### ISSUE TITLE
Import of SVG-file fails with extraction (returns undefined)

### ISSUE THREAD

**Issue by wanecek** [kisenka/svg-sprite-loader#106]
With my current build-process, the `import` of an SVG-file returns `undefined` when extraction is turned on. with `{ extract: off }` it returns an object as expected per documentation.

I have created a [reduced test-case](https://github.com/wanecek/svg-sprite-loader-test-case ), which I will hope assist the debugging process.

**Details of my setup:**
 - Windows 10
 - Node v. 7.2.1
See [package.json](https://github.com/wanecek/svg-sprite-loader-test-case/blob/master/package.json) for further details.

**To Reproduce:**

 - Download the [test-case](https://github.com/wanecek/svg-sprite-loader-test-case/) and install dependencies.
 - Start up the project with `npm start`. This should launch your web-browser at `http://localhost:3000`.
 - Open the console, and see that `undefined` is logged by `Shell.vue:12`, which attempts to log the `import` of `./assets/arrow.svg`.
  - In [`build/webpack.base.conf.js:59`](https://github.com/wanecek/svg-sprite-loader-test-case/blob/master/build/webpack.base.conf.js#L59), set `extract: true` and run the build process again.

**Comment by kisenka** [comment]
I found 3 issues:
1. svg-sprite-loader in extract mode sometimes return wrong symbol url. It was fixed in `svg-sprite-loader@2.1.0-1` (beta).
2. Sprite loader plugin used twice - [here](https://github.com/wanecek/svg-sprite-loader-test-case/blob/3e8c2d9743f1ac138bb887e566b48db6be5ab6fb/build/webpack.base.conf.js#L84) and [here](https://github.com/wanecek/svg-sprite-loader-test-case/blob/3e8c2d9743f1ac138bb887e566b48db6be5ab6fb/build/webpack.dev.conf.js#L34).
3. I am not sure, but looks like `<svg><use xlink:href/></svg>` embed method will not work with external sprite. I've [replaced](https://github.com/kisenka/svg-sprite-loader-test-case/blob/ac5b3e0bd39565bacb06f9082c4d06f0b533c528/src/Shell.vue#L3) it with `<img src="sprite.svg#id">` and it works:

![image](https://cloud.githubusercontent.com/assets/2714771/25802152/b6986ed6-33f9-11e7-9de3-fdb8a4981869.png)

Check my fork with updates - https://github.com/kisenka/svg-sprite-loader-test-case

**Comment by wanecek** [comment]
Hi! Thank you very much for your reply and your thorough help!

I've taken note of the issues you found (sorry for the duplicate SpriteLoaderPlugin - my bad), and fixed them in recent commits. Furthermore, I've vastly simplified my test-case, e.g. by removing `Vue` from the build.

What I found was that using the beta-version removed the support for SpriteSymbol - instead a (system-relative) path is logged.

If you have more time to debug, I've pushed my changes to the same repo as before.

Thank you for your kind help and patience.

**Comment by kisenka** [comment]
I think I understand what you want - svg image should goes to external sprite, but symbol (`SpriteSymbol<id: string, viewBox: string, content: string>`) should returns from import statement instead of symbol url. Am I right?

**Comment by kisenka** [comment]
#107

**Comment by wanecek** [comment]
That is exactly what I want! :) Is that not the expected behavior?

**Comment by kisenka** [comment]
Basically not, but I'll think about it. However it can be done via custom runtime generator, it was created for cases when you need some special stuff :) I've added example with extract mode in __interop__ branch:
- [Example dir](https://github.com/kisenka/svg-sprite-loader/tree/8f08971d6ed457a3cb9ff54fcf30b800f239a157/examples/custom-runtime-in-extract-mode)
- [source code](https://github.com/kisenka/svg-sprite-loader/blob/8f08971d6ed457a3cb9ff54fcf30b800f239a157/examples/custom-runtime-in-extract-mode/main.js)
- [built code](https://github.com/kisenka/svg-sprite-loader/blob/8f08971d6ed457a3cb9ff54fcf30b800f239a157/examples/custom-runtime-in-extract-mode/build/main.js#L74). Here you can see that loader returns object with width. height, viewBox and url props, but sprite is in separate file - sprite.svg
- [runtime generator implementation](https://github.com/kisenka/svg-sprite-loader/blob/8f08971d6ed457a3cb9ff54fcf30b800f239a157/examples/custom-runtime-in-extract-mode/extracting-runtime-generator.js), rather simple

**Comment by wanecek** [comment]
This is great, thank you! I'm very thankful of your commitment.

I'm still running into some issues with the sprite-loading though. More specifically, I cannot get the `url` to output the correct fragment-URL (e.g. `sprite.svg#twitter-usage`). 

I've updated the [test-case](https://github.com/wanecek/svg-sprite-loader-test-case) with the runtime generator, where it's evident that the `url` is `undefined` when using `2.0.5`, and the system-relative path when using `beta`. 

For `2.0.5`, in the `runtime-generator`, `symbol.request` is `C:\Users\NUC-10\Desktop\svg-sprite-loader-test-case\src\assets\arrow.svg` and the spritePlaceholder is `{{sprite-filename|C:\Users\NUC-10\Desktop\svg-sprite-loader-test-case\src\assets\arrow.svg}}`

**Comment by kisenka** [comment]
As I said [here](https://github.com/kisenka/svg-sprite-loader/issues/106#issuecomment-299841258):
> svg-sprite-loader in extract mode sometimes return wrong symbol url. It was fixed in svg-sprite-loader@2.1.0-1 (beta).

**Comment by wanecek** [comment]
I've noted that. Unfortunately, this still returns the system-relative path instead of the build-relative path (i.e. `C:\web\mainstream\src\assets\icons\logo.svg` instead of `sprite.svg#logo`.)

If this is the expected behavior, it'd be lovely if you could give me a pointer for what to modify.
If not, and this is an issue, I can help resolve the issue if you give me pointers to as where to look :)

**Comment by kisenka** [comment]
That strange. Could you push latest changes in your repo so I can check?

**Comment by WalterZou** [comment]
@kisenka I have the same problem as @wanecek got: 
> I've noted that. Unfortunately, this still returns the system-relative path instead of the build-relative path (i.e. C:\web\mainstream\src\assets\icons\logo.svg instead of sprite.svg#logo.)
> If this is the expected behavior, it'd be lovely if you could give me a pointer for what to modify.
If not, and this is an issue, I can help resolve the issue if you give me pointers to as where to look :)

When `extract: true ` 
Input:
``` 
<img src="./logo.svg" alt="">
```
Output:
```
<img src="[object Object]" alt="">
```

**Comment by kisenka** [comment]
@WalterZou could you please create repo with your setup?

**Comment by wanecek** [comment]
@kisenka Commits are pushed to the [repository](https://github.com/wanecek/svg-sprite-loader-test-case)

**Comment by kisenka** [comment]
Got it, it's Windows path resolving issue. I will have access to Windows machine tomorrow, stay tuned!

**Comment by wanecek** [comment]
Excellent @kisenka! Thank you very much for your help

**Comment by kisenka** [comment]
@wanecek please check `svg-sprite-loader@2.1.0-3`

**Comment by wanecek** [comment]
Works like a charm! Thank you for all your help Kisenka.
