### ISSUE TITLE
Svg empty when extract: false

### ISSUE THREAD

**Issue by tleunen** [kisenka/svg-sprite-loader#110]
I wanted to have a configuration that extract my svg automatically when I build for production, so I explicitely set `extract: true` or `extract: false`, and I've noticed that as soon as I do that, my svg's are empty (or invisible).

So it seems that as soon as I explicitely set this value, it doesn't give the right output.

I don't really know how to debug this so let me know what you need :)

**Comment by kisenka** [comment]
I need more information of your setup - could you setup a repo with webpack config & minimum code which reproduces described case.

**Comment by tleunen** [comment]
I'll keep this on the side, I haven't got the time to investigate further. It might be complicated to try reproducing that in another project.

Will try during the weekend and I'll report back or close the ticket. Thanks.

**Comment by kisenka** [comment]
@tleunen ping

**Comment by kisenka** [comment]
@tleunen ping again

**Comment by tleunen** [comment]
Sorry, I don't really have time to test again or try to create another app with the issue. Feel free to close for now if you'd like. I haven't tested a more recent version of the svg-sprite-loader as well.
