### ISSUE TITLE
Typo: localtion

### ISSUE THREAD

**Issue by jrencz** [kisenka/svg-sprite-loader#112]
https://github.com/kisenka/svg-sprite-loader/search?utf8=✓&q=localtion&type=

When used with angular1 it triggers `TypeError: Cannot read property 'href' of undefined`

**Comment by jrencz** [comment]
I haven't yet found where it comes from but it may be some of dependencies

**Comment by jrencz** [comment]
Ok: I found that it has already been fixed yet it's probably not released: https://github.com/kisenka/svg-baker/commit/33cebc1525cff12b58a685a4776f5c7f096c8334

**Comment by jrencz** [comment]
@kisenka feel free to close this one but I think it should stay until new version with updated dependency is released

**Comment by kisenka** [comment]
Fixed in `svg-sprite-loader@2.1.0`
