### ISSUE TITLE
Incorrect sprite in css if also used in JS

### ISSUE THREAD

**Issue by jrencz** [kisenka/svg-sprite-loader#113]
I tried using the same SVG both as background in CSS and in `<use>` by importing a reference to it in JS and it only worked in JS. In CSS the SVG file was just injected into `url()`, not turned into a reference (`sprite.svg#idOfSymbol`).

When I copied the SVG file so one is used in Js and the other in CSS it works.

**Comment by kisenka** [comment]
Please provide your webpack config

**Comment by jrencz** [comment]
```js
{
  module: {
    loaders: [
      {
        test: /sprite(?:s)?\/.*\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          extract: true,
        },
      },
    ]
  },
  plugins: [
    new SpriteLoaderPlugin(),
  ]
}
```

I use https://github.com/kisenka/svg-sprite-loader/blob/master/examples/assets/twitter.svg as `example.svg`

I include it 2 times in my project:
once using `<use>` (via angular1 component, but it's not relevant) and it works:
<img width="542" alt="screen shot 2017-05-15 at 08 52 29" src="https://cloud.githubusercontent.com/assets/948356/26045803/1f7154c0-394c-11e7-9969-038da872c38a.png">
<img width="573" alt="screen shot 2017-05-15 at 08 52 10" src="https://cloud.githubusercontent.com/assets/948356/26045819/32592d24-394c-11e7-9f23-3865c64c4118.png">


And another time as element background:
<img width="345" alt="screen shot 2017-05-15 at 08 55 49" src="https://cloud.githubusercontent.com/assets/948356/26045833/4e086d6e-394c-11e7-8049-0e7d3e529530.png">
where it doesn't work:
<img width="280" alt="screen shot 2017-05-15 at 08 52 22" src="https://cloud.githubusercontent.com/assets/948356/26045826/42e34ba2-394c-11e7-895b-8cf142af832b.png">

Whether there's SpriteLoaderPlugin or not does not seem to matter (but: I don't get warned in case it's missing)

**Comment by kisenka** [comment]
Sorry for the delay, are you sure svg-sprite-loader is only once who process SVGs? Could you please create repo with minimal demo code - webpack config, package.json, svg images & pieces of code which import images.

**Comment by kisenka** [comment]
@jrencz ping

**Comment by jrencz** [comment]
Sorry, I'm busy with other parts of the project not related to svg. I can't tell you where will I have more time to create simplified demo.

I'm sure those svg are only processed by this loader. They are filtered by a regexp which only takes svg files from a certain directory and there another one (file loader) which processes all others

**Comment by Grsmto** [comment]
I had the same issue. I had to set the following configuration:
```
extract: true,
esModule: false
```

and then in my js, append `/sprite.svg`:
```
<svg>
      <use xlinkHref={`/sprite.svg#${glyph.id}`} />
    </svg>
```

**Comment by kisenka** [comment]
@Grsmto you're right, it's a configuration issue. Should be mentioned in FAQ.
