### ISSUE TITLE
Extract mode doesn't extract if a don't import any icons?

### ISSUE THREAD

**Issue by trumbitta** [kisenka/svg-sprite-loader#114]
I'm trying to make the loader create a sprite from some svg icons I have in `assets/icons`.

Relevant Webpack config:

```JS
            {
                test: /\.svg$/,
                loader: 'svg-sprite-loader',
                include: /assets\/icons/,
                options: {
                    extract: true
                }
            },
```

I have ` new SpriteLoaderPlugin()`.

The extraction seems to occur only if I comment the `include` option and the loader then finds the old svg icon font imported by the CSS icon file. Of course, my new SVG icons in `assets/icons` are always ignored.

I don't import those icons anywhere in my JavaScript code, and I don't intend to, because I'll have a simple Angular component and will use the `<svg><use>` technique.

I just need something to get the single SVG icon files and bundle them into a symbol sprite with some optimisations (I'm going to chain `svgo-loader`).

Can I do this with `svg-sprite-loader`?

**Comment by kisenka** [comment]
In any case you should somehow tell webpack about your icons. You can create separate entry point and use webpack "globbing import" - [require.context](https://webpack.js.org/guides/dependency-management/#require-context), for example:

```js
const modules = require.context(/assets\/icons/, false, /\.svg$/);
files.keys().forEach(files);
```

**Comment by trumbitta** [comment]
Makes sense, thanks :)
