### ISSUE TITLE
How to pass `syncUrlsWithBaseTag`

### ISSUE THREAD

**Issue by 285858315** [kisenka/svg-sprite-loader#116]
https://github.com/kisenka/svg-baker/blob/master/packages/svg-baker-runtime/src/browser-sprite.js#L39

**Comment by kisenka** [comment]
You want to disable or enable this option?

**Comment by 285858315** [comment]
Yes.I very need.

**Comment by kisenka** [comment]
1. Create your own sprite file - `my-sprite.js`
2. Copy contents of default [browser-sprite](https://github.com/kisenka/svg-sprite-loader/blob/master/runtime/browser-sprite.js) and add your logic:
```js
import BrowserSprite from 'svg-baker-runtime/src/browser-sprite';
import domready from 'domready';

const sprite = new BrowserSprite({ syncUrlsWithBaseTag: true }); // your option
domready(() => sprite.mount(document.body));

export default sprite;
```
3. Specify path to your custom sprite in loader [spriteModule](https://github.com/kisenka/svg-sprite-loader#spritemodule-autoconfigured) config option:
```js
{
  test: /\.js$/,
  loader: 'svg-sprite-loader',
  options: {
    spriteModule: './my-sprite.js'
  }
}
```

**Comment by kisenka** [comment]
@285858315 does it work for you?
