### ISSUE TITLE
Problem with release 2.1.0

### ISSUE THREAD

**Issue by jrencz** [kisenka/svg-sprite-loader#119]
When I try to install with version number constraint `^2.1.0` I get npm error:

```
npm ERR! notarget No compatible version found: svg-sprite-loader@^2.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.1.0-3, 2.1.0-2, 2.1.0-1, 2.1.0-0, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0-alpha.4, 2.0.0-alpha.3, 2.0.0-alpha.2, 2.0.0-alpha.1, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.21, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.3, 0.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

On the other hand here, on GH in releases one can see 2.1.0 released

**Comment by jrencz** [comment]
`2.1.0-3` gets installed ok

**Comment by mattdarveniza** [comment]
Yeah seems it hasn't been published to npm yet?

**Comment by jrencz** [comment]
I see another one: browser-sprite.build.js shipped with 2.1.0-3 is still the old one.
@kisenka May it be that you didn't flush dependencies before releasing and you still had the old one? That's how it looks.

**Comment by kisenka** [comment]
Sorry guys, just published 2.1.0

**Comment by jrencz** [comment]
2.1.0 works ok

But I tried to reconfigure the loader so it uses the runtime directly form svg-baker instead of the bundled one. I wasn't able because the values I passed as options were overridden by auto-configuration. @kisenka was that your intention?

**Comment by kisenka** [comment]
@jrencz I need your config to check what's happening. Demo repository will be the best

**Comment by jrencz** [comment]
I'm afraid I don't have time to provide you with one right now. I'll let you know if I find some

**Comment by kisenka** [comment]
Ok, closing this. Feel free to open another issue about your problem.
