### ISSUE TITLE
`svg use` on external sprite file

### ISSUE THREAD

**Issue by thasmo** [kisenka/svg-sprite-loader#120]
How would I use the generated SVG sprite by referencing the file directly as an external resource?
```svg
<svg>
	<use xlink:href="/static/sprite.svg#icon-html5-usage"/>
</svg>
```
This doesn't seem to render anything. I suppose the inlined CSS in the SVG sprite prevents it being used as an external resource.

Is there a solution to use it this way?

**Comment by thasmo** [comment]
Basically I'm trying to use [this method](https://css-tricks.com/svg-symbol-good-choice-icons/#article-header-id-1).

**Comment by kisenka** [comment]
It's just not working in browsers at all with external sprite, you can try it yourself without sprite-loader. I think it's because `<use>` tag should refer to existing node in DOM (even it's a part of a shadow DOM).

**Comment by thasmo** [comment]
Nowadays it works in most (modern) browsers. Even in Edge. (But not in IE.) [Temporary demo.](https://thasmo.com/svg/)

**Comment by thasmo** [comment]
There are also solutions to kinda polyfill it for non-supported browsers like [svg4everybody](https://github.com/jonathantneal/svg4everybody) and they also show an [example](https://github.com/jonathantneal/svg4everybody#usage) of how to use external files.

**Comment by kisenka** [comment]
Hmm, interesting. Looks like browsers supports only references to symbols itself. Use URL to symbol then - `/static/sprite.svg#icon-html5` (without `-usage`).

**Comment by thasmo** [comment]
Oh, true - it didn't work for me in the first place because I had a protocol-mismatch. What is the use-case for actually wrapping the `symbol` elements in a `defs` element and adding separate `use` elements within the generated SVG file? Wouldn't it just work right away by using the `symbol` elements directly?

**Comment by kisenka** [comment]
For referencing from CSS - no, see [related discussion](https://github.com/kisenka/svg-sprite-loader/issues/122).
