### ISSUE TITLE
Symbols vs. Stacking

### ISSUE THREAD

**Issue by timkelty** [kisenka/svg-sprite-loader#122]
Curious why this uses svg "stacking" vs. multiple symbols (which seems like a more modern approach): https://css-tricks.com/svg-symbol-good-choice-icons/

Or is there a way to implement this behavior I'm missing?

**Comment by timkelty** [comment]
Ah ok...I guess I was a bit confused, it appears you _are_ doing multiple symbols w/ IDs.

But then you're also calling those symbols with `<use>` and using the `:target` technique.
Why do we need to do both?

**Comment by princed** [comment]
What do you mean by target technique?

**Comment by timkelty** [comment]
Including this css:
```
<style>use {display: none;} use:target {display: inline;}</style>
```

This is only  necessary when you're stacking with `<defs>/`<g>` elements. If you're using `symbol`, they [don't display as you define them](https://css-tricks.com/svg-symbol-good-choice-icons/#article-header-id-2).

**Comment by kisenka** [comment]
Because if you refer to image in external sprite, e.g. `.logo {background-image: url(sprite.svg#symbol_id)}` symbol won't renders by itself, you should render it manually. That's why `:target` is used.

**Comment by timkelty** [comment]
@kisenka Ah, I didn't realize that!
I thought a fragment identifier for a symbol would display (though I knew there were browser compat. issues).

Thanks!

**Comment by princed** [comment]
@kisenka Should we document it maybe?

**Comment by kisenka** [comment]
@princed yep
