### ISSUE TITLE
Clafiry documentation about using loader with style-loader

### ISSUE THREAD

**Issue by silicakes** [kisenka/svg-sprite-loader#127]
## description
during development, using the following relative url call: `background: url(../path/to/file.svg);`
produces the following output: `background: url([object object]);`

However, the output for the build seems to be fine, as it correctly compiles into: `url(icon-d3a90#file-usage);` 

there are no issues when using it from a js (.tsx in my case) file.

## environment
Node 7.7.1
webpack 2.3.3
svg-sprite-loader 3.0.2
macOS Sierra

## webpack configuration (relevant parts)
```
rules: [ {
			test: /\.scss$/,
			use: [
				{
					loader: 'style-loader'
				}, {
					loader: 'css-loader',
					options: {
						modules: true,
						minimize: true,
						localIdentName: '[name]__[local]___[hash:base64:5]',
						importLoaders: 1
					}
				}, {
					loader: 'sass-loader',
				}
			]
		},{
			test: /\.svg$/,
			use: [{
				loader: 'svg-sprite-loader',
				options: {
					extract: true,
					spriteFilename: "icon-[hash:5].svg"
				}
			}, {
				loader: 'svgo-loader',
				options: {
					plugins: [
						{removeTitle: true},
						{convertColors: {shorthex: false}},
						{convertPathData: false}
					]
				}
			}]
		}]
```

**Comment by kisenka** [comment]
@silicakes could you please create a demo repo with your setup (package.json, webpack.config.js and piece of code), so I can help you.

**Comment by silicakes** [comment]
@kisenka ofcourse:
https://github.com/silicakes/svg-sprite-loader-demo

**Comment by kisenka** [comment]
Just curious, what the usecase of using single image in both ways: with js runtime and as CSS background?

**Comment by silicakes** [comment]
I've updated my example for a possible use-case where an "expandable" component uses the same svg icon as a custom select box, feel free to pull and have a look.

The reason you'd want the select's custom arrow to be a background image is so that the click will propagate and the box will open.

I've also added an additional svg Icon to show that even if it's being used by itself as a background image - it still breaks.

**Comment by kisenka** [comment]
I get it, I mean why not use all SVGs as background-images in CSS?

**Comment by silicakes** [comment]
Because more than often, you'd like to attach various events to the SVG element itself, without wrapping it with another DOM element.

Additionally, in my opinion, when using React, it's more appropriate to use a component that will generate DOM, rather than an inline style attribute.

**Comment by kisenka** [comment]
> Because more than often, you'd like to attach various events to the SVG element itself, without wrapping it with another DOM element.

You don't need to wrap anything, moreover it will save one DOM node (if it's important), just compare:
- `<svg class="icon" viewBox="..."><use xlink:href="#id"></use></svg>` (2 nodes)
- `<div class="icon"></div>` (1 node)

Loader does not support using 1 image in two ways: as part of JS sprite and as background image from CSS. It's hard to implement, loader is rather complex now and implementing this feature will increase complexity. Also it increases complexity for developer - you will need to setup 2 rules for SVGs in webpack config. But the most inconvenient thing - import statements for one of these two ways should contain query params, e.g. `background-image: url(./image.svg?qwe)`. Only in this case webpack will generate 2 different modules per image. 
It's just not worth it. Just select one method and use it :)

**Comment by silicakes** [comment]
@kisenka - Are you talking about re-using the same svg icon? i.e using `foo.svg` in both a module and inside a css file?
because this is not the case here:
In my demo, I've use `plus.svg` just inside the css and it still got it as an object.

**Comment by kisenka** [comment]
Ok, one thing should be clarified - of you're using style-loader `esModule` svg-sprite-loader option should be always `false`. It should be mentioned in FAQ, but I has no time now to do that.

**Comment by silicakes** [comment]
>- of you're using style-loader esModule svg-sprite-loader option should be always false
You mean something like this?
```
{
loader: 'svg-sprite-loader',
	options: {
		extract: true,
		spriteFilename: "icon-[hash:5].svg",
		modules: false
	}
}
```
because that doesn't seem to work.

**Comment by kisenka** [comment]
> `esModule` svg-sprite-loader option should be always `false`.

```js
{
    loader: 'svg-sprite-loader',
    options: {
        extract: true,
        spriteFilename: "icon-[hash:5].svg",
        esModule: false
    }
}
```
