### ISSUE TITLE
RuntimeGenerator doesn't work with UglifyJsPlugin

### ISSUE THREAD

**Issue by valentinvoilean** [kisenka/svg-sprite-loader#128]
The svg-sprite-loader doesn't seem to work when a **runtimeGenerator** is used together with the **uglifyjs** plugin.

I get this error when the UglifyJsPlugin is enabled:
```
ERROR in js/vendorsc88a34a326b89f72f8ec.js from UglifyJs
Unexpected token: name (BookingNewIcon) [js/vendorsc88a34a326b89f72f8ec.js:57757,10]
```

I used the same code like in [this file](https://github.com/kisenka/svg-sprite-loader/blob/master/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator.js) to create the runtime generator.

The UglifyJSPlugin doesn't have extra options.
```
plugins: [
  new webpack.optimize.UglifyJsPlugin()
]
```

**Comment by kisenka** [comment]
Please, don't remove default issue template. I need you to create simple repo to with webpack.config.js, package.json and piece of code to demonstrate the issue.

**Comment by kisenka** [comment]
As UglifyJsPlugin breaks on `class BookingNewIcon ...` looks like you didn't setup es6->es5 transpilation for code returned by sprite-loader. You should add babel-loader after sprite-loader:

```js
{
  test: /\.svg$/,
  use: [
    'babel-loader',
    {
      loader: 'svg-sprite-loader',
      options: {
        runtimeGenerator: require.resolve('./svg-to-icon-component-runtime-generator'),
        runtimeOptions: {
          iconModule: './icon.jsx' // Relative to current build context folder
        }
      }
    }
  ]
}
```

**Comment by valentinvoilean** [comment]
Thanks a lot. That was the problem. I forgot to include the "babel-loader".
