### ISSUE TITLE
Webpack target 'web' not detected

### ISSUE THREAD

**Issue by pascalw** [kisenka/svg-sprite-loader#131]
**Do you want to request a feature, report a bug or ask a question?**

Bug.

**What is the current behavior?**

SVG is not injected into the page. After some fiddling I noticed that in [configurator.js](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/configurator.js) the `target` variable is undefined, resulting in the `isomorphicSpriteModule` being used instead of the `browser-sprite` module.

**What is the expected behavior?**

SVG to be injected into the page. I have not set any webpack target, which should default to `web`.

**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**

I don't have a repro case ready. However changing `const target = context.options.target` to `const target = context.target` seems to fix the issue as `context.target` contains `web`. This leads me to believe that the code is simply looking at the wrong variable?

**Comment by pascalw** [comment]
Reading the [Webpack loader docs](https://webpack.js.org/api/loaders/#this-target) I indeed believe that `target` resides directly on the loader context, not on `options.target`.

**Comment by kisenka** [comment]
@pascalw please check `svg-sprite-loader@3.0.3`

**Comment by pascalw** [comment]
Thanks @kisenka, works!

**Comment by kisenka** [comment]
Coooooooool
