### ISSUE TITLE
Make sprite stacking CSS and markup optional in extract mode

### ISSUE THREAD

**Issue by ShimShamSam** [kisenka/svg-sprite-loader#132]
**Do you want to request a feature, report a bug or ask a question?**
Feature

**What is the current behavior?**
Extract mode always includes a &lt;style> tag and markup for sprite stacking.

**What is the expected behavior?**
An option to turn this off for those who use &lt;svg>&lt;use>&lt;/use>&lt;/svg> exclusively.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Apart from the extraneous data in the exported SVG file, my build setup compiles down to a single CSS and JS file which I hash and include as a nonce in my [Content Security Policy](https://content-security-policy.com/) header. Since this new version now injects an extra &lt;style> tag for sprite stacking, the console throws a silent error that the &lt;style> tag doesn't have an associated nonce in the CSP.

Example:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'sha256-PQmX2D20LVTxXMw/q0RwlgRtaZJZqCjZkLD0q1xzyDY='". Either the 'unsafe-inline' keyword, a hash ('sha256-Kl0oOFCXNACC8wRypDy0qfmAZG1Rd1IPJyGPcb2SthQ='), or a nonce ('nonce-...') is required to enable inline execution.

**Please tell us about your environment:**

- Node.js version: 7.6.0
- webpack version: 2.6.1
- svg-sprite-loader version: 3.0.3
- OS type & version: Windows 10

**Comment by kisenka** [comment]
@ShimShamSam I wish you suggest the name of this option.

**Comment by ShimShamSam** [comment]
## spriteStacking (default: true)
Whether or not to include markup to support [sprite stacking](https://css-tricks.com/svg-fragment-identifiers-work/#article-header-id-4) (allows references to sprites via &lt;img src="icons.svg#my-icon">)

**Comment by kisenka** [comment]
Related issue https://github.com/kisenka/svg-baker/issues/4

**Comment by kisenka** [comment]
@ShimShamSam sorry for the delay, this feature is shipped in `svg-sprite-loader@3.3.0`.
