### ISSUE TITLE
This Plugin doesn't work with svg generated from Sketch

### ISSUE THREAD

**Issue by Temp2017** [kisenka/svg-sprite-loader#134]
This plugin doesn't work with svg generated from sketch.
Shows parser error "NameSpace prefix sketch for type g is not defined" at sketch:type="MSPage" place in generated svg sprite.
Node Version 6.10.0
-------------------------------------------------------------------

![image](https://cloud.githubusercontent.com/assets/28975869/26711362/755ddaa4-477d-11e7-8293-2a90ba81b3cf.png)

**Comment by kisenka** [comment]
@Temp2017 please don't remove issue template, it's crafted for detailed issue reporting and save a lot of my and your time. Please update an issue and fill [following template](https://github.com/kisenka/svg-sprite-loader/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by kisenka** [comment]
@Temp2017 ping
