### ISSUE TITLE
Is it possible to load svg files from node_modules directory?

### ISSUE THREAD

**Issue by piotrkulpinski** [kisenka/svg-sprite-loader#136]
Hi guys,
Does anyone know is it possible to load svg files from node_modules directory?
I'd want to use the new Feather Icons by @colebemis (https://github.com/colebemis/feather) but can't get it to work.

My current SVG loader config:
```
{
  test: /\.svg$/,
  loader: 'svg-sprite-loader?' + JSON.stringify({
    name: '[name]_[hash]',
    prefixize: true
  }),
  include: [
    resolve('src/assets/icons'),
    resolve('node_modules/feather-icons/icons/core'),
    resolve('node_modules/feather-icons/icons/arrows'),
    resolve('node_modules/feather-icons/icons/logos'),
  ],
  options: {
    modules: true
  }
}
```

Let me point out that the icons stored in `src/assets/icons` are working perfectly. The problem is only with external packages from node_modules.

- Node.js version: 7.7.4
- webpack version: 2.3.3
- svg-sprite-loader version: 3.0.3
- OS type & version: MacOS 10.12.5

**Comment by kisenka** [comment]
You are using old loader config format, there is no `name` and `prefixize` in > 2.x sprite-loader versions (check [migration guide](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md)). Also  using `loader: 'svg-sprite-loader?' + JSON.stringify` in combination with `options: {...}` is also incorrect in webpack 2. BTW there is no `modules` option, but `esModule`, check [configuration section of readme](https://github.com/kisenka/svg-sprite-loader#configuration).
You should also provide part of your code where you trying to import icons from node_modules.

**Comment by piotrkulpinski** [comment]
Thanks @kisenka!

So I've updated the config to match the v2.x and it looks like that: 
```
{
  test: /\.svg$/,
  loader: 'svg-sprite-loader',
  include: [
    resolve('src/assets/icons'),
    resolve('node_modules/feather-icons/icons/core'),
    resolve('node_modules/feather-icons/icons/arrows'),
    resolve('node_modules/feather-icons/icons/logos'),
  ]
}
```
And then I reference the fonts like that:
```
<svg>
  <use xlink:href="icon-name"></use>
</svg>
```
While the icons from `src/assets/icons` are still working, I still can't get it to work with `node_modules`.

**Comment by piotrkulpinski** [comment]
@kisenka I was able to make it work finally.
Thank you for your time!

**Comment by kisenka** [comment]
Always welcome!

**Comment by ilyanoskov** [comment]
@piotrkulpinski how did you solve the issue? Can you please show the final solution

**Comment by piotrkulpinski** [comment]
@ilyanoskov 

It was an issue with SVG files not the loader. 
I fixed that by using an SVGO loader to clean the files.

Here's the final webpack config:
```
{
  test: /\.svg$/,
  use: [
    {
      loader: 'svg-sprite-loader'
    },
    {
      loader: 'svgo-loader',
      options: {
        plugins: [
          {
            removeAttrs: {
              attrs: 'stroke.*'
            }
          }
        ]
      }
    }
  ],
  include: [
    resolve('src/assets/icons'),
    resolve('node_modules/feather-icons/icons'),
  ]
}
```
