### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by sshmyg** [kisenka/svg-sprite-loader#137]
Hi, can I change output path, when I use extract option?

**Comment by kisenka** [comment]
Use [`spriteFilename`](https://github.com/kisenka/svg-sprite-loader#spritefilename-default-spritesvg) option.

**Comment by serheyShmyg** [comment]
I tried to use this option, but got something strange behaviour. 
`spriteFilename: '../img/sprite.svg'` - this is my param.
SVG file creation doesn't stop at all, and file size become larger and large.
And http://prntscr.com/fhr23q this is console view.

**Comment by kisenka** [comment]
This is an incorrect filename, `img/sprite.svg` should be used

**Comment by serheyShmyg** [comment]
I need to go out from my cwd and choose another one.

**Comment by kisenka** [comment]
@serheyShmyg what do you mean?

**Comment by serheyShmyg** [comment]
Resolved in another way. Thnks

**Comment by serheyShmyg** [comment]
Sorry but `img/sprite.svg` also generate a huge sprite.
Any additional routes for spriteFilename option are not appropriate.

**Comment by serheyShmyg** [comment]
@kisenka Can you check it?

**Comment by kisenka** [comment]
Check what? I need a demo repo with your setup. Please fill [this issue template](https://github.com/kisenka/svg-sprite-loader/blob/master/.github/ISSUE_TEMPLATE.md) and don't remove it next time, because it was crafted for report issues effectively.

**Comment by kisenka** [comment]
@sshmyg ping, I still need a demo from you :)
