### ISSUE TITLE
Allow to have an option to only export symbolID (to benefit more from server side rendering)

### ISSUE THREAD

**Issue by Axnyff** [kisenka/svg-sprite-loader#139]
**Do you want to request a feature, report a bug or ask a question?**
Feature

**What is the current behavior?**
Now that server side rendering of svg is possible, the svg are loaded twice into the dom: by the server and then by the client. The webpack bundle needs to have all the svg data and also needs to have the runtime.

**What is the expected behavior?**
Allow to have an option for the loader which will return something lighter:
module.exports = {symbolId: "some-svg-id"};

**If this is a feature request, what is motivation or use case for changing the behavior?**
Reducing bundle size, avoiding to dynamically append svg data already provided by the server.
Unless I'm missing something there's no way do to this without writing a specific loader for the client side.

I'd be willing to do a pull request if you think this could be valuable.
Anyway, thanks in advance and thanks for your awesome loader

**Comment by kisenka** [comment]
Hello @Axnyff!
Please check [server-side rendering example](https://github.com/kisenka/svg-sprite-loader/tree/master/examples/server-side-rendering) and [resulting bundle](https://github.com/kisenka/svg-sprite-loader/blob/master/examples/server-side-rendering/build/main.js). As you can see Isomorphic sprite runtime is used.

**Comment by Axnyff** [comment]
Hi, thanks for your answer. I'm not sure I was very clear in my post, I made a repository to clarify:

https://github.com/Axnyff/example

In here, I'm taking advantage of server side rendering, following your example to preload my svg for my application.
However, my front is also loading the svg: 
the runtime is going to append the svg in the dom
the bundle is going to contain all of the content of the svg whereas it only needs the ids to properly work.

This could be simply be solved by quickly putting together a loader but I think it would be better to have only one loader for all svg.

**Comment by Axnyff** [comment]
I would like an option to allow for a minimal bundle: only the id to match the svg rendered on the server side.

**Comment by Axnyff** [comment]
You are perfectly right!

**Comment by kisenka** [comment]
This is hard, but doable.
Webpack caches each import output. When you import image for the first time, resulting output will be used _everywhere_ for following imports. For example `require('./image.svg')` will always produce `module.exports = 'sprite.svg#image'`). To have different outputs for single image the import statement should also be different, e.g.: 
- `require('./image.svg')` => `module.exports = {/* SVG data */}`
- `require('./image.svg?ref')` => `module.exports = "id"`

And finally you should write custom runtime generator which cover different import cases.

**Comment by Axnyff** [comment]
Nice, thanks a lot for your time
