### ISSUE TITLE
Webpack banner plugin breaks the extracted output

### ISSUE THREAD

**Issue by sidonaldson** [kisenka/svg-sprite-loader#142]
**Do you want to request a feature, report a bug or ask a question?**
Bug / Resolution / Question - should it be covered in docs?

**What is the current behavior?**
In production mode I use the webpack banner plugin - it injects a banner into the generated SVG and breaks it

**What is the expected behavior?**
SVGs work

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**
add into your webpack build:
```
new webpack.BannerPlugin({
	banner: util.format('%s (v%s)\nAuthored by %s - %s', pkg.name, pkg.version, pkg.author.name + ', ' + pkg.contributors.join(', '), new Date().toUTCString())
			})
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
Trying to help others with a possible fix or doc update

**Please tell us about your environment:**

- Node.js version: 6.11
- webpack version: 2.6.1
- svg-sprite-loader version: latest
- OS type & version: mac latest

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

I fixed it by excluding the file:
```
new webpack.BannerPlugin({
       exclude:'sprite-name.svg',
	banner: util.format('%s (v%s)\nAuthored by %s - %s', pkg.name, pkg.version, pkg.author.name + ', ' + pkg.contributors.join(', '), new Date().toUTCString())
			})
```

The most preferable way to resolve this is to prevent the banner from being injected, but otherwise this is a very easy fix in the webpack config and it might help others.

**Comment by kisenka** [comment]
@sidonaldson thanks for sharing this, I'll add it to docs.
