### ISSUE TITLE
Intermittently the <use/> do not populate (Extracted sprite) (Chrome only)

### ISSUE THREAD

**Issue by sidonaldson** [kisenka/svg-sprite-loader#143]
**Do you want to request a feature, report a bug or ask a question?**

Bug or a question

**What is the current behavior?**

I use SVG's all over my react app and all load fine with one exception. I have a sidebar that lists multiple items and is re-rendered in all together. On first load it works fine, often the second and third time it also works - but once it refreshed a few times the SVGs disappear. The markup is correctly injected but the shadowdom shows nothing internally. It's almost like the can't find the matching ID's from the spite

**What is the expected behavior?**

All SVGs to show

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
[https://gist.github.com/sidonaldson/c32b3127e432176433051a43d95a2089](https://gist.github.com/sidonaldson/c32b3127e432176433051a43d95a2089
)
**Please tell us about your environment:**

- Node.js version: 6.11
- webpack version: 2.61
- svg-sprite-loader version: latest
- OS type & version: Mac OS latest

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

Possibly this issue here: [https://stackoverflow.com/questions/35049842/svgs-in-chrome-sometimes-dont-render](https://stackoverflow.com/questions/35049842/svgs-in-chrome-sometimes-dont-render)

How is the sprite requested each time and is there a way I can force it to be cached?

**Comment by ruisalgado** [comment]
I was having this issue with intermittently SVGs not rendering. I changed to [Extract Configuration](https://github.com/kisenka/svg-sprite-loader#extract-configuration) (instead of having the svg appended to document.body) and that seems to have solved it for me.

**Comment by sidonaldson** [comment]
@ruisalgado I am already using extract:true. It's so strange that it only happens in chrome (canary is the same too!)

Since my build is based on `express` I was able to add proxy route that simply adds a caching header
```
router.all('/*.svg', (req, res, next) => {
	res.setHeader("Cache-Control", "private, max-age=6000"); // 1hr
	next();
});
```

This solves it for production, not sure how to handle it for webpack and the dev server!

**Comment by alinchican** [comment]
@sidonaldson I'm experiencing the same issue while using [devServer](https://webpack.js.org/configuration/dev-server/).

Based on your answer I've added Cache-Control in [devServer.headers](https://webpack.js.org/configuration/dev-server/#devserver-headers-) as a workaround. Be aware that this adds Cache-Control to all responses.

```javascript
devServer: {
  headers: {
    "Cache-Control": "private, max-age=6000" // Read https://github.com/kisenka/svg-sprite-loader/issues/143
  }
}
```
