### ISSUE TITLE
Webpack 3's ModuleConcatenationPlugin breaks output

### ISSUE THREAD

**Issue by epiloque** [kisenka/svg-sprite-loader#146]
**Do you want to request a feature, report a bug or ask a question?**

Bug

**What is the current behavior?**

svg-sprite-loader extract mode works without `ModuleConcatenationPlugin`, however with `ModuleConcatenationPlugin` it simply does not emit the svg sprite.

- Node.js version: 8.1.2
- webpack version: 3
- svg-sprite-loader version: ? 3.0.5 
- OS type & version: ? linux

**Comment by fvsch** [comment]
I can reproduce this issue.
(After a few hours of unsuccessfully trying to find the right combination of config ^^)

**Comment by thasmo** [comment]
Can confirm this too. When using `ModuleConcatenationPlugin` no sprite-file is written.
- node 6.11.1
- webpack 3.3.0
- svg-sprite-loader 3.0.6

**Comment by kisenka** [comment]
Guys, please help me with my investigation - create an repo with reproducible error.

**Comment by thasmo** [comment]
@kisenka Absolutely! :)

Please have a look at https://github.com/thasmo/test-svg-sprite-loader-146

**Comment by kisenka** [comment]
Shipped with `svg-sprite-loader@3.1.0`

**Comment by epiloque** [comment]
Thank you very much Stas!

**Comment by thasmo** [comment]
Awesome! :)

**Comment by kisenka** [comment]
Please test it. `[chunkname]` placeholder in `symbolName` config option isn't working, please follow the #168.

**Comment by silicakes** [comment]
@kisenka 

on webpack 3.5.2 / node v8.2.1 I get the following:

>  /Users/mike-work/dev/world-client/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11
>   const { request, issuer, loaders } = module;
>                                        ^
> 
> TypeError: Cannot match against 'undefined' or 'null'.
>     at isModuleShouldBeExtracted (/Users/mike-work/dev/world-client/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11:40)
> 

Apparently  ` this.spriteModules = this.allModules.filter(isModuleShouldBeExtracted);` inside `mapped-list.js`

I'm not sure as to the cause of it all.

**Comment by kisenka** [comment]
@silicakes please update to the last loader version, I've just fixed this in #172

**Comment by silicakes** [comment]
Perfect, thanks!
