### ISSUE TITLE
Exception: 2 rules applies to svg

### ISSUE THREAD

**Issue by katiasmet** [kisenka/svg-sprite-loader#149]
**Do you want to request a feature, report a bug or ask a question?**
Question, i guess.

**What is the current behavior?**
Compiling fails because of my svg. 
Failed to compile.
./src/_assets/svg/twitter.svg
svg-sprite-loader exception. 2 rules applies to /Applications/MAMP/htdocs/launchpad/src/_assets/svg/twitter.svg
 @ ./src/_js/script.js 1:0-53
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/_scss/style.scss ./src/_js/script.js ./src/index.html

Some snippets of the files can be found here: https://gist.github.com/katiasmet/d5a4cc15592e58f56678f475b29b3b6b

**What is the expected behavior?**
Same as the example of the browser-sprite. Inline svg and using it with <use>. 

**Please tell us about your environment:**

- Node.js version: v6.11.0
- webpack version: 3.0.0
- svg-sprite-loader version: 3.0.5 (svgo-loader: 1.2.1) 
- OS type & version: OSX Sierra

I use the Webpack dev server.

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
I tried different svg's so I don't think the svg is the problem. Maybe it's a conflict with the webpack dev server?

**Comment by colepatrickturner** [comment]
I also came across this issue. I looked into the code and it appears to originate from matching the rules:

https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils/get-matched-rules.js#L10

With Webpack 2 you can apply loaders differently depending on the issuers, for example in CSS I use url and file loader, while using svg sprite loader for JS. I believe this would need to be accommodated when matching rules, or to remove this check altogether?

**Comment by kisenka** [comment]
@colepatrickturner thanks, 3.0.6 with your update is published.

**Comment by nikuz** [comment]
Same issue in 3.2.4:
```javascript
{
     test: /\.svg$/,
     use: 'svg-sprite-loader',
}
```

import upArrow from '../assets/svg/up.svg';

Result:
```bash
WARNING in ./app/assets/svg/up.svg
svg-sprite-loader exception. 2 rules applies to
```

**Comment by JimVercoelen** [comment]
I don't get it. Is this supposed to be solved at 3.0.6? Because I am facing the same problem using 3.0.6.

Can other rules cause this problem? 

@katiasmet You managed to solve this problem? Because I am using the same config for this loader as you have.

**Comment by kisenka** [comment]
@JimVercoelen could you please check latest version?

**Comment by antongunkin** [comment]
Same problem...

**Comment by katiasmet** [comment]
@JimVercoelen I used another plugin. But it doesn't have all the features of this one. So a solution would be nice :(. 

https://github.com/mrsum/webpack-svgstore-plugin

**Comment by kisenka** [comment]
@katiasmet @antongunkin it will be very useful if some of you guys create git repo with reproducible error. In this way I will assist quickly :)

**Comment by kisenka** [comment]
@katiasmet still actual?

**Comment by irodger** [comment]
I had same problem and it was a url-loader make base64 from svg. I solved this problem by exclude svg from url-loader.

**Comment by vercoelenmike** [comment]
Same problem, this problem is still alive

**Comment by vercoelenmike** [comment]
@JimVercoelen @katiasmet @irodger 

The problem here is that you are using more than 1 webpack `rule` for handling `svg` file types, so you prob. have a rule going for either images or fonts.

You should exclude ur `icons` folder, and it's solved.

**Comment by anrn** [comment]
Is it possible to use more than one rule? I try to use this loader with webpacker 3 (it's ruby on rails gem) and you cannot really manage all rules and change settings easily in that case.

**Comment by anrn** [comment]
Is it possible to use more than one rule? I try to use this loader with webpacker 3 (it's ruby on rails gem), in that case you cannot really manage all rules and change prepared settings.

**Comment by kisenka** [comment]
@anrn this warning broke your compilation somehow?

**Comment by anrn** [comment]
@kisenka Yes, after warning I have an error:
`Module build failed: InvalidSvg: svg-sprite-loader exception.`
Other default loader didn't change anything in svg file, it just modified name with adding hash

**Comment by kisenka** [comment]
Dropped this silly warning in `svg-sprite-loader@3.5.3`, please update!

**Comment by katiasmet** [comment]
@kisenka sorry for the late reply. But i managed to make it work :)

**Comment by chess126** [comment]
@vercoelenmike 
thx.. i found myself forget to add 'exclude'.. lol
`      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/icons')],  //
        options: {
          symbolId: 'icon-[name]',
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        exclude: [resolve('src/icons')],  // folders other than src/icons use url-loader
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },`

**Comment by chess126** [comment]
@vercoelenmike 
thx.. i found myself forget to add 'exclude'.. lol

      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: [resolve('src/icons')],  //
        options: {
          symbolId: 'icon-[name]',
        }
      },
      {
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'url-loader',
        exclude: [resolve('src/icons')],  // folders other than src/icons use url-loader
        options: {
          limit: 10000,
          name: utils.assetsPath('img/[name].[hash:7].[ext]')
        }
      },

**Comment by SteGreig** [comment]
> @JimVercoelen @katiasmet @irodger
> 
> The problem here is that you are using more than 1 webpack `rule` for handling `svg` file types, so you prob. have a rule going for either images or fonts.

Does anyone know how I can fix this in a Gatsby project? After installing the gatsby-plugin-svg-sprite package, simply importing an SVG file into a component like this:

`import icon from "../images/bars-regular.svg"`

results in the following error:

`Cannot find module 'webpack/package.json'`

It sounds like I need to stop url-loader from processing my SVG icons that I want to be processed by gatsby-plugin-svg-sprite (svg-sprite-loader) but I can't see how to do this anywhere?
