### ISSUE TITLE
working with existing svg sprite

### ISSUE THREAD

**Issue by omryr** [kisenka/svg-sprite-loader#153]
Hi I am looking for a way to load existing svg sprite i created using Icons8 website.
right now I have a sprite and I want to use it in a build with webpack, is there a way to do so? and is there a way to import just that sprite without having to make import for each of the svg's it holds? like import svgsprite from './icons/svg-sprite' and later use that to refrence all the svg's with their id?
something like <use xlinkhref=svgsprite#id> ?

I couldnt find an answer to that in the documentation it keeps refrencing an import from assets folder which i dont have, since i dont have an svg folder but a ready to use sprite

**Comment by kisenka** [comment]
The quick answer is no, please see https://github.com/kisenka/svg-sprite-loader/issues/151#issuecomment-314107776 for details.
