### ISSUE TITLE
doubt about my server side rendering configuration

### ISSUE THREAD

**Issue by lemoustachiste** [kisenka/svg-sprite-loader#155]
**Do you want to request a feature, report a bug or ask a question?**
bug/question

**What is the current behavior?**
I have a simple webpack configuration in order to generate the HTML of my app on the server.
```javascript
var path = require('path')

var commonLoaders = [
  ...,
  {
    test: /\.svg$/,
    loaders: ['svg-sprite-loader']
  }
  ...,
]

module.exports = [
  {
    // The configuration for the server-side rendering
    name: 'server-side rendering',
    entry: path.join(__dirname, './pre-render.js'),
    target: 'node',
    output: {
      filename: path.join(__dirname, './generated.js'),
      libraryTarget: 'commonjs2'
    },
    externals: /^[a-z\-0-9]+$/,
    module: {
      loaders: commonLoaders
    }
  }
]
```

looking here: https://github.com/kisenka/svg-sprite-loader/tree/master/examples/server-side-rendering it seems that I am correctly using the `node` option for the `target` key in the config.

Compiling is ok, but when I try to render the page, I am getting this error:

```
ReferenceError: document is not defined
    at new Sprite (path/to/generated.js:22431:22)
```

And looking at that line, here is the code generated:
```javascript
function Sprite() {
	  var baseElement = document.getElementsByTagName('base')[0]; // --> faulty line
	  var currentUrl = window.location.href.split('#')[0];
	  var baseUrl = baseElement && baseElement.href;
	  this.urlPrefix = baseUrl && baseUrl !== currentUrl ? currentUrl + DEFAULT_URI_PREFIX : DEFAULT_URI_PREFIX;
```

**What is the expected behavior?**
From what I understand, `svg-sprite-loader` should not make references to `document` when used in node context. Am I doing something wrong or is this a bug? 

- Node.js version: v6.9.1
- webpack version: 1.15.0
- svg-sprite-loader version: 5.0.3 
- OS type & version: Mac OS 10.12.4

**Comment by andreyMakahov** [comment]
I have the same error.

**Comment by kisenka** [comment]
I can't reproduce this error. Please make a repo with package.json, webpack config, SVG image and piece of your code.

**Comment by lemoustachiste** [comment]
Hi @kisenka, thanks for your answer. I'm a bit busy this week, but I'll try to do that this friday.

**Comment by kisenka** [comment]
@lemoustachiste friendly ping

**Comment by lemoustachiste** [comment]
Hi @kisenka, I will not have time to get back to this before my vacation. We can close this for now, and I'll reopen if it's still an issue when I try again.

Sorry for any inconvenience and thanks for your support.

**Comment by kisenka** [comment]
@lemoustachiste it's strange that browser sprite used in node env, try to set spriteModule manually: 

```js
{
  test: /\.js$/,
  loader: 'svg-sprite-loader',
  options: {
    spriteModule: 'svg-sprite-loader/runtime/sprite.build'
  }
}
```

But firstly upgrade to the latest loader version, maybe this bug was resolved.
