### ISSUE TITLE
My svgs are not loading after upgrading webpack and svg-sprite-loader.

### ISSUE THREAD

**Issue by sourvb** [kisenka/svg-sprite-loader#156]
SVGs are not loading. I think I am missing some minor configurations.

I have upgraded from webpack_1.13.2 to webpack_2.2.1 and svg-sprite-loader_0.0.31 to svg-sprite-loader_3.0.6. Basically, I did an `npm-check-updates -u && npm install` to update all packages in my project. My svgs were loading fine before updating. 
But after updating, my svgs are not loading. This [gist](https://gist.github.com/sourvb/15e2ded246f40aefae0dbe84d1db48cf) includes a sample svg I am using, webpack dev config file, my react component SvgIcon.js and a sample page where I am loading the icon. None of the SVGs are loading and all I get is the below error in browser console.

> Request URL:http://localhost:8080/%3Csymbol%20viewBox=%220%200%2022%2043%22%20id=%22left-arrow%22%3E%20%20%20%20%3C!--%20Generator:%20sketchtool%2042%20(36781)%20-%20http://www.bohemiancoding.com/sketch%20--%3E%20%20%20%20%3Ctitle%3EA137762E-488D-4A78-ACB6-542445894CF6%3C/title%3E%20%20%20%20%3Cdesc%3ECreated%20with%20sketchtool.%3C/desc%3E%20%20%20%20%3Cdefs%3E%3C/defs%3E%20%20%20%20%3Cg%20id=%22left-arrow_Page-1%22%20stroke=%22none%22%20stroke-width=%222%22%20fill=%22none%22%20fill-rule=%22evenodd%22%20opacity=%221%22%3E%20%20%20%20%20%20%20%20%3Cg%20id=%22left-arrow_Property-page-resdiental_show-more%22%20transform=%22translate(-51.000000,%20-965.000000)%22%20fill=%22
> Request Method:GET
> Status Code:404 Not Found
> Remote Address:127.0.0.1:8080

**Comment by kisenka** [comment]
Please add package.json because I need to use the same versions to reproducing an issue.

**Comment by sourvb** [comment]
Thanks for your time. Due to close deadline, I have reverted all the updates. Will ping again once I start the task of updating my project again.

**Comment by kisenka** [comment]
Okay, I'll ping you back after some time :)

**Comment by kisenka** [comment]
@sourvb still actual? If no, please close an issue.

**Comment by sourvb** [comment]
I am using svg-inline-loader now which fixed my issue. Thanks.

**Comment by kisenka** [comment]
@sourvb ah sorry, I've missed your gist, 0.x version behaviour can be enabled via `runtimeCompat: true` [config option](https://github.com/kisenka/svg-sprite-loader/#runtimecompat-default-false-deprecated).

**Comment by gazpachu** [comment]
@kisenka I also had to enable `runtimeCompat: true` to make it work with the latest version. What do we have to change in our code to be able to get rid of `runtimeCompat`?

**Comment by kisenka** [comment]
@gazpachu from [migration guide](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md):

> Runtime symbol is an object now (class instance actually). It contains `id`, `viewBox` and `content` fields. See [SpriteSymbol class](https://github.com/kisenka/svg-baker/blob/55082f1310964572fba15f27427664ecc04b11f0/packages/svg-baker-runtime/src/symbol.js).

**Comment by gazpachu** [comment]
Thanks. I fixed it now :)
