### ISSUE TITLE
Icon id is not added into the style rules

### ISSUE THREAD

**Issue by ghostd** [kisenka/svg-sprite-loader#157]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
The icon id is not added into the <style /> element when the style has a font-family with a string value:
```css
.st5{font-family:'WebFont';}
```

**What is the expected behavior?**
The icon id is added into the <style /> element. The <style /> element should be:
```css
#icon-id .st5{font-family:'WebFont';}
```

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**
SVG sample:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 219.4 373.2" style="enable-background:new 0 0 219.4 373.2;" xml:space="preserve">
<style type="text/css">
	.st5{font-family:'WebFont';}
</style>
<path class="st0" d="M219.4,348c0,13.9-9.7,25.2-21.7,25.2H21.7C9.7,373.2,0,361.9,0,348V25.2C0,11.3,9.7,0,21.7,0h176.1
	c11.9,0,21.7,11.3,21.7,25.2V348z"/>
</svg>
```

**Please tell us about your environment:**

- Node.js version: 8.1.2
- webpack version: 3.3.0
- svg-sprite-loader version: 3.0.6
- OS type & version: Linux Ubuntu

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
The bug only occurs when svgo-loader (version 1.2.1) is also used.

Webpack loader settings:
```js
    {
      test: /icons\/.+\.svg/,
      use: [
        {
          loader: 'svg-sprite-loader',
          options: {
            symbolId: 'icon-[name]'
          }
        },
        {
          loader: 'svgo-loader',
          options: {
            plugins: [
              { removeTitle: true }
            ]
          }
        }
      ]
    }
```

**Comment by ghostd** [comment]
I dug into the code, so here is my explanation about this bug (and a potential fix):

`svgo-loader` (actually `svgo`) returns a modified `style` element with the following content:
`.st5{font-family:&apos;WebFont&apos;;}`
(which is compliant with the HTML specification, but for now [this behavior cannot be disabled](https://github.com/svg/svgo/issues/176))

`posthtml` parses the source and returns the style content without evaluating the HTML entities. The node content received by prefixStyleSelectors is:
```
[ '.st5{fill:#00f;font-family:&apos;WebFont&apos;}' ]
```

`postcss` parses the string with the `apos` entity and throws an exception:
```
CssSyntaxError {
  name: 'CssSyntaxError',
  reason: 'Unknown word',
  source: '.st5{fill:#00f;font-family:&apos;WebFont&apos;}',
  line: 1,
  column: 34,
  message: '<css input>:1:34: Unknown word',
  input: 
   { line: 1,
     column: 34,
     source: '.st5{fill:#00f;font-family:&apos;WebFont&apos;}' } }
```
The exception is silently ignored by `svg-sprite-loader` (i manually added a try/catch to see it), maybe a console warn would be usefull.

To fix that, i changed the `posthtml-svg-mode` Processor#process implementation to pass the `decodeEntities` option to the posthtml parser:
```js
  process(ast, options = null) {
    const opts = Object.assign({ parser }, options);

    opts.parser = (html) => postHtmlParser(html,
      {
        lowerCaseTags: false,
        lowerCaseAttributeNames: false,
        decodeEntities: true,
        xmlMode: true
      }
    );

    return this.posthtml.process(ast, opts).then(({ tree }) => new PostHTMLProcessingResult(tree));
  }
```
And i changed the prefixStyleSelectors implementation to join the text node as specified by the HTML specification: 

> All descendant elements must be processed, according to their semantics, before the style element itself is evaluated. For styling languages that consist of pure text (as opposed to XML), user agents must evaluate style elements by passing the concatenation of the contents of all the Text nodes that are children of the style element (not any other nodes such as comments or elements), in tree order, to the style system.
```js
node.content = postcss().use(prefixSelectors({ prefix })).process(styles.join('')).css;
```

**Comment by kisenka** [comment]
@ghostd great job! Will fix it soon

**Comment by kisenka** [comment]
@ghostd BTW why you not use inlining CSS styles in SVG elements? It's much safe for such cases.

**Comment by ghostd** [comment]
@kisenka i just integrate SVG, the people creating those files are using Adobe Illustrator (that generates <style /> elements).

**Comment by kisenka** [comment]
@ghostd published as svg-sprite-loader@3.1.2.

**Comment by ghostd** [comment]
@kisenka thanks

I tested on my project, but now all my icons with a <style /> element look like:
```html
<style><div>#icon-alert .st0{fill:#f9b000}#icon-alert .st1{fill:#fff}</div></style>
```

I've no time this week to dig into, hope next week i can look for why we have this `<div />` into our style.

**Comment by kisenka** [comment]
@ghostd could you provide an image source?

**Comment by ghostd** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 21.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Calque_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 61 52" style="enable-background:new 0 0 61 52;" xml:space="preserve">
<style type="text/css">
	.st0{fill:#F9B000;}
	.st1{fill:#FFFFFF;}
</style>
<path class="st0" d="M60.3,46.5c1.8,3.1,0.4,5.6-3.2,5.6H3.9c-3.6,0-5-2.5-3.1-5.5L27.3,2.3c1.8-3,4.8-3,6.6,0L60.3,46.5z"/>
<g>
	<path class="st1" d="M30.5,20.5c-7.1,0-12.8,5.7-12.8,12.8c0,7,5.7,12.8,12.8,12.8c7.1,0,12.8-5.7,12.8-12.8
		C43.3,26.2,37.6,20.5,30.5,20.5z M30.5,43.2c-5.5,0-10-4.5-10-10c0-5.5,4.5-10,10-10c5.5,0,10,4.5,10,10
		C40.5,38.8,36,43.2,30.5,43.2z"/>
	<path class="st1" d="M37.2,32.7l-5.6-0.8l-2-4c-0.4-0.7-1.4-1.1-2.1-0.7c-0.4,0.2-0.7,0.5-0.8,0.9c-0.1,0.4-0.1,0.8,0.1,1.2
		l2.7,5.5l7.3,1c0.1,0,0.1,0,0.2,0c0.8,0,1.4-0.6,1.6-1.4c0-0.1,0-0.1,0-0.2C38.5,33.5,37.9,32.8,37.2,32.7z"/>
</g>
</svg>
```

And the settings:
```
use: [
        {
          loader: 'svg-sprite-loader',
          options: {
            symbolId: 'icon-[name]'
          }
        },
        {
          loader: 'svgo-loader',
          options: {
            plugins: [
              { removeTitle: true }
            ]
          }
        }
      ]
```

**Comment by ghostd** [comment]
@kisenka i think the regression comes from this commit:
https://github.com/kisenka/svg-baker/commit/936e7d61c53b6f813a66373cee36c59183c73696

i think `.css` is missing, it should be (in `prefix-style-selectors.js`):
```js
      return postcss()
        .use(prefixSelectors({ prefix }))
        .process(content)
        .then(prefixedStyles => node.content = prefixedStyles.css);
```

**Comment by kisenka** [comment]
@ghostd I've publish svg-baker@1.2.12 [with fix](https://github.com/kisenka/svg-baker/commit/41756a6ecb4ea07b78db46af9110bb0c11fe4268), please update svg-sprite-loader dependencies and tell me if it's now working.

**Comment by ghostd** [comment]
@kisenka i'll test the both fix tomorrow (i'm not at the office today)

**Comment by kisenka** [comment]
@ghostd deal, I'll be waiting for you

**Comment by ghostd** [comment]
@kisenka i tested the both fix, all seems working here.

i think i made a little mistake in https://github.com/kisenka/svg-baker/pull/13/files
`document.querySelectorAll('style');` could be replaced by `node.querySelectorAll('style');` since we want IE to re-evalute the style of the symbol, not all styles of the whole document

**Comment by kisenka** [comment]
Yup, I got that and refactor a bit [your code](https://github.com/kisenka/svg-baker/blob/7ca725d9ba8a25f0a53fbb76fe8aeb01313e14d6/packages/svg-baker-runtime/src/utils/eval-styles-ie-workaround.js#L15).
