### ISSUE TITLE
svg-sprite-laoder doesn't work with React

### ISSUE THREAD

**Issue by Feel-Joy** [kisenka/svg-sprite-loader#160]
I want ask a question

I want load svg images in my React component, so I used `svg-sprite-loader` and `svgo-loader`, but it doesn't work

webpack config:
```js
// nothing else to process svg images
{
  test: /\.svg$/,
  include: path.resolve('./static'),
  use: [
    'svg-sprite-loader',
    'svgo-loader',
  ],
},
```

component:
```jsx
import React, {PureComponent} from 'react';
import cssModule from 'react-css-modules';

import styles from './index.css';
import react from '../../../static/react.svg';

@cssModule(styles)
export default class Home extends PureComponent {
  render() {
    return (
        <svg><use xlinkHref={react} /></svg>
    );
  }
}
```

when I run the project, I got nothing, here is the request:
<img width="991" alt="2017-07-27 10 42 47" src="https://user-images.githubusercontent.com/25546299/28676504-5d89d150-731d-11e7-8d9a-986508329337.png">

can somebody help me to deal with this problem?

- Node.js version: v 6.11.1
- webpack version: v 3.0.0
- React version: v 15.6.1
- svg-sprite-loader version: v 3.0.7
- svgo-loader version: v 1.2.1 
- OS type & version: macOS v10.12.6

**Comment by kisenka** [comment]
@Feel-Joy please create a repo with reproducible issue, I have no time to investigate it by myself.

**Comment by swesh** [comment]
@Feel-Joy , Try it like
```

import React, {PureComponent} from 'react';
import cssModule from 'react-css-modules';

import styles from './index.css';
import react from '../../../static/react.svg';

@cssModule(styles)
export default class Home extends PureComponent {
  render() {
    return (
        **<svg><use xlinkHref={'#'+react.id} /></svg>**
    );
  }
}

```

**Comment by aga5tya** [comment]
@swesh I'm able to get it to work with react-universally boilerplate. Use this as reference and should work for you too

https://github.com/aga5tya/react-universally/tree/svg-sprite-test
https://github.com/aga5tya/react-universally/commit/423c0af375d9207ea775287c968e7c74c0539643
