### ISSUE TITLE
[IE/Edge] (async) SVG icons are rendered black

### ISSUE THREAD

**Issue by ghostd** [kisenka/svg-sprite-loader#167]
**Do you want to request a feature, report a bug or ask a question?**
bug

**What is the current behavior?**
The same as described in #163 when the symbol is load asynchronously.

I create a new issue, because the previous fix does not work when i load some react component which are loading icons. I think the workaround we added into `runtime/browser-sprite.js` can be called with no symbols, then the symbols are added but the workaround is not re-called.

I think the workaround should be refactored/copied into the `svg-baker-runtime/browser-sprite#add` method; it needs to be called for each added symbol

What is your pov about this @kisenka?

**Comment by kisenka** [comment]
@ghostd agreed, could you make a PR in svg-baker?

**Comment by ghostd** [comment]
I will, but i wont have spare time before next week.

**Comment by ghostd** [comment]
https://github.com/kisenka/svg-baker/pull/13

**Comment by kisenka** [comment]
@ghostd published as svg-baker-runtime@1.2.99, try to update svg-sprite-loader dependencies. I'll revert this soon, as I plan to fix #165 and #8.

**Comment by ghostd** [comment]
@kisenka i just tested the 3.2.0, and this works partially. The bug is still present on Edge. I think your [last refactoring](https://github.com/kisenka/svg-baker/commit/6f92906635535e37d811091ce834d1780583ba66) removed a condition (or was it intentional?).
```js
if (browser.isIE) {
    evalStylesIEWorkaround(symbolNode);
}
```
should be
```js
if (browser.isIE || browser.isEdge) {
    evalStylesIEWorkaround(symbolNode);
}
```

**Comment by kisenka** [comment]
@ghostd thank you for reviewing me :) Publish a new 3.2.0 version with the fix.

**Comment by ghostd** [comment]
All seems working now. Thanks a lot for your work :)
