### ISSUE TITLE
Windows path problem

### ISSUE THREAD

**Issue by fr-ench** [kisenka/svg-sprite-loader#17]
I've been trying to use 'entry' options to automatically load SVG sprite on windows machine.

My publicPath is  *'./dist'*.
Webpack plugin settings are
            <code>new SvgStore("svg/icons/**/*.svg", "/", {
                    name: '[hash].sprite.svg',
                    chunk: 'head'
            })</code>

The code path.join(publicPath, filePath) from 109 line in index.js produces this code in the resulting chunk head.js:
<code>svgXHR('\dist\8239235be0f2ba409fac873fb004346b.sprite.svg');</code>

This causes the xhr request 404 error as the path is being read in javascript as 'dist8239235be0f2ba409fac873fb004346b.sprite.svg'.

**Comment by kisenka** [comment]
@fr-ench perhaps you're looking for [webpack-svgstore-plugin](https://github.com/mrsum/webpack-svgstore-plugin) repo?

**Comment by fr-ench** [comment]
@kisenka, oh yes, I'm sorry.

**Comment by kisenka** [comment]
@fr-ench you're welcome! :smile:
