### ISSUE TITLE
Runtime generator not found

### ISSUE THREAD

**Issue by saadshahd** [kisenka/svg-sprite-loader#171]
Hi,

Thank you for the great loader!

I'm not sure if it's a bug or not, But I'm getting this exception:
> Module build failed: InvalidRuntimeException: svg-sprite-loader exception. Runtime generator "/home/service-manager/conf/svg-to-icon.js" not found

While I'm hundred percent sure  the file is there and I could view it through the same relative path `less /home/service-manager/conf/svg-to-icon.js`.

Could you please help? https://gist.github.com/saadshahd/d2a5a4b1eb163a62f8b4bc8b0b37a7bc

- Node **7.7.1**
- Webpack **2.2.1**
- svg-sprite-loader **3.1.2**
- OS Ubuntu **16.04**

**Comment by kisenka** [comment]
@saadshahd the real error was `Cannot find module 'pascal-case'`, I've updated loader error reporting, now it's displays real error message. Published as `svg-sprite-loader@3.1.3`.
