### ISSUE TITLE
Error after minor webpack update 3.4.1 -> 3.5.1

### ISSUE THREAD

**Issue by Flamme13** [kisenka/svg-sprite-loader#172]
/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11

const { request, issuer, loaders } = module;
-----------------------------------------------^
TypeError: Cannot match against 'undefined' or 'null'.

**Comment by Flamme13** [comment]
Sorry, this error after update webpack 3.4.1 -> 3.5.1

webpack 3.4.1
(node:10555) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

3.5.1
/node_modules/svg-sprite-loader/lib/utils/is-module-should-be-extracted.js:11
const { request, issuer, loaders } = module;
----------------------------------------------^
TypeError: Cannot match against 'undefined' or 'null'.

**Comment by kisenka** [comment]
I've add a hotfix for this, publish as 3.1.4

**Comment by kisenka** [comment]
Related issue webpack/webpack/issues/5477

**Comment by salmanm** [comment]
@kisenka Looks like there's [one more place](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/plugin.js#L188) we need to fix this issue.

**Comment by salmanm** [comment]
Accessing `modules` property throws a warning from [here](https://github.com/webpack/webpack/blob/webpack-3/lib/Chunk.js#L469). 
It anyway already defaults to `({ modules } = chunk);`, so the declaration can just be `let modules;`.

WDYT?
