### ISSUE TITLE
Deprecation warning with webpack 3: Module.chunks

### ISSUE THREAD

**Issue by silicakes** [kisenka/svg-sprite-loader#173]
**Do you want to request a feature, report a bug or ask a question?**
bug
**What is the current behavior?**
The following deprecation message appears:

> (node:3170) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead

**What is the expected behavior?**
No deprecation warning

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
## relevant config:
```
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');

plugins: [
	new SpriteLoaderPlugin()
],
```

**Please tell us about your environment:**

- Node.js version: v8.2.1
- webpack version: 3.5.2
- svg-sprite-loader version: 3.1.3 
- OS type & version: MacOS Sierra

**Comment by kisenka** [comment]
Shipped with svg-sprite-loader@3.2.3
