### ISSUE TITLE
spriteFilename naming pattern

### ISSUE THREAD

**Issue by vchrm** [kisenka/svg-sprite-loader#174]
Hi, when using `file-loader`, I use `[sha1:hash:base36:10].[ext]` naming pattern for extracted files, but I am unable to use the same configuration for svg-sprite-loader (@3.1.5). Pattern `[hash:base36:10]` somehow works, but I am unable to define `hashType`. Setting `spriteFilename` to `[sha1:hash:base36:10].svg` creates a file named `[sha1:hash:base36:10].svg` :-).

Is there a way out? Thank you.

**Comment by kisenka** [comment]
Use spritehash instead of hash - `[sha1:spritehash:base36:10]`

**Comment by vchrm** [comment]
Is that supposed to work? For me `spriteFilename: "assets/[sha1:spritehash:base36:10].svg"` creates a file named `[sha1:spritehash:base36:10].svg`.

**Comment by kisenka** [comment]
@vchrm ah sorry, now I get it. It's a bug.

**Comment by kisenka** [comment]
@vchrm fixed in svg-sprite-loader@3.1.6

**Comment by vchrm** [comment]
@kisenka Thank you for your work :).
