### ISSUE TITLE
Gradients rendered differently on server and client sprites

### ISSUE THREAD

**Issue by rjokelai** [kisenka/svg-sprite-loader#177]
**Do you want to request a feature, report a bug or ask a question?**
- [x] Bug report

**What is the current behavior?**

Browser sprite renders the linear gradients correctly outside of the symbols. However, the server sprite leaves them inside the symbols, causing them to fail on Firefox.

#### Sprite rendered on server
<img src="https://user-images.githubusercontent.com/1803028/29349465-bf497a22-8262-11e7-97bc-09d313377544.jpg" width="638">

Image of the rendered SVG on Firefox
![bffef7dc-2de7-4329-a39e-1b153d93468c](https://user-images.githubusercontent.com/1803028/29349610-89af1286-8263-11e7-9c9e-84200746dba9.jpg)

#### Sprite rendered in client
<img src="https://user-images.githubusercontent.com/1803028/29349466-bfc722ec-8262-11e7-8282-bd4caadc10f9.jpg" width="316">

Image of the rendered SVG on Firefox
![b6a4c752-8178-418c-9ecb-d2998265f3db](https://user-images.githubusercontent.com/1803028/29349611-8b0f330e-8263-11e7-9791-8dd40515c2f0.jpg)

**What is the expected behavior?**

The server sprite should render the linear gradients similarly to the client.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: 6.9.5
- webpack version: 2.6.1
- svg-sprite-loader version: 3.1.6
- OS type & version: macOS 10.12.6, Firefox 54.0.1

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by kisenka** [comment]
That's true. And unfortunately there is no way to do this, because at node env sprite treated as string. We either need to parse it via posthtml (again!) or use regular expressions (even worse). 
Actually we have the same content on client and on server, but on client additional JS runtime is used, which [move gradients outside symbols](https://github.com/kisenka/svg-baker/blob/7ca725d9ba8a25f0a53fbb76fe8aeb01313e14d6/packages/svg-baker-runtime/src/browser-sprite.js#L60). The quick way is to use a part from this code: 

**your app.js**
```js
import moveGradiends from 'svg-baker-runtime/src/utils/move-gradients-outside-symbol';

document.addEventListener('DOMContentLoaded', () => {
  moveGradients(document.querySelector('body svg:first-child'));
});
```

**Comment by rjokelai** [comment]
Sadly, that won't work if we want the pages to work without JS. I guess we can live without the gradients for now, though.

**Comment by kisenka** [comment]
@rjokelai just curious, how many users without JS you have? :)

**Comment by rjokelai** [comment]
Hopefully not many 😄 I guess I just don't want to have multiple layers of JS, since we're already bootstrapping the angular app then afterwards.

Anyway, closing this since we have an adequate solution.

**Comment by kisenka** [comment]
Yeah, it's possible with server sprite, but it's a complex way. Feel free to reopen if you'll really need this solution and we'll discuss.

**Comment by paramjitkaur** [comment]
Has there been any solution to this as I am running into the same issue
