### ISSUE TITLE
Icons doesn't load in async-imported modules.

### ISSUE THREAD

**Issue by dangreen** [kisenka/svg-sprite-loader#182]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
Icons doesn't load in async-imported modules.

**What is the expected behavior?**
Icons should be loaded in async-imported modules.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**
```js
// component.js
export default function SomeComponent() {
  return <SomeSvgIcon/>;
}
// main.js
import('./component').then((module) => {
  render(module.default, document.querySelector('#root'));
});
```
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: 7
- webpack version: 2
- svg-sprite-loader version: 2.1.0
- OS type & version: macOS Sierra

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by kisenka** [comment]
@dangreen does it works with lazy imports?

**Comment by dangreen** [comment]
@kisenka after update to v3 all has become ok
