### ISSUE TITLE
svg-sprite-loader not working in nuxt.js application

### ISSUE THREAD

**Issue by unwrittenmike** [kisenka/svg-sprite-loader#185]
**Do you want to request a feature, report a bug or ask a question?**
Report a bug
**What is the current behavior?**
Compiled with 1 warnings                                              
 warning  in ./assets/icons/big-loader.svg
svg-sprite-loader exception. 2 rules applies to 
**What is the expected behavior?**
No warnings and sprite to load
**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
`config.module.rules.push({
        test: /\.svg$/,
        loader: 'svg-sprite-loader'
      })`

`import test from '~/assets/icons/big-loader.svg'
`
<svg><use xlink:href="#big-loader"></use></svg>
**Please tell us a
bout your environment:**

- Node.js version: v8.1.4
- webpack version: 3.5.5
- svg-sprite-loader version: 3.2.4
- OS type & version: ? MasOs 10.12.6

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by kisenka** [comment]
I need the whole webpack config to be sure that is a loader bug

**Comment by unwrittenmike** [comment]
Hi there see below:
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin')
module.exports = {
/*
** Headers of the page
*/
head: {
title: 'nissanconfig',
meta: [
{ charset: 'utf-8' },
{ name: 'viewport', content: 'width=device-width, initial-scale=1' },
{ hid: 'description', name: 'description', content: 'Nuxt.js project' }
],
link: [
{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
]
},
/*
** Customize the progress-bar color
*/
loading: { color: 'red' },
css: [
'~/assets/fonts/stylesheet.css',
{ src: '~/assets/main.scss', lang: 'scss' }
],
/*
** Build configuration
*/
build: {
plugins: [
new SpriteLoaderPlugin()
],
extend(config, ctx) {
if (ctx.dev && ctx.isClient) {
config.module.rules.push({
enforce: 'pre',
test: /\.(js|vue)$/,
loader: 'eslint-loader',
exclude: /(node_modules)/
})
}
config.module.rules.push({ test: /\.svg$/, loader: 'svg-sprite-loader' })
}
}
}

**Comment by unwrittenmike** [comment]
That a nuxt.js config...

**Comment by vanoorschot** [comment]
@unwrittenmike You can extend the nuxt default webpack in the nuxt.config.js.
Nuxt already has it's own webpack config (https://nuxtjs.org/guide/assets/#webpacked) which uses the 'url-loader' for svg files.
I don't think this is a bug in svg-sprite-loader, but a conflict with the nuxt webpack configuration.
   
Right now I have the same problem ;)

**Comment by vanoorschot** [comment]
@unwrittenmike I created an issue with Nuxt, to ask how this can be achieved.
Meanwhile I wrote a hack to get it working.

See my ticket for the implementation:
https://github.com/nuxt/nuxt.js/issues/1584

**Comment by unwrittenmike** [comment]
@vanoorschot  Thanks! Your hack works for me! ... sat for a a full day trying to get this working.. total legend!

@kisenka Sorry for pointing the blame at your library...

**Comment by jesperlandberg** [comment]
Is there a chance someone could show me a full implementation/solution to this? How the config looks and how the icon is imported into the components because I can't seem to get this working. Would be extremely grateful.

**Comment by unwrittenmike** [comment]
@jesperlandberg I'll post a link to some code for you a bit later today. I have it running smoothly in 2 nuxt.js apps ;)

**Comment by jesperlandberg** [comment]
@unwrittenmike would be awesome=)

**Comment by unwrittenmike** [comment]
@jesperlandberg Here you go:
[https://unwrittenmike@bitbucket.org/unwrittenmike/spriteloadertest.git](url)

**Comment by unwrittenmike** [comment]
@jesperlandberg Happy to answer any questions you may have...

**Comment by jesperlandberg** [comment]
@unwrittenmike awesome! Looks like the repo doesnt exist tho?

**Comment by unwrittenmike** [comment]
@jesperlandberg try this, sorry new to sharing repos...  not the hottest git guy haha... [https://bitbucket.org/unwrittenmike/spriteloadertest](url)

**Comment by jesperlandberg** [comment]
@unwrittenmike thanks a lot! However, the icons doesn't seem to show up. Tested on my project and also cloning ur repo and running dev mode.

![icons](https://user-images.githubusercontent.com/3479734/35994616-42693ea4-0d11-11e8-9c87-091b48115507.jpg)

**Comment by krivaten** [comment]
@jesperlandberg any chance you could make a gist or something? Both the BitBucket links were busted :(

**Comment by ChucKN0risK** [comment]
@unwrittenmike @jesperlandberg @krivaten I managed to deal with SVG sprite with the following configuration. I hope it will help you 😉

https://gist.github.com/ChucKN0risK/2d0f8466e13d4b63f3982ed2b60bd111

**Comment by dword-design** [comment]
I actually wrote a Nuxt module that does it. Maybe it's still of interest:
https://www.npmjs.com/package/nuxt-svg-sprite-loader
