### ISSUE TITLE
Add option for symbol based output for use with <use>

### ISSUE THREAD

**Issue by MaxMilton** [kisenka/svg-sprite-loader#192]
**Do you want to request a feature, report a bug or ask a question?**
Feature

**What is the current behavior?**
Symbol markup in the sprite is wrapped in `<defs>`, includes a `<style>` block, and includes a `<use>` for each svg item. The reasoning for this is explained in https://github.com/kisenka/svg-sprite-loader/issues/122 .

**What is the expected behavior?**
If the developer will only be refering items in the sprite via `<use xlink:href="sprite.svg#item-name"/>` and not in CSS or `<img>` then allow svg-sprite-loader to generate a simpler output without the things mentioned above (defs, style, use).

**If this is a feature request, what is motivation or use case for changing the behavior?**
No need for the extra markup bloat when only using `<use xlink:href="sprite.svg#item-name"/>`; smaller file size.

**Please tell us about your environment:**

- Node.js version: 8.5
- webpack version: 3.6
- svg-sprite-loader version: 3.2.5 
- OS type & version: Linux, Fedora Linux x86_64

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
Example of current output:
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><style>
    .sprite-symbol-usage {display: none;}
    .sprite-symbol-usage:target {display: inline;}
  </style><symbol viewBox="0 0 24 24" fill="none" stroke="currentColor" id="anchor">
    <circle cx="12" cy="5" r="3" />
    <line x1="12" y1="22" x2="12" y2="8" />
    <path d="M5 12H2a10 10 0 0 0 20 0h-3" />
</symbol></defs><use id="anchor-usage" xlink:href="#anchor" class="sprite-symbol-usage" /></svg>
```
Example of proposed simplified output:
```
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <symbol id="anchor" viewBox="0 0 24 24" fill="none" stroke="currentColor">
    <circle cx="12" cy="5" r="3" />
    <line x1="12" y1="22" x2="12" y2="8" />
    <path d="M5 12H2a10 10 0 0 0 20 0h-3" />
  </symbol>
</svg>
```

**Comment by jpzwarte** [comment]
See #194, you really want to have the SVG icons inline, not in a separate resource (also see https://css-tricks.com/svg-symbol-good-choice-icons/)

**Comment by MaxMilton** [comment]
Inline is not a good idea if you have icons which repeat, no point defining the same code multiple times. The `<use>` technique is great since SVG resources only need to be defined once and you can style the same SVG item in different ways.

I'm not sure that this package is the right place to do file inlining as its purpose is to create an SVG **sprite**, although there may be some SVG parsing logic you could use to write a custom loader.

**Comment by jpzwarte** [comment]
I mean inlining the *sprite* in de HTML. You get all the benefits of ```<use>``` without cross browser issues and having to load the sprite using AJAX.

**Comment by xlotlu** [comment]
Except inlining the sprite means losing the benefits of caching. Besides, there's [this](https://github.com/jonathantneal/svg4everybody).

**Comment by MaxMilton** [comment]
Saw some work towards this in https://github.com/kisenka/svg-sprite-loader/commit/fcf3939 . Now when initializing the class you can speficy:
```javascript
new SpriteLoaderPlugin({ plainSprite: true }),
```
Everything is pretty sweet and works basically as I originally described in the OP. Only issue is the `-usage` is still appended to my svg path, e.g. `"sprite.svg#item-name-usage"` instead of `"sprite.svg#item-name"`.

**Comment by kisenka** [comment]
@MaxMilton it's inconsistent behaviour, but if it will produce `sprite.svg#item-name` instead of `sprite.svg#item-name-usage` it will have no sense if you're using external sprite. Right?

**Comment by kisenka** [comment]
Closing this one, there is a bug described by @MaxMilton, please follow #221

**Comment by MaxMilton** [comment]
Sorry, I didn't get back about this. It is important to me but I've been on holidays for the last few weeks.

I'll put together a reproducable case for this ASAP and post a link to it in the new issue.

**Comment by kisenka** [comment]
No needs for demo case, I know where is a bug, just need some time to fix it. Subscribe to #221.

**Comment by MaxMilton** [comment]
Amazing, thank you very much. P.S. love the project, I use it on almost every client project now :heart:

**Comment by kisenka** [comment]
I making this work for such words!
