### ISSUE TITLE
Merging <defs> outside of symbols ?

### ISSUE THREAD

**Issue by alx-gk** [kisenka/svg-sprite-loader#195]
Hi! Can anybody tell me, what's the right way to use one defs to a several symbols (linear-gradient for example) ? When I'm add symbols to sprite, each symbol has its own defs, can I move and merge defs outside of symbols for multiple use ? I understand, that I can use it multiple through css, if it is in one symbol only, but I think, this is not usable to some tasks.

**Comment by kisenka** [comment]
@alx-gk do you have any problems with multiple defs or just curious?

**Comment by alx-gk** [comment]
I think its not problem, but, for example, if I need two svg symbols with same linear-gradient, now I can create defs with gradient in each symbol ( but dont want to duplicate code ), or create defs in first symbol and use it for second symbol too ( symbols will be not independent ). I think the right way will be create one defs outside of symbols ( merge it from symbols with same gradient ) and use it for all necessary symbols ?

**Comment by kisenka** [comment]
Actually it's not a loader issue, it is related to sprite optimization and minification, svgo for example. However, such optimizations in automatic way is rather dangerous and I don't think they are necessary.

**Comment by kisenka** [comment]
@alx-gk svg-sprite-loader uses svg-baker for creating sprites under the hood, you can file an issue there.

**Comment by alx-gk** [comment]
Ok, thanks! Will read svgo documentation once more.
