### ISSUE TITLE
Why the loader append the file name in the svg ID when I try to extract a file?

### ISSUE THREAD

**Issue by brunohkbx** [kisenka/svg-sprite-loader#197]
This is my webpack configuration.

```
{
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: path.join(__dirname, '/node_modules/@salesforce-ux/design-system/assets/icons/utility-sprite/svg/symbols.svg'),
        options: {
          extract: true,
          spriteFilename: '/assets/icons/utility-sprite/svg/symbols.svg'
        },
}
```

I'm trying to include the /node_modules/@salesforce-ux/design-system/assets/icons/utility-sprite/svg/symbols.svg file.

This is a example of symbol extracted using the loader.
`<symbol viewBox="0 0 24 24" id="symbols_event">`

Why this string **symbols_** is appended in the original ID?
I tried to alter symbolId option, but it also doesn't work.

**Comment by kisenka** [comment]
This loader doesn't supports using sprite generated by other tools.

**Comment by thomasaull** [comment]
I'm having the same problem, without any other tools. I want an exported svg form Sketch to have a specific Id, but SVG-Sprite-Loader overwrites the ID with filename_id, which basically breaks my workflow. Any solution to this?

**Comment by kisenka** [comment]
@thomasaull why you need this? You refer to sprite symbols manually?

**Comment by thomasaull** [comment]
No, I wanted to overwrite fills or strokes based on an ID – but I was making a mistake, since it's in the shadow dom I can't really access it anyway :)

**Comment by kisenka** [comment]
Yep, but you can fill and stroke elements without these attributes.

**Comment by thomasaull** [comment]
I know, but I have to edit the svgs manually. When I export it again, I have to do the changes again, which is cumbersome and error-prone…

**Comment by kisenka** [comment]
But you can drop fill and stroke in Sketch source once (if we are talking about icons of course).

**Comment by thomasaull** [comment]
Yes we're talking about icons. Thing is, when I define this in sketch im bound to a specific color. What I want to do is basically this:
```
svg {
  stroke: $myBrandColor;
  fill: none;
}

svg #fill {
  fill: $myBrandColor;
}
```
For line icons

**Comment by kisenka** [comment]
This will not work decause of shadow DOM. But you can always inline SVGs directly.
