### ISSUE TITLE
Generate sprites at build-time and auto inject in html template

### ISSUE THREAD

**Issue by c0defre4k** [kisenka/svg-sprite-loader#198]
Has anyone tried to generate the sprites at build time?

My goal is to reduce the package size of my app. Since svg-sprite-loader renders the sprite in the browser on the client-side the client also needs to know how to build that sprite.

Now I came up with the idea of building the sprite during build and inject the SVG with HtmlWebpackPlugin or something into my index.html.

So my question is, if this is even possible? If yes, whats the best way to achieve this?

**Comment by kisenka** [comment]
@c0defre4k this feature already was requested in #194

**Comment by kisenka** [comment]
Closing as duplicate, try to implement this on the next week.
