### ISSUE TITLE
spriteFilename option not working properly

### ISSUE THREAD

**Issue by cedrictahina** [kisenka/svg-sprite-loader#199]
**Do you want to request a feature, report a bug or ask a question?**
I would like to report a bug
**What is the current behavior?**
spriteFilename option is not taken into consideration
**What is the expected behavior?**
The generated file should take the spriteFilename value in webpack configuration, output file always has sprite.svg as name

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
```js
module: {
    rules: [
      {
        test: /\.svg$/,
        include: path.resolve(__dirname, `${PATH.src}/icons`),
        use: [
          { 
            loader: 'svg-sprite-loader',
            options: {
              extract: true,
              spriteFilename: 'assets-sprite.svg'
            }
          },
          {
            loader: 'svgo-loader'
          }
        ]
      }
    ]
  },
  plugins: [
    new SpriteLoaderPlugin()
  ]
```
**Please tell us about your environment:**

- Node.js version: 6.11.3
- webpack version: 3.6.0
- svg-sprite-loader version: 3.2.6
- OS type & version: Mac Os El Capitan

**Comment by kisenka** [comment]
@cedrictahina couldn't reproduce with your webpack & loader version. Could you please create a git repo where I can reproduce described error?

**Comment by cedrictahina** [comment]
After deep investigation, I noticed that the svg-sprite-loader was in conflict with image-webpack-loader when svg files are presents in the rule test.
