### ISSUE TITLE
Inkscape SVG not processed

### ISSUE THREAD

**Issue by stereoit** [kisenka/svg-sprite-loader#20]
Hello,

icons exported from Inkscape are processed, but not rendered because the `defs` are empty. Is this problem of sprite-loader or Inkscape?

[icon_from_inkscape.svg.zip](https://github.com/kisenka/svg-sprite-loader/files/85947/icon_from_inkscape.svg.zip)

**Comment by kisenka** [comment]
Duplicate of #11

**Comment by kisenka** [comment]
Fixed in [0.0.16](https://github.com/kisenka/svg-sprite-loader/releases/tag/v0.0.16)
