### ISSUE TITLE
this.async is not a function issue with webpack

### ISSUE THREAD

**Issue by girwin575** [kisenka/svg-sprite-loader#201]
Hi Kisenka,
After getting your updates from the callback issue I'm getting the below error.
<<< start of error >>>
loader option has been deprecated - replace with "use"
{localfilepath}/node_modules/svg-sprite-loader/lib/loader.js:18
  const done = this.async();
                    ^
TypeError: this.async is not a function
<<< end of error >>>
Could you please advise on a fix? Thanks.

**Comment by kisenka** [comment]
@girwin575 please provide webpack version

**Comment by girwin575** [comment]
@kisenka  3.7.1

**Comment by kisenka** [comment]
@girwin575 couldn't reproduce, could you please create a git repo with reproducible error?

**Comment by mascardoso** [comment]
Having the same issue.
Using `"webpack": "^3.6.0"`

**Comment by mascardoso** [comment]
any ideas how to solve this?

**Comment by girwin575** [comment]
@mascardoso yeah I'm having the same issue. What version of node are you using?

**Comment by mascardoso** [comment]
@girwin575 node `v8.7.0`

**Comment by mascardoso** [comment]
Also probably good to know but I have in place an SSR app. I get this error when I try to add `sprite-svg-loader` to my `.babelrc`

**Comment by kisenka** [comment]
@girwin575 it will be better if you edit this issue and fill the [template](https://github.com/kisenka/svg-sprite-loader/blob/master/.github/ISSUE_TEMPLATE.md) (and don't remove it next time). Also I can help you much faster if you create a git repo where I can reproduce an error.

**Comment by girwin575** [comment]
@kisenka I'll fill out that issue template now as a comment, with regards to a repo I'm working on one with the same issue as I can't publish what I currently have.

**Comment by kisenka** [comment]
@girwin575 ok, let's start from details about your environment, I need only this information from issue template

**Comment by girwin575** [comment]
- Node.js version: 7.10.1
- webpack version: 3.7.1
- svg-sprite-loader version: 3.3.1
- OS type & version: OS X El Capitan - 10.11.6

**Comment by mascardoso** [comment]
If it also helps @kisenka:

- Node.js version: 8.7.0
- webpack version: 3.6.0
- svg-sprite-loader version: 3.3.1
- OS type & version: OS Sierra - 10.12.6

**Comment by kisenka** [comment]
@mascardoso 
> I get this error when I try to add sprite-svg-loader to my .babelrc

What does it mean `try to add sprite-svg-loader to my .babelrc`? sprite loader configuration should be defined in webpack config

**Comment by kisenka** [comment]
@girwin575 still cannot reproduce with node 7.10.1 & webpack 3.7.1. I need demo repo with package.json, webpack config & minimal piece of your code. You don't need to share whole project :)

**Comment by mascardoso** [comment]
@kisenka the reason I add in `babelrc` it's because this is a SSR application. Does it make sense?

**Comment by girwin575** [comment]
Ok @kisenka I'll get one together. Thanks!

**Comment by kisenka** [comment]
@mascardoso please provide an .babelrc example with svg-sprite-loader config

**Comment by mascardoso** [comment]
```
{
  "presets": ["es2015", "es2016", "es2017", "react"],
  "plugins": [
    "svg-sprite-loader",
    ["css-modules-transform", {
          "generateScopedName": "[local]___[hash:base64:5]",
          "extensions": [".scss"],
          "rootDir": "./front"
    }],
    "dynamic-import-node",
    "syntax-dynamic-import",
    "transform-async-to-bluebird",
    ["transform-runtime", {
      "polyfill": true,
      "regenerator": true
    }],
    "transform-object-rest-spread",
    "ramda"
  ]
}
```

**Comment by kisenka** [comment]
@mascardoso svg-sprite-loader is not a babel plugin, it's a webpack loader. Please follow the [configuration](https://github.com/kisenka/svg-sprite-loader#configuration) readme section to setup it properly.

**Comment by mascardoso** [comment]
@kisenka this is probably a different topic for me then... but if I use only webpack config and SSR I get the following error when importing an svg: `"ReferenceError: React is not defined",`. There's also a ticket [here](https://github.com/kisenka/svg-sprite-loader/issues/175)

**Comment by girwin575** [comment]
Hi @kisenka here is the repo https://github.com/girwin575/testrepo

Node.js version: 7.10.1
webpack version: 3.7.1
svg-sprite-loader version: 3.3.1
OS type & version: OS X El Capitan - 10.11.6

I hope this helps?

**Comment by kisenka** [comment]
@girwin575 you're trying to import loader instead of plugin [here](https://github.com/girwin575/testrepo/blob/master/webpack.config.js#L3):

```js
const SpriteLoaderPlugin = require('svg-sprite-loader');
```

should be
```js
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');
```

**Comment by girwin575** [comment]
Thanks @kisenka whilst you have the repo may I ask the fact I have

`    module: {
        rules: [
            {
                test: /\.svg$/,
                loader: 'svg-sprite-loader',
                include: path.resolve(svgDir), 
                options: {
                    extract: true,
                    spriteFilename: 'flags-sprite.svg'
                }
            }
        ]
    },`

Does that mean I should have a local copy of my flags-sprite.svg in my repo now? As I can't see it.

**Comment by kisenka** [comment]
@girwin575 you can't see it because you have no svg imports in your code. Add `import shareId from './assets/share.svg';` in app.js. 

Also you have an error in [webpack.config.js#2](https://github.com/girwin575/testrepo/blob/021b6e47ceaea8532327ebd309c486c5f7c88ee1/webpack.config.js#L2), leading slash should be removed in /src/assets:

```js
+ const svgDir = path.resolve(__dirname, 'src/assets'); 
```

**Comment by girwin575** [comment]
Fantastic, thanks for the help @kisenka
