### ISSUE TITLE
Bug: Hash is sporadically invalidated

### ISSUE THREAD

**Issue by wanecek** [kisenka/svg-sprite-loader#204]
## Current behaviour

When building an external sprite with webpack, the hash of the sprite-chunk is sometimes invalidated (changes) without the source files (the svgs) having been modified. 

## Expected Behaviour

When building an external sprite with webpack, the hash of the sprite-chunk should *never* be invalidated (change) without the source files (the svgs) having been modified.

## Demo

A simplified demo can be found at [`wanecek/svg-sprite-loader-hash-invalidation`](https://github.com/wanecek/svg-sprite-loader-hash-invalidation)

## Environment

- Node.js version: 8.5.0
- webpack version: 3.8.1
- svg-sprite-loader version: 3.4.0
- OS type & version: macOS Sierra 10.12.6

## Other information

I've found that importing less than 6 symbols seriously diminishes the rate at which chunks are invalidated, but does however not completely dispell the issue. To try this, comment out one (or more) of the imports in `src/main.js`.

---

This bug baffles me. If you need help in debugging, please do not hesitate to ask; however, I'm not sure where I'd begin...

**Comment by kisenka** [comment]
@wanecek thanks a lot for reporting! Fix shipped with `v3.4.1`

**Comment by wanecek** [comment]
Neat! Thank you for the quick fix @kisenka!
