### ISSUE TITLE
extract-mode example fails to build

### ISSUE THREAD

**Issue by sentience** [kisenka/svg-sprite-loader#207]
**Do you want to request a feature, report a bug or ask a question?**

Report a bug.

**What is the current behavior?**

Building the examples failed with an error, Cannot find module 'extract-text-webpack-plugin', in the extract-mode example.

**What is the expected behavior?**

Building the examples with `npm run build:examples` should run successfully.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**

```
$ node node_modules/webpack/bin/webpack.js --config examples/extract-mode/webpack.config.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kyank/code/svg-sprite-loader/examples/extract-mode/webpack.config.js:4:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Please tell us about your environment:**

- Node.js version: 7.9.0
- webpack version: 3.8.1
- svg-sprite-loader version: 3.4.1 (89c0bdd8218ae0a6963eab1c146bf4903afb1ca7)
- OS type & version: macOS 10.13 (High Sierra)

**Suggestions to fix:**

Add extract-text-webpack-plugin as a devDependency?

**Comment by kisenka** [comment]
@sentience try to run

```
yarn run bootstrap
yarn run env webpack-3
```

**Comment by sentience** [comment]
Aha! Did I miss the docs for this, or do they still need to be written? I'd be happy to draft an addition to examples/README.md and submit a PR if that would help.

**Comment by kisenka** [comment]
Actually it's in Setup section of [contributing guidelines](https://github.com/kisenka/svg-sprite-loader/blob/master/CONTRIBUTING.md#setup), but maybe it should be referenced from readme :)

**Comment by kisenka** [comment]
I've added postinstall script which runs `yarn run env webpack-3` each time when you install deps. Hope it helps.

**Comment by sentience** [comment]
I'm now seeing this in a project that depends on svg-sprite-loader master:

```
❯ yarn
yarn install v1.2.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/3] ⠂ fsevents
[2/3] ⠂ node-sass
[3/3] ⠂ svg-sprite-loader: info Visit https://yarnpkg.com/en/docs/cli/run for docum
[-/3] ⠂ waiting...
error /Users/kyank/code/cultureamp-style-guide/node_modules/svg-sprite-loader: Command failed.
Exit code: 1
Command: yarn env webpack-3
Arguments:
Directory: /Users/kyank/code/cultureamp-style-guide/node_modules/svg-sprite-loader
Output:
yarn run v1.2.1
$ node scripts/select-env webpack-3
module.js:529
    throw err;
    ^

Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kyank/code/cultureamp-style-guide/node_modules/svg-sprite-loader/scripts/select-env.js:3:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

**Comment by kisenka** [comment]
How you include sprite-loader in this project? You should use `npm link` or `yarn link`

**Comment by sentience** [comment]
I simply included it as a GitHub dependency in package.json:

```
  "svg-sprite-loader": "kisenka/svg-sprite-loader#master",
```

**Comment by kisenka** [comment]
shelljs specified in devDependencies

**Comment by sentience** [comment]
That explains it, then, right? The new postinstall script is running when the package is installed as a dependency of my project—when the devDependencies are not available.

**Comment by kisenka** [comment]
`npm install --ignore-scripts`?

**Comment by sentience** [comment]
I don't think it's reasonable for all projects that use svg-sprite-loader as a dependency to have to specify `--ignore-scripts` when they `npm install`.

Because npm postinstall scripts are run both when you `npm install` the package itself, as well as when you `npm install` a project that _depends_ on the package, you simply can't rely on `devDependencies` being present.

[From the official docs of NPM scripts, under “best practices"](https://docs.npmjs.com/misc/scripts#best-practices):

> Don't use install. Use a .gyp file for compilation, and prepublish for anything else. You should almost never have to explicitly set a preinstall or install script. If you are doing this, please consider if there is another option. The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture.

**Comment by kisenka** [comment]
Hmm, could you suggest better solution? I want to always run env script after dependencies changed.

**Comment by sentience** [comment]
How about if your postinstall script checked for the presence of a devDependency (such as shelljs), and exited silently if it was not present? That way, when the package is installed with devDependencies, the script will run, and when the package is not installed with devDependencies (i.e. as a dependency of a project), then the script would exit harmlessly.

**Comment by kisenka** [comment]
Too complicated :) I'm better remove postinstall script!

**Comment by kisenka** [comment]
Too complicated :) I'm better remove postinstall script!
