### ISSUE TITLE
Extract and inject SVG spritesheet in a single build

### ISSUE THREAD

**Issue by sentience** [kisenka/svg-sprite-loader#208]
**Do you want to request a feature, report a bug or ask a question?**

Propose a feature we might contribute.

**If this is a feature request, what is motivation or use case for changing the behavior?**

We need to support a couple of constraints on our SVGs:

* Our pages are sometimes rendered as PDF using [wkhtmltopdf](https://wkhtmltopdf.org), which crashes when SVG symbols are injected into the HTML document by JavaScript. To satisfy this constraint, we might normally choose to use Extract Mode, or use server-side rendering to inject the spritesheet into the page.
* Our pages are served from a different domain than our Webpack assets, which come from a CDN. Current browsers do not permit cross-origin requests to SVG assets (e.g. `<use xlink:href="http://some-other-server.com/sprite.svg#icon-id">`). To satisfy this constraint, we might normally choose **not** to use Extract Mode.

In order to support both of these constraints at once, we would like to use Extract Mode to generate an external sprite.svg file, which we would inject into the page server-side when rendering the page as PDF. At the same time, so as not to bloat the HTML pages that we serve to web browsers, we would like to maintain the non-Extract-Mode behaviour of injecting the SVG spritesheet into the page with JavaScript at page load. We hope not to have to do two webpack builds to support both of these requirements.

**Proposal for implementation**

We believe the main changes to make this possible would need to happen in svg-sprite-loader/lib/runtime-generator.js. Currently, this file checks the `extract` config flag to decide which implementation to use. We simply want some other configuration flag that will cause the logic in this file to use the non-extract implementation even though the rest of the build will still use `svg-sprite-loader/plugin` to extract the spritesheet to a file.

Perhaps we could add a `runtimeOptions.ignoreExtract` flag, since we are effectively telling it to ignore the extracted spritesheet at runtime?

```js
function runtimeGenerator(params) {
  const { symbol, config, context } = params;
  const { extract, esModule, spriteModule, symbolModule, runtimeCompat, runtimeOptions } = config;
  let runtime;

  if (extract && !runtimeOptions.ignoreExtract) {
    // … reference the extracted spritesheet
  } else {
    // … inject and reference the sprite
  }

  return runtime;
}
```

If we're reading the code right, this will still generate the extracted SVG spritesheet file, but will ignore it for runtime purposes. We will then have the freedom to inject that spritesheet file into the page server-side when we are rendering for PDF. The default browser-sprite implementation (svg-sprite-loader/runtime/browser-sprite.js) will then detect the existing spritesheet in the DOM and do nothing.

We would happily contribute this feature if it were considered desirable.

**Please tell us about your environment:**

- Node.js version: 8.7.0
- webpack version: 3.6.0
- svg-sprite-loader version: 3.3.1
- OS type & version: macOS and Ubuntu Linux

**Comment by sentience** [comment]
I just tested the proposed change above (adding a `runtimeOptions.ignoreExtract` flag) in our project, and it meets our needs perfectly.

**Comment by kisenka** [comment]
I didn't get, you describe two different cases:
1. Extract mode with external sprite.
2. Usual mode with JS runtime.

You want to mix them in one webpack build? I mean you want to import the same SVG image and it should be processed in both ways?

**Comment by sentience** [comment]
That's right, yes. We would like to use the standard mode where the spritesheet is injected into the DOM on `documentready`, while also generating the extracted version of the spritesheet as an SVG file that we can inject into the page server-side for our PDF rendering, where it needs to be present in the DOM *before* `documentready`.

**Comment by kisenka** [comment]
If I know it's not possible in webpack to process one module differently. But if you know how - PR is always welcome!

**Comment by sentience** [comment]
I completed an implementation of this feature, but then our requirements changed and so we no longer require this, so I will close this issue. Just in case my work is of use or interest to future generations, I've opened a pull request with the changes (#214); however, I will also close that without merging for now.
