### ISSUE TITLE
Module build failed: SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by binarykitchen** [kisenka/svg-sprite-loader#209]
When I require an SVG image like `const listSvg = require('list.svg')` and use it in a Coffee markup like

```
  "<svg id=\"#{listSvg}\">" +
    "<use xlink:href=\"#{listSvg}\"></use>" +
  "</svg>"
```

the above error message comes up. Using latest versions of everything here. Really weird why it complains about `{` ... why?

**Comment by chestozo** [comment]
Apparently it is the same problem as here:
https://github.com/kisenka/svg-sprite-loader/issues/140#issuecomment-312474829

I am getting the same error on node `v4.5.0`, but no error on `v9.1.0`.
Also you can use older versions of this plugin (which is not a good idea but ... it is easier sometimes compared to upgrading your node version).

**Comment by kisenka** [comment]
@chestozo you're right, only node>= 6 is supported. Thanks for clarification!
