### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by chungchiehlun** [kisenka/svg-sprite-loader#21]
When using svg-sprite-loader , I always get `ReferenceError: React is not defined`.
I followed the instruction and listed my code below. 
Did anyone confront the same problem ?
```js
// webpack.config.js
{
    test: /\.svg$/,
    loader: 'svg-sprite?' + JSON.stringify({
      name: '[name]_[hash]',
      prefixize: true
    }),
    exclude: /node_modules/
}
```

```js
// my_component.js
import iconSearch from './icon_search.min.svg';
```

**Comment by kisenka** [comment]
@chungchiehlun try to add this to webpack.config.js
```js
externals: {
    'react': 'React'
}
```
This tells Webpack to not resolve require('react') by loading an npm module, but instead to expect a to not resolve require('react') by loading an npm module, but instead to expect a global variable called React. ([original anwser](http://stackoverflow.com/a/34563571/4624403))

**Comment by chungchiehlun** [comment]
It works !  Thank you very much.
