### ISSUE TITLE
Allow to generate sprite filename via function

### ISSUE THREAD

**Issue by fenderil** [kisenka/svg-sprite-loader#213]
**Do you want to request a feature, report a bug or ask a question?**
feature, plz (or question?)

**What is the current behavior?**
Commonly we have this condition: `svgSpriteLoaderRules.length === sprites.length`

**What is the expected behavior?**
One rule for any count of sprites

**If this is a feature request, what is motivation or use case for changing the behavior?**
There is one webpack-config and a few count of projects.
It's redundantly to update config by adding rules on any request.
So i want to unify loader rule.

**Please tell us about your environment:**

- Node.js version: 8.5.0
- webpack version: 3.2.0
- svg-sprite-loader version: 3.4.1
- OS type & version: macOS 10.12.3

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
For example, it is possible to take paths to different icons and merge them into a single sprite by directory name.
```
/sprite
  /flags // -> goes to sprite flags.svg
    /usa.svg
    /rus.svg
    /jpn.svg
  /cars // -> goes to sprite cars.svg
    /bmw.svg
    /ford.svg
```
I had done this by regexp matching with test/include rule parameter.

PS: thx, you had made perfect loader, Kisenka.

**Comment by kisenka** [comment]
I don't get what you want. You can ping me in Telegram - `@superkisenka`
