### ISSUE TITLE
Wrong behaviour with ExtractTextPlugin

### ISSUE THREAD

**Issue by ophite** [kisenka/svg-sprite-loader#216]
When use ExtractTextPlugin and set there custom folder for assets (for example js and css want to place in chunks folder, image, fonts, svg sprite in assets folder and index.html in root) then ExtractTextPlugin add prefix chunks and svg-sprite-loader add prefix path assets for sprite and as result we have chunks/assets/sprite.svg but expected assets/sprite.svg by loader and so sprite does not work

**Comment by kisenka** [comment]
Please see https://github.com/kisenka/svg-sprite-loader/issues/215#issuecomment-346050967:

> It can be fixed by adding output.publicPath: '/'.

**Comment by ophite** [comment]
It works only in webpack dev server case, but when open static (dev/prod) files - incorrect path to assets

**Comment by kisenka** [comment]
I don't get. If assets path on production differs from dev-server specify them like this `publicPath: isProduction ? '/productionPath' : '/'`.

**Comment by ophite** [comment]
But even in dev mode it does not help. Use svg icon through css.

P.s. in prod and dev the same dir structure (directory dist and all inside).
