### ISSUE TITLE
Hash in filename is changed if htmlWebpackPlugin is used at plugin:91 

### ISSUE THREAD

**Issue by jamescrstnwork** [kisenka/svg-sprite-loader#217]
**Do you want to request a feature, report a bug or ask a question?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
- htmlWebpackplugin with svg-sprite-loader extract mode
-  module-rule: 
`{
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          extract: true,
          spriteFilename: 'app.icons.[hash:6].svg'
        }
      }
`
**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**

**Please tell us about your environment:**

- Node.js version: 8
- webpack version: 3
- svg-sprite-loader version: 3.4.1
- OS type & version: arch-manjaro

**Comment by jamescrstnwork** [comment]
- SVG file is generated with hashcode, but in html-webpack-plugin phase 'html-webpack-plugin-before-html-processing', it recreates hash with different value with different filename, then in line 91 of plugin get value of undefined filename

`
                     app.icons.a6db05.svg    70.2 kB          [emitted]         app.icons.a6db05
                               index.html    1.41 kB          [emitted]         

ERROR in   TypeError: Cannot read property 'source' of undefined
  
  - plugin.js:91 Object.keys.reduce
    [m-erp]/[svg-sprite-loader]/lib/plugin.js:91:44
  
  - Array.reduce
  
  - plugin.js:90 Compilation.htmlPluginHook
    [m-erp]/[svg-sprite-loader]/lib/plugin.js:90:52
  
  - Tapable.js:272 Compilation.applyPluginsAsyncWaterfall
    [m-erp]/[tapable]/lib/Tapable.js:272:13
  
  - util.js:16 Compilation.tryCatcher
    [m-erp]/[bluebird]/js/release/util.js:16:23
  
  
  - index.js:645 
    [m-erp]/[html-webpack-plugin]/index.js:645:12
  
  - index.js:122 
    [m-erp]/[html-webpack-plugin]/index.js:122:16
  
  - util.js:16 tryCatcher
    [m-erp]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [m-erp]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [m-erp]/[bluebird]/js/release/promise.js:569:18
  
  - promise.js:614 Promise._settlePromise0
    [m-erp]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [m-erp]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [m-erp]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [m-erp]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [m-erp]/[bluebird]/js/release/async.js:17:14
`

**Comment by kisenka** [comment]
@jamescrstnwork could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by jamescrstnwork** [comment]
@kisenka repository created at [https://github.com/jamescrstnwork/svg-hash-issue](svg-hash-bug-repo). 

- run `npm run build`.
- to test it, make changes at `webpack.config.prod.js` without `app.icons.[hash:6].svg` and with.

**Comment by kisenka** [comment]
@jamescrstnwork thanks for the repo, I'm working on it

**Comment by kisenka** [comment]
@jamescrstnwork fixed in `svg-sprite-loader@3.6.2`, please update.

**Comment by jamescrstnwork** [comment]
@kisenka thanks, tested with prod and dev mode. Fully worked.

**Comment by kisenka** [comment]
Thank you for reporting, your repo helps me a lot to investigate this bug.
