### ISSUE TITLE
Load svg's in SSR via webpack

### ISSUE THREAD

**Issue by omRm** [kisenka/svg-sprite-loader#220]
**Do you want to request a feature, report a bug or ask a question?**
Question

**What is the current behavior?**
Loading all SVGs in SSR means i have to have direct access to the .html file,
which i dont as we use handlebars to insert our app.

**What is the expected behavior?**
Can i extract all icons and insert them into the html via webpack?

**Comment by kisenka** [comment]
I need a demo of your project.

**Comment by kisenka** [comment]
@omRm ping

**Comment by kisenka** [comment]
@omRm ping

**Comment by omRm** [comment]
sorry for the delayed response. i had a look at the SSR example and understand it now.
can be closed
