### ISSUE TITLE
plainSprite extract mode emits incorrect id/url of symbols to the webpack chunk

### ISSUE THREAD

**Issue by 3lvcz** [kisenka/svg-sprite-loader#221]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
When using extract mode with `plainSprite: true` option, symbol id in resulting sprite is equals to original file name, but values of `id` and `url` properties in emitted webpack chunk is composed like this: `{filename}-usage`.

**What is the expected behavior?**
Id and url in emitted javascript-code should not be postfixed with "-usage", if extract mode with `plainSprite: true` is used.

**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
repository: https://github.com/3lvcz/svg-sprite-loader-issue
wrong id: https://github.com/3lvcz/svg-sprite-loader-issue/blob/master/dist/build.js#L84

**Please tell us about your environment:**

- Node.js version: 8.9.1
- webpack version: 3.9.1
- svg-sprite-loader version: 3.4.1
- OS type & version: OSX Sierra 10.12.6

**Comment by kisenka** [comment]
@3lvcz sorry for delay, fixed in `svg-sprite-loader@3.5.4`

**Comment by vorobey** [comment]
I can reproduce it again

**Comment by vorobey** [comment]
@kisenka was any changes for this in new releases?

**Comment by salomoneb** [comment]
Bump on this as well. Experiencing it with version `4.1.3`.
