### ISSUE TITLE
Don't work in Firefox

### ISSUE THREAD

**Issue by ophite** [kisenka/svg-sprite-loader#222]
All work in chrome, but do not work in firefox and safari. 
`
      {
          test: /\.(svg)$/i,
          loader: 'svg-sprite-loader',
          options: {
            extract: true,
            spriteFilename: 'theme-sprite.svg',
          },
        }
`
Icon use via css https://monosnap.com/file/BVf4cJjnjD2nQDMFINCl8c3IaZYwBS
If open sprite fragment in firefox (copy link address) in separate tab all works (see svg).

Chrome print screen: https://monosnap.com/file/dVSjUtPXg82HSaFE6ZwxHrQri12iX7
Firefox print screen: https://monosnap.com/file/Rt9fhl2hYWJmqkQ1gselrBIHcQLVMx
Firefox svg: https://monosnap.com/file/dL0M6syvAf0pBTgkBBlNQMbvAoHzY6

- Node.js version: 8.6.0
- webpack version:  2.7.0
- svg-sprite-loader version: 3.4.1 
- OS type & version: macos 10.13.1

**Comment by kisenka** [comment]
Please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by kisenka** [comment]
@ophite ping, I need a working demo to fix error
