### ISSUE TITLE
Add ability to specify sprite attributes in extract mode

### ISSUE THREAD

**Issue by jpzwarte** [kisenka/svg-sprite-loader#230]
**Do you want to request a feature, report a bug or ask a question?**
Feature request

**What is the current behavior?**
It outputs the <svg> element with icon definitions without inline styles. This causes the element to be visible on the page until the CSS has loaded (which hides the element).

**What is the expected behavior?**
Add inline style to <svg> element so it is always invisible.

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
See plainSprite example output.

**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Works by default, no CSS necessary to hide the svg icon definition element.

I tried reading the svg-sprite-loader sources to see if i could add this behavior myself (and submit a PR), but i'm having trouble understanding the flow of the code :/

**Comment by jpzwarte** [comment]
Perhaps you can point me in the right direction?

**Comment by kisenka** [comment]
@jpzwarte how you use extracted sprite? Download it via AJAX?

**Comment by jpzwarte** [comment]
Sorry, i guess i wasn't clear. I'm using html-webpack-plugin with the ```extract: true``` and ```plainSprite: true```

**Comment by kisenka** [comment]
Shipped in `svg-sprite-loader@3.6.0`, it produces `syle="position: absolute; width: 0; height: 0` in plain sprite mode (see https://github.com/kisenka/svg-sprite-loader/issues/63#issuecomment-254225478, #70)

**Comment by jpzwarte** [comment]
Thanks! Guess i'll have to wait for it to appear on npm :)

**Comment by kisenka** [comment]
It's already there!

**Comment by jpzwarte** [comment]
Not yet with yarn :( Dunno why; perhaps its mirrored?

**Comment by jpzwarte** [comment]
Still not updated, weird: https://yarnpkg.com/en/package/svg-sprite-loader

**Comment by kisenka** [comment]
https://www.npmjs.com/package/svg-sprite-loader

**Comment by jpzwarte** [comment]
Yeah, yarn just listed the latest version. Just wanted to say how much i appreciate your work on this loader!

**Comment by kisenka** [comment]
Thank you for kind words, I love my users! :)
