### ISSUE TITLE
Random SVGs are undefined upon first compilation

### ISSUE THREAD

**Issue by binarykitchen** [kisenka/svg-sprite-loader#235]
This is a funny bug. Upon first webpack compilation a code line like this among many similar ones

`import broomSvg from 'broom.svg'` 

gives me undefined, nothing.

But when I make a change and webpack recompiles, then the above works and that missing SVG can be seen. Using the latest version v3.6.2 here with all the latest webpack packages.

DOM is loaded and the SVG symbols exist in the HTML which is fine. Still, do not understand why some random SVG import statements do not work upon first compilation.

With some debugging, I can see that deep inside webpack, where it holds all installed modules in the `installedModules` variables, this broom SVG is missing and not included. But few other random SVGs are.

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by binarykitchen** [comment]
okay, it took me hours to reduce our monster app to a minimalistic repo:
https://github.com/binarykitchen/random-svg-issues

it has some weird code there and could look better but that's not important. how to reproduce:
1. git clone it
2. install deps with yarn
3. run `yarn watch` and open http://localhost:3000 in the browser
4. keep an eye for errors in the dev console

if you don't see any errors, hit ctrl-c and try again until they show up (as i said, it's random)

**Comment by kisenka** [comment]
Have no idea how this expression works `import restoreSvg from 'restore.svg'`, where restore.svg is located? If I use `import restoreSvg from '../vectors/restore.svg'` all works fine. Just use relative path in imports and God will bless you!

**Comment by binarykitchen** [comment]
@kisenka huh, i already have added the path `src/vectors` to the webpack modules
https://github.com/binarykitchen/random-svg-issues/blob/master/env/dev/webpack/config.js#L57

it should work

**Comment by kisenka** [comment]
Honestly I have no idea how to investigate this and I think it's webpack's HMR issue

**Comment by binarykitchen** [comment]
This issue is still bugging me and studying webpack's HMR does't make me believe it's their problem. What makes you think so @kisenka ?
