### ISSUE TITLE
Optional inline styles on root SVG element 

### ISSUE THREAD

**Issue by leighkendell** [kisenka/svg-sprite-loader#240]
Currently when using the runtime configuration a few inline styles are added to the root SVG element to hide it. Is it possible to turn this behaviour off so I can hide the element through CSS instead? I'm implementing a strict CSP where inline styles are forbidden so they're being stripped out by some browsers.

**Comment by kisenka** [comment]
https://github.com/kisenka/svg-sprite-loader#sprite-attributes
