### ISSUE TITLE
Not compatible with Wepack 4

### ISSUE THREAD

**Issue by denisw** [kisenka/svg-sprite-loader#248]
This plugin doesn't seem to work with Webpack 4.0.0-beta.2 at the moment. I get the following error:

```
Module build failed: TypeError: Cannot read property 'target' of undefined
    at configurator (/Users/denis/Dropbox/Workspace/yumory/web/node_modules/svg-sprite-loader/lib/configurator.js:18:34)
    at Object.loader (/Users/denis/Dropbox/Workspace/yumory/web/node_modules/svg-sprite-loader/lib/loader.js:37:18)
 @ ./src/common/NavBar.js 27:16-50
 @ ./src/recipes/RecipeDetailsPage.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src
```

This might be caused by one of the breaking changes for plugin authors described here:

https://github.com/webpack/webpack/releases/tag/v4.0.0-beta.0

**Comment by Hypnosphi** [comment]
@kisenka See official migration guide for loader developers https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202

**Comment by Chris2011** [comment]
Have the same problem, just voted for it. Only want to know, is there a workaround for this? Except from downgrade Webpack :D

**Comment by rynclark** [comment]
Started work in #247. @phun-ky has continued this on in #249.

Hopefully will land soon.
