### ISSUE TITLE
Not working in Chrome 49

### ISSUE THREAD

**Issue by RoberMac** [kisenka/svg-sprite-loader#25]
![download](https://cloud.githubusercontent.com/assets/4065233/13655780/1098f51e-e69d-11e5-975a-447c46cef10c.png)
![screen shot 2016-03-10 at 8 36 53 am](https://cloud.githubusercontent.com/assets/4065233/13655781/118ee2f8-e69d-11e5-8455-7a7794061496.png)

**Comment by princed** [comment]
Please update to `0.0.17`.
Duplicates #24.

**Comment by RoberMac** [comment]
@princed still not working. :(

**Comment by princed** [comment]
There could be several solutions:
* Remove `<base>` tag
* Trigger custom `spriteLoaderLocationUpdated` event on window with `newUrl` param like [we do for angular](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/web/angular-base-workaround.js#L6) when React finished rendering.
* Resolve relative url (e.g. `#twitter`) that loader returns to absolute url (e.g. `https://one---line.com/settings#twitter`) using window.location.

**Comment by RoberMac** [comment]
the `<base>` tag is a legacy when I move from AngularJS to React.

"Remove `<base>` tag" can solve this problem, thank you!

**Comment by princed** [comment]
Great!

**Comment by beljand** [comment]
For all Angular2 users, you can remove `<base>` and use:
`
import { APP_BASE_HREF } from '@angular/common';
`
and then in bootstrap function
`
bootstrap('App',[
  provide(APP_BASE_HREF, {useValue : '/' })
])
`
