### ISSUE TITLE
Loader doesn´t set the spriteFileName in version 3.7.0

### ISSUE THREAD

**Issue by IvanRodriCalleja** [kisenka/svg-sprite-loader#258]
**Do you want to request a feature, report a bug or ask a question?**
Bug
**What is the current behavior?**
When i configure the loader with property 'spriteFilename', allways is the default file name .

My loader configuration is:
```javascript
module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        options: {
          extract: true,
          spriteFilename: 'my-custom-name.svg'
        }
      }
    ]
  },
plugins: [ new SpriteLoaderPlugin() ]
```

**What is the expected behavior?**

I expect the output file hase the name 'my-custom-name.svg' but always is 'sprite.svg'

**Please tell us about your environment:**

- Node.js version: ?
    v8.9.4
- webpack version: ?
   4.0.0
- svg-sprite-loader version: ? 
   3.7.0
- OS type & version: ?
   Windows 10

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by kisenka** [comment]
This is strange, because corresponding tests [are passed successfully](https://travis-ci.org/kisenka/svg-sprite-loader/builds/351705029#L887). I need a demo repo where this option doesn't work for you.

**Comment by IvanRodriCalleja** [comment]
I have reproduced this issue in repo: https://github.com/IvanRodriCalleja/svg-sprite-loader-issues-258

I was looking repo for posible solutions but i dont know exactly how this plugin works. X(

**Comment by kisenka** [comment]
@IvanRodriCalleja `spriteFileName` should be `spriteFilename` [here](https://github.com/IvanRodriCalleja/svg-sprite-loader-issues-258/blob/master/webpack.config.js#L31). I should add config validation to prevent such errors.

**Comment by kisenka** [comment]
#259

**Comment by IvanRodriCalleja** [comment]
@kisenka thanks for the aclaration, i didn´t see this error. 😬
