### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by eschao** [kisenka/svg-sprite-loader#262]
**Do you want to request a feature, report a bug or ask a question?**
I think it is a bug or something else

**What is the current behavior?**
Just simply configured it in webpack and loaded given sprite file but failed when start vuejs project by npm

**What is the expected behavior?**
load sprite successfully and can be used in vue file

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
This is my simple configuration in webpack:
```js
      {
        test: /\.svg$/,
	loader: 'svg-sprite-loader',
	include: resolve('src/assets/fa-brands.svg')
      },
```
I'm using font awesome svg file

**The best way is to create repo with minimal setup to demonstrate a problem (package.json, webpack config and your code).**
**It you don't want to create a repository - create a [gist](http://gist.github.com) with multiple files**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: 6.9.2
- webpack version: 2.9.0
- svg-sprite-loader version: latest
- OS type & version: mac

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

**Comment by eschao** [comment]
Here is my sprite svg file: 
[fa-brands.svg.zip](https://github.com/kisenka/svg-sprite-loader/files/1850116/fa-brands.svg.zip)

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by chiefraccoon** [comment]
Have the same issue, but need some time to distinguish minimal setup to reproduce the issue from my pretty huge project.

**Comment by chiefraccoon** [comment]
I don't know yet, how it is related but the issue is reproducing only if i run task within Webstorm npm scripts runner module. In case if i manually launch exactly the same command (npm task) directly from console, it builds successfully!

**Comment by kisenka** [comment]
@eschao you're using precompiled SVG sprite, it's not possible with this loader.
