### ISSUE TITLE
Extract Mode in Webpack 4

### ISSUE THREAD

**Issue by ottoborden** [kisenka/svg-sprite-loader#264]
I'd like to use `svg-sprite-loader` with Webpack 4 in extract mode. The gist below contains my `webpack.config.js` and how I'm trying to use the files. The issues I'm running into is that `extract-text-webpack-plugin` is not compatible with Webpack 4 and there are no intentions to fix this. Instead I've had to switch over to using `mini-css-extract-plugin`. Has anyone else tried this plugin and had any success?

[Gist](https://gist.github.com/ottoborden/b588aea6ed244c2ef40107d7acd995c8)

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
`svg-sprite-loader` seems to run and extract the SVG files as expected, but it fails on import. The code in the [Gist](https://gist.github.com/ottoborden/b588aea6ed244c2ef40107d7acd995c8) results in the following error:

```
[object:1 GET http://localhost:3000/[object 404 (Not Found)
```

`svg-sprite-loader` seems to be injecting `[object Object]` where it should be injecting the url to the extracted SVG. I get the same result when trying to import into a CSS file.

**Please tell us about your environment:**

- Node.js version: 9.9.0
- webpack version: 4.2.0
- svg-sprite-loader version: 3.7.3
- OS type & version: OSX 10.12.3

Any help would be greatly appreciated. Thank you.

**Comment by dormadekhin-denis** [comment]
@ottoborden, In the parameters, you need to add ` esModule: false`

**Comment by ottoborden** [comment]
@dormadekhin-denis Thanks! Don't know how I missed that, must have been too late at night.

**Comment by joserobleda** [comment]
> The issues I'm running into is that extract-text-webpack-plugin is not compatible with Webpack 4 and there are no intentions to fix this

@dormadekhin-denis in case you don't know, note that `extract-text-webpack-plugin` is already working for Webpack 4, just install the "next" version (I think they say it is unstable for now, but works great for me)
