### ISSUE TITLE
Inject existing svg sprite file

### ISSUE THREAD

**Issue by matan-modai** [kisenka/svg-sprite-loader#265]
**Do you want to request a feature, report a bug or ask a question?**
question

I have an existing svg sprite file (as opposed to many svg files) and I would like to inject it into my index.html. Meaning I want to skip the svg bundling part and only do the injecting. 
For some reason I don't find a good explanation to this online. 
Is it possible to do this with this loader? If not, how can I achieve this?

**Comment by kisenka** [comment]
This loader is for building sprite from single SVG images. It is not possible to use existing sprite with this loader
