### ISSUE TITLE
Loading multiple sprites from multiple libraries

### ISSUE THREAD

**Issue by silicakes** [kisenka/svg-sprite-loader#270]
Following https://github.com/kisenka/svg-sprite-loader/issues/136 , I have  the following use case:

* MyProject - contains the normal svg/sprite config which works great
* A 3rd party library also containing a SVG sprite.

the question is, how do I combine the two?

I've tried the solution previously suggested in the aformentioned discussion, however that one only works for svg files, rather than svg sprites.

My current code insight my local project looks something like this:

```
      {
        test: /\.svg$/,
        use: [
          {
            loader: "svg-sprite-loader",
            options: {
              extract: true,
              spriteFilename: `icon.svg`
            }
          },
          {
            loader: "svgo-loader",
            options: {
              plugins: [
                { removeTitle: true },
                { convertColors: { shorthex: false } },
                { convertPathData: false },
                {removeXMLProcInst: true},
                {removeXMLNS: true},
                {
                  removeAttrs: {
                    attrs: "stroke.*"
                  }
                }
              ]
            }
          }
        ],
        include: [`${rootDir}/src/assets/`, `${rootDir}/node_modules/3rdpartyibrary`]
      }
```

And the error I'm getting:

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

What am I missing?

webpack 4.3
svg-sprite-loader 3.7.3

**Comment by silicakes** [comment]
I have a temp workaround for the dev env, should you using webpacks devserver:

```
    before: (app) => {
        app.get('/3rdparty.svg', function(req, res) {
            res.setHeader('Content-Type', 'image/svg+xml');
            fs.readFile(path.resolve(`${rootDir}/node_modules/3rdpartylib/dist/3rdparty.svg`), (err, data) => {
                if (err) {
                    console.error(err.stack);
                }
                res.end(data);
    
            });
        });
      }
```

Adding the above to devServer's config should take care of it.
As for production - it's pretty much the same, just with your actual server.

**Comment by kisenka** [comment]
@silicakes if you have already built sprite from 3rd party lib - process it via file-loader, not svg-sprite-loader
