### ISSUE TITLE
Sprite svg not working with vuejs

### ISSUE THREAD

**Issue by nicomartin92** [kisenka/svg-sprite-loader#275]
I am trying to install svg-sprite-loader on my projet. But it seems it does'nt work , no svg sprite is generated. Maybe I configure the solution in the wrong way. 
Could you please help me.
This is a gist url of my file:
https://gist.github.com/nicomartin92/a828b7e3c70be80cfa03295c78d1c478

- Node.js version: v8.9.4
- webpack version: ^3.11.0"
- svg-sprite-loader version: ^3.7.3 
- OS type & version: Windows 10

Thank you in advance.

**Comment by kisenka** [comment]
You're process svg files twice: by [url-loader](https://gist.github.com/nicomartin92/a828b7e3c70be80cfa03295c78d1c478#file-webpack-base-conf-js-L54) and by [svg-sprite-loader](https://gist.github.com/nicomartin92/a828b7e3c70be80cfa03295c78d1c478#file-webpack-base-conf-js-L78). Also set esModule: false in svg-sprite-loader option

**Comment by nicomartin92** [comment]
Ok thank you very much for your quick feedback.
