### ISSUE TITLE
Allow custom spriteNodeId

### ISSUE THREAD

**Issue by jasongerbes** [kisenka/svg-sprite-loader#276]
**Do you want to request a feature, report a bug or ask a question?**
Request a feature.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I would like to provide a custom `spriteNodeId` instead of using the hard-coded `__SVG_SPRITE_NODE__`.

**Comment by kisenka** [comment]
You can use custom sprite implementation via [spriteModule](https://github.com/kisenka/svg-sprite-loader#spritemodule-autoconfigured) config option.

**Comment by jasongerbes** [comment]
Thanks :)
