### ISSUE TITLE
Wrap <symbol>s in a <def>

### ISSUE THREAD

**Issue by jasongerbes** [kisenka/svg-sprite-loader#277]
**Do you want to request a feature, report a bug or ask a question?**
Request a feature

**If this is a feature request, what is motivation or use case for changing the behavior?**
The `<symbol>`s should be wrapped in a `<def>`, for example:

```
<svg>
    <def>
        <symbol id="1">...</symbol>
        <symbol id="2">...</symbol>
        <symbol id="3">...</symbol>
    </def>
</svg>
```

**Comment by kisenka** [comment]
There is no `<def>` tag in SVG. If you mean `<defs>` generated sprite already contains it.

**Comment by bvellek** [comment]
Hey @kisenka , 

I am also running into this issue since upgrading form v`0.3.0` to v`3.8.0` - did you find any resolution to this?

here is my config for reference

```
{
                loader: 'svg-sprite-loader',
                options: {
                  runtimeCompat: true,
                  symbolId: `${svgNamespace}.[name].[hash]`
                }
              }
```
