### ISSUE TITLE
Getting sprite with optimized svgs

### ISSUE THREAD

**Issue by aLkRicha** [kisenka/svg-sprite-loader#278]
**Do you want to request a feature, report a bug or ask a question?**
ask

**What is the current behavior?**
seems like svgo loader doesn't work

**What is the expected behavior?**
expects to use svgo optimization on output sprite

[gist](https://gist.github.com/aLkRicha/97059771972791d88cc262bab3e85650)

**Please tell us about your environment:**

- Node.js version: v9.11.1
- webpack version: webpack@3.11.0
- svg-sprite-loader version: svg-sprite-loader@3.7.3
- OS type & version: Linux 420afcde5ebb 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**
as you can see in gist, i try to use round in svgo, but in result got not rounded numbers in sprite
also, i'm always getting this warning ```svg-sprite-loader exception. Some loaders will be applied after svg-sprite-loader in extract mode```

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by aLkRicha** [comment]
I'll close it because I figured out the situation
