### ISSUE TITLE
I can't set the spriteFilename in version 3.7.3

### ISSUE THREAD

**Issue by imnot2** [kisenka/svg-sprite-loader#279]
**Do you want to request a feature, report a bug or ask a question?**
Bug

**What is the current behavior?**
When i configure spriteFilename option, output always is default name(sprite.svg)

**What is the expected behavior?**
I want control output file name by spriteFilename option

**Please tell us about your environment:**
- Node.js version: ?
v8.4.0
- webpack version: ?
^4.8.1
- svg-sprite-loader version: ? 
^3.7.3
- OS type & version: ?
window 10

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

https://github.com/imnot2/svg-sprite-loader--279

https://github.com/imnot2/svg-sprite-loader--279/blob/master/uat.config.js

https://travis-ci.org/imnot2/svg-sprite-loader--279/jobs/379029602

**Comment by kisenka** [comment]
@rguanghui thanks, you are right.

**Comment by imnot2** [comment]
I must provide these two rules for two different file formats (jsx & less), 
mergeing svg background-image in less, i use svg-sprite-loader;
using svg as a react component, i use svgr;

Anyway!  after change the order of these rules, it's work !
https://github.com/imnot2/svg-sprite-loader--279/commit/993da7fe9adc30cb72f65102309fe7eddb65dc6c#diff-86b76ea5eaea59291e53ab7d5343950b

**Comment by rguanghui** [comment]
you can do like this

```
{
  test: /inline.svg$/,
  loader: 'svgr/webpack', 
},
{
  test: /.svg$/,
  loader: 'svg-sprite-loader', 
}
```

**Comment by imnot2** [comment]
The same svg may be used on svg-sprite-loader and svgr
