### ISSUE TITLE
The svg is not outputted when using context

### ISSUE THREAD

**Issue by AoDev** [kisenka/svg-sprite-loader#28]
Maybe I'm doing something wrong, but:

Having my webpack config:
```
      {
        test: /img\/sprite\/.+\.svg$/,
        loader: 'svg-sprite'
      }
```

It will work, for a single file:
```
require('../img/sprite/icon-help.svg')
```

But I can't get it to work with context, trying this way:

```
var files = require.context('../img/sprite', true, /.svg$/)
```

The svg isn't added to the body of the page.

**Comment by princed** [comment]
Do you "execute" your modules after that? You'll need to add something like `files.keys().forEach(filed)` in this case.

**Comment by AoDev** [comment]
My mistake. I had two issues. The first one was related to a conflict with another loader. While investigating, I removed the line you mention (`files.keys().forEach(files)`) and then I forgot to put it back.

 Sorry for the inconvenience and great module, thx : )

**Comment by princed** [comment]
My pleasure :)

**Comment by Memoyr** [comment]
Hi, this maybe a basic question, i'm new at using webpack. Where should be added , those lines:
var files = require.context('svg-sprite!svgo-loader?useConfig=svgoConfig1!../img/sprite', true, /.svg$/);
files.keys().forEach(files)

In my App.js (or SomeComponent.js)  OR in webpack config ?  
thanks

**Comment by kisenka** [comment]
This code should be placed in your application

**Comment by gohilumesh** [comment]
Hi, I am using Angular2 and when I add this line 
const svgfiles =
    require.context('svg-sprite!svgo-loader?useConfig=svgoConfig1!./public/svg-source', true, /\.svg$/);
svgfiles.keys().forEach(svgfiles);

it complain that "property 'context' does not exist on type 'NodeRequire'" 
Can you please help
