### ISSUE TITLE
Resource query string is inaccessible for modification in symbolId

### ISSUE THREAD

**Issue by dsbudiac** [kisenka/svg-sprite-loader#281]
## Do you want to request a feature, report a bug or ask a question?
bug

## What is the current behavior?

`symbolRegExp` does not include query string / `resourceQuery` to match. Thus, the query string is always appended to the symbol id and there's no way to remove from the output symbol id (that I can tell).

**entry.js**
```js
import './my-image.svg?sprite';
```

**webpack config svg-sprite-loader rule**

```js
let rule = {
  test: /\.svg$/,
  resourceQuery: /sprite/,
  loader: 'svg-sprite-loader',
  options: {
    extract: true,
    symbolRegExp: /(.+)--sprite$/,
    symbolId: '[1]'
  }
}
```

**sprite.svg** output
```svg
<svg>
<symbol ... id="[1]--sprite" />
...
```

## What is the expected behavior?

**sprite.svg** output
```svg
<svg>
<symbol ... id="my-image" />
...
```

**Please tell us about your environment:**

- Node.js version: 8.11.1
- webpack version: 4.8.3
- svg-sprite-loader version: 3.7.3
- OS type & version: macOS High Sierra 10.13.4

**Comment by kisenka** [comment]
Unfortunately loader-utils#interpolate doesn't support query string interpolation, so I add ability to use `symbolId` as function which accepts 2 arguments - image path and image query, so you can do something like this:

```js
const path = require('path');

let rule = {
  test: /\.svg$/,
  resourceQuery: /sprite/,
  loader: 'svg-sprite-loader',
  options: {
    extract: true,
    symbolId: path => path.basename(path, '.svg')
  }
}
```
