### ISSUE TITLE
<base> breaks icons

### ISSUE THREAD

**Issue by davidspiess** [kisenka/svg-sprite-loader#29]
If a `base` element is present, the icons break, regardless if i'm using angular or not. Why not make a universal solution?

**Comment by kisenka** [comment]
@davidspiess https://github.com/kisenka/svg-sprite-loader/issues/25#issuecomment-194844134

**Comment by princed** [comment]
Unfortunately we can't have automatic universal solution. 
Angular is just widespread case of `<base>` usage, which is easy to automate.

**Comment by davidspiess** [comment]
Why not always use an absolute path like in the solution mentioned by @kisenka? Shouldn't that fix the `<base>` problem completely?
At the moment i'm using something like this

```html
<use xlink:href="${ window.location.href.split('#')[0] + icon }"></use>
```

**Comment by princed** [comment]
Because absolute path changes when navigation (using history API) happened, so we have to update `xlink:href`s of all existing icons, that's why we listen to custom `spriteLoaderLocationUpdated` event in order to do it on time.

So actually you need both second and third point from the comment.

**Comment by davidspiess** [comment]
Thanks for the clarification :) I didn't think about the history api. More docs about the `<base>` issue would be a great addition :+1:

**Comment by princed** [comment]
My pleasure :)
Let us know if you have any ideas on custom event API.

**Comment by princed** [comment]
@davidspiess BTW, would you like to make a PR regarding #30?

**Comment by davidspiess** [comment]
@princed right now i'm quite busy, but i'll dive into it this weekend :)
