### ISSUE TITLE
Don't find svg-sprite-loader/runtime/symbol.build file in the npm package

### ISSUE THREAD

**Issue by remoe** [kisenka/svg-sprite-loader#290]
Bug?

**What is the current behavior?**

One can't find svg-sprite-loader/runtime/symbol.build 

**What is the expected behavior?**

svg-sprite-loader/runtime/symbol.build should exists?
It's documented in readme.md

- Node.js version: 8.11.3
- webpack version: 3.10.0
- svg-sprite-loader version:  3.9.0
- OS type & version: windows / WSL

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by remoe** [comment]
I don't think this is needed. It's documented on your readme:

```
symbolModule (autoconfigured)
Same as spriteModule, but for sprite symbol. By default also depends on target webpack config option:

svg-sprite-loader/runtime/browser-symbol.build for 'web' target.
svg-sprite-loader/runtime/symbol.build for other targets.
```
But this file is not there. It has only this:

```
browser-sprite.build.js
browser-sprite.js
sprite.build.js
sprite.js
```

**Comment by radislaw** [comment]
Документация отличается от того, что есть в npm пакете, или устарела! Ни уя не понятно, что, куда. Постоянно требует, какие-то зависимости, о которых в документации ничего не написано

**Comment by kisenka** [comment]
Docs were updated, see [symbolModule section](https://github.com/kisenka/svg-sprite-loader/#symbol-module).
