### ISSUE TITLE
Is it possible to compare icons inner XML

### ISSUE THREAD

**Issue by Krasnopir** [kisenka/svg-sprite-loader#293]
Sometimes in different components one and the same icon is called differently, and gets to the sprite on the fact twice, or more.

And sometimes different icons with the same name are called in different components, and the last component call icon is replaced in sprite.

It would be nice to compare them XML and rename them in case of the same code, or apply v1 v2 to the end of icon id in sprite in case of different XML code with the same icon name

**Comment by kisenka** [comment]
Could you please create repo with minimal setup to demonstrate a problem (package.json, webpack config, SVG image and piece of your code). If you don't want to create a repository - you can create a [gist](http://gist.github.com) with multiple files.

**Comment by Krasnopir** [comment]
Hi! I created repo https://github.com/Krasnopir/isomorphic-style-provider
with simple configuration. There you can try how working isomorphic-style-loader and svg-sprite-loader.
Different icons in components have the same name and gets into the sprite once.

**Comment by Krasnopir** [comment]
At least console  warning or error in case of a match of names and different XML of icons

**Comment by kisenka** [comment]
> And sometimes different icons with the same name are called in different components, and the last component call icon is replaced in sprite.

@Krasnopir you can use [symbolId](https://github.com/kisenka/svg-sprite-loader#symbolid-string--functionpath-query-default-name) option to avoid such cases.

**Comment by Krasnopir** [comment]
sorry. forgot about [hash]
symbolId : 'kisenka-[name]-[hash:base64:5]'
