### ISSUE TITLE
Extract SVG sprite AND inject it.

### ISSUE THREAD

**Issue by SpikeShape** [kisenka/svg-sprite-loader#299]
Hey,

Is there a way to let svg-sprite-loader both inject and extract the svg sprite? My goal is to have it injected in my html file and put it into an assets folder for later use.

My current loadout:
- Node.js version: 8.10.0
- webpack version: 3.12.0
- svg-sprite-loader version: 3.8.0
- OS type & version: macOS 10.13.6

**Comment by kisenka** [comment]
Check this [example](https://github.com/kisenka/svg-sprite-loader/tree/master/examples/interop-with-html-webpack-plugin)

**Comment by SpikeShape** [comment]
Exactly what I was looking for. I just didn't know how to put it. Thank you so much!
