### ISSUE TITLE
More docs on `<base>` tags workaround

### ISSUE THREAD

**Issue by princed** [kisenka/svg-sprite-loader#30]
To provide clear visible information on topics we explained in #25 and #29

**Comment by freelance-tech-writer** [comment]
I can help with this, but I have a few questions:

- does using `<base>` _always_ break svg-sprite-loader? or does it only break when `<base>` is used in conjunction with an app that uses the history API to handle navigation?
- is `angularBaseWorkaround` only meant for Angular.js (1.x)? or does it also work with Angular2?
- can you confirm that [the last comment](https://github.com/kisenka/svg-sprite-loader/issues/25#issuecomment-219981386) on thread #25 does indeed fix the issue for Angular2 apps?

thanks!

**Comment by princed** [comment]
Great, thank you for your effort!

* the latter, only `<base>` in conjunction with the history API breaks svg rendering
* `angularBaseWorkaround` is meant only for Angular.js (1.x)
* `<base>` removal should definitely help with the issue, and looks like that the proposed solution is appropriate for Angular2, see the link — https://angular.io/docs/ts/latest/guide/router.html#!#html5-urls-and-the-lt-base-href-

**Comment by princed** [comment]
Fixed in #85, thanks to @freelance-tech-writer!
