### ISSUE TITLE
Republish using svg-mixer package

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [kisenka/svg-sprite-loader#305]
Hello :)

Is there any chance of having the `svg-sprite-loader` `npm` package get updated to use the `svg-mixer` npm package instead of the `svg-baker` npm package? As far as I can tell, `svg-baker` has been replaced by `svg-mixer`.

**Comment by kisenka** [comment]
@Bosch-Eli-Black yes, I am working on moving svg-sprite-loader to svg-mixer project, but don't have enough time yet. I'am planning to finish this work in November

**Comment by Bosch-Eli-Black** [comment]
Okay. Thanks, man.

**Comment by Bosch-Eli-Black** [comment]
Hi @kisenka. Sorry to bug you, but are you still planning on moving this package over to using the svg-mixer package instead of svg-baker?
