### ISSUE TITLE
Audit issue. Found 4 low severity vulnerabilities

### ISSUE THREAD

**Issue by vtereshyn** [kisenka/svg-sprite-loader#323]
Hi!
Recently after running the `npm audit` script, I got an issue that `4 low severity vulnerabilities have been found`
The full list is below. As I understood the problem is in `merge-options` package. 
So, maybe you have opportunity to fix this nasty problem. Thank you in advance!

![audit](https://user-images.githubusercontent.com/32247411/47205730-6bf80300-d38f-11e8-8640-ff51d5175cba.png)

**Comment by losbeekos** [comment]
I wanted to create an issue but instead found this.

As I understand, the `svg-baker` package has been renamed to `svg-mixer`, correct me if I'm wrong. Svg-mixer also contains the merge-options package so would throw the same vulnerabilities. I've created an issue over there: https://github.com/JetBrains/svg-mixer/issues/42.

**Comment by vtereshyn** [comment]
# https://github.com/JetBrains/svg-mixer/issues/42

**Comment by vtereshyn** [comment]
#JetBrains/svg-mixer#42

**Comment by kisenka** [comment]
Fixed in svg-sprite-loader@4.1.3
