### ISSUE TITLE
Automatically strip color

### ISSUE THREAD

**Issue by SBoudrias** [kisenka/svg-sprite-loader#33]
It'd be nice it the module would automatically strip colors from the svg files.

**Comment by kisenka** [comment]
@SBoudrias what use case for such behavior?

**Comment by SBoudrias** [comment]
@kisenka if you strip color, you can then assign it via CSS or use `currentColor`.

That being said, I see that svgo have been removed from the project and the suggestion is to just combine the loaders. That's what I did for now.

Maybe it'd be good to add a note to the readme about how you can combine the svgo-loader to minimize/process svg files.
