### ISSUE TITLE
spriteModule and symbolModule imports dont work with yarn PnP

### ISSUE THREAD

**Issue by bimbiltu** [kisenka/svg-sprite-loader#344]
**Do you want to request a feature, report a bug or ask a question?**
Report a bug

**What is the current behavior?**
Currently this loader generates imports like `import 'svg-sprite-loader/runtime/browser-sprite.build'` and `import 'svg-baker-runtime/browser-symbol'`. These imports currently rely on the svg-sprite-loader and svg-baker-runtime packages being hoisted to work which can cause errors in some edge causes and also causes webpack to fail on projects using [yarn pnp](https://yarnpkg.com/lang/en/docs/pnp/) [with webpack](https://github.com/arcanis/pnp-webpack-plugin). When building you'll see an error like the following:

```
ERROR in ./src/circle.svg
Module not found: Error: You cannot require a package ("svg-baker-runtime") that is not declared in your dependencies (via "/Users/mdavis/temp/webpack-test/src/circle.svg")
 @ ./src/circle.svg 1:0-60 3:17-29
 @ ./src/index.js
```

**What is the expected behavior?**
I should be able to use the loader with yarn Plug n Play

**If the current behavior is a bug, please provide the steps to reproduce, at least part of webpack config with loader configuration and piece of your code.**
A minimal reproducer can be found here: https://github.com/bimbiltu/svg-sprite-loader-pnp-repro

**Please tell us about your environment:**

- Node.js version: 10.15.1
- yarn version: 1.13.0
- webpack version: 4.29.6
- svg-sprite-loader version: 4.1.3
- OS type & version: macOS mojave

**Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)**

I tried to work around this problem by configuring the loader like so:
```
use: {                                                                                                                                                                    
  loader: require.resolve('svg-sprite-loader'),                                                                                                                           
  options: {                                                                                                                                                              
    spriteModule: require.resolve('svg-sprite-loader/runtime/browser-sprite.build'),                                                                                      
    symbolModule: require.resolve('svg-baker-runtime/browser-symbol'),                                                                                                    
  },                                                                                                                                                                      
}, 
```
However this doesn't work due to imports to spriteModule and symbolModule [always being turned into a path relative to the package root](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/runtime-generator.js#L36-L37) rather than relative to the file being imported. I end up with errors like the following:

```
ERROR in ./src/circle.svg
Module not found: Error: Can't resolve '../../Library/Caches/Yarn/v4/npm-svg-baker-runtime-1.4.0-eb53a5447856b824095f8344e969663b002b4149/node_modules/svg-baker-runtime/browser-symbol.js' in '/Users/mdavis/git/svg-sprite-loader-pnp/src'
 @ ./src/circle.svg 1:0-174 3:17-29
 @ ./src/index.js
```

The solution here should be to have `spriteModule` default to `require.resolve('../runtime-browser-sprite.build')` and have `symbolModule` default to  `require.resolve('svg-baker-runtime/browser-symbol')`. This change would also require the [generated imports](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/runtime-generator.js#L36-L37) to be made relative to the loaders context rather than the compilation context (i.e. pass `params.loaderContext` to stringifyRequest instead of `{context}`). To preserve existing behavior, relative paths passed as options can first be resolved against the compilation context before being passed to the 2nd parameter of stringifyRequest

The changes to the runtime-generator make sense even ignoring yarn PnP IMO. The current implementation generates the same exact import (i.e. `import sprite from './my-browser-sprite.js'`) regardless of where the js file importing the svg is located. This essentially means that files in only one directory (but not any of its subdirectories) can actually import an svg that is run through this loader.

I would be happy to send a PR with the above changes if you think they're reasonable.

**Comment by kisenka** [comment]
Fixed in svg-sprite-loader@4.1.4
