### ISSUE TITLE
Svg not visibe

### ISSUE THREAD

**Issue by Pet3ris** [kisenka/svg-sprite-loader#354]
Hi There,

First of all, thanks for creating the library, eager to use it as my main option for rendering svgs using reason react.

**Do you want to request a feature, report a bug or ask a question?**

Ask a question/report a bug

**What is the current behavior?**

Svg not rendering. The path gets rendered in the browser but the svg is not visible at all.

**What is the expected behavior?**

Svg should be rendering. Full source code [here](https://stackoverflow.com/questions/57546347/svg-not-visible-svg-sprite-loader-webpack-reason-ml).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please tell us about your environment:**

- Node.js version: v12.1.0
- webpack version: v4.0.1
- svg-sprite-loader version: v4.1.6
- OS type & version: OSX 10.14.3

[Stackoverflow](https://stackoverflow.com/questions/57546347/svg-not-visible-svg-sprite-loader-webpack-reason-ml).

Also could be relevant to note I'm using ReasonML to render the svg.

**Comment by klyukvushka** [comment]
@Pet3ris hi! did you solve this problem? i've got the same issue, invisible icons, and warnings in console while i use option "extract: true"

**Comment by Pet3ris** [comment]
For me it was an issue of not using the right sprite name. I found that by using an example project and then changing things one by one into my set up.
