### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by whois42** [kisenka/svg-sprite-loader#40]
Hello,
I testing my react application with Mocha and when I run `npm test`  I got the  exception: 
`app/DOM/pure/landing-assets/logo.svg:3
React.createElement(
^

ReferenceError: React is not defined`

How I can solve this problem?

**Comment by kisenka** [comment]
@whois42 I need more details. Please create a test case which reproduces error (webpack.config.js, your react component and svg file).

**Comment by princed** [comment]
@whois42 Have you solved the issue? Is there some info for people who may encounter it too?

**Comment by antonydb** [comment]
If anyone ends up here like I didi, this might be helpful https://github.com/jhamlet/svg-react-loader/issues/31.

**Comment by mascardoso** [comment]
I also have the same issue.
Tried reading @antonydb post reference but their options for me don't work.
The weird thing is that I only have this issue when starting webpack in dev env and it still works.

This is the error:
```
[0]     "stack": [
[0]       "ReferenceError: React is not defined",
[0]       "    at Object.<anonymous> (/front/assets/img/sprite.svg:1:1)",
[0]       "    at Module._compile (module.js:571:32)",
[0]       "    at loader (/node_modules/babel-register/lib/node.js:144:5)",
[0]       "    at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:154:7)",
[0]       "    at Module.load (module.js:488:32)",
[0]       "    at tryModuleLoad (module.js:447:12)",
[0]       "    at Function.Module._load (module.js:439:3)",
[0]       "    at Module.require (module.js:498:17)",
[0]       "    at require (internal/module.js:20:19)",
```

**Webpack config:**

```
..
      {
        test: /\.svg$/,
        loader: 'svg-sprite-loader',
        include: path.resolve(__dirname, 'front/assets/img/')
      }
..
```

**jsx-1:**

```
import React from 'react'
import '../../../assets/img/sprite.svg'

const Icon = ({ type, fill, size, padded, id }) => (
  <svg ...>
    <use xlinkHref={`#sprite-${type}`} />
  </svg>
)

export default Icon
```


**jsx-2:**

```
import Icon from '../icon.jsx'

<Icon type='customize' size='--medium' />
```

**Comment by NorbertNader** [comment]
I know this is an old post but look at the errors you are getting:
`Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-register/lib/node.js:154:7)",`

I had this same issue and what you can do is add an extensions to node. This is actually a babel issue. Try adding:
`require.extensions['.svg'] = () => {}; `
to wherever you are requiring babel-register

you could also try passing ignore to babel-register (https://babeljs.io/docs/en/babel-register), but for some reason that is not working for me, seems like and issue with babel.
