### ISSUE TITLE
Loader should support different configs

### ISSUE THREAD

**Issue by mdreizin** [kisenka/svg-sprite-loader#46]
It would be nice to have ability to use custom configs via https://github.com/webpack/loader-utils#getloaderconfig

**Comment by kisenka** [comment]
@mdreizin hi! Sorry for delay. You can specify different configs in 0.0.26 via `config` option like this:
```js
{
  module: {
    loaders: [
      {
        test: /\.svg$/,
        loader: 'svg-sprite?config=svgConfig1'
      }
    ]
  },

  svgConfig1: {
    name: 'tralala_[name]'
  }
};
```
