### ISSUE TITLE
Add a option to remove some attributes of svg

### ISSUE THREAD

**Issue by jairzh** [kisenka/svg-sprite-loader#47]
Can you add a option to remove some attributes of svg, such as `Fill` attribute

**Comment by kisenka** [comment]
@jairzh no, sorry. Sprite loader should only compose images in single sprite. You can use posthtml to preprocess/postprocess your images:

```
npm i posthtml-loader posthtml-remove-attributes
```

```js
var removeAttrs = require('posthtml-remove-attributes');

module.exports = {
  module: {
    loaders: [
      {
        test: /\.svg$/,
        loader: 'svg-sprite!posthtml'
      }
    ]
  },

  posthtml: function() {
    return {
      defaults: [
        removeAttrs(['fill'])
      ]
    }
  }
};
```

**Comment by jairzh** [comment]
It does not work for me, but thanks for tips.

**Comment by kisenka** [comment]
@jairzh why it does not work for you?

**Comment by jairzh** [comment]
@kisenka The  posthtml can remove the `Fill` attribute, but it will also remove the `viewBox` of the `symbol` tag, I tried to use `posthtml-extend-attrs` to re-add the `viewBox`, but it does not work. I went through the posthtml's document and google it, but don't figure out the reason.

**Comment by princed** [comment]
Does it happen without `posthtml-remove-attributes` added to posthtml config?
If it doesn't please file a issue to [posthtml-remove-attributes](https://github.com/princed/posthtml-remove-attributes), otherwise to [posthtml](https://github.com/posthtml/posthtml) itself.

**Comment by jairzh** [comment]
I will create an issue under the [posthtml](https://github.com/posthtml/posthtml)

**Comment by princed** [comment]
Great, thanks!

**Comment by kisenka** [comment]
@jairzh I published temporary workaround for https://github.com/posthtml/posthtml/issues/146, please update svg-sprite-loader to 0.0.25

**Comment by jairzh** [comment]
@kisenka  You are great, it works now, thanks a lot.
