### ISSUE TITLE
No icon rendered

### ISSUE THREAD

**Issue by n00dl3** [kisenka/svg-sprite-loader#48]
I tried this loader yesterday, and I can't figure out how to load icons, I'm working on an angular 2 app so I created a component that does more or less the same job as the react-one in the examples (see code below) but it does not display any icon.

from the `README.md`:

> By default sprite renders when DOMContentLoaded event fires and injects as first child in document.body

* I don't see neither anything added to the body after page load (even before angular's bootstrap) nor a single reference to a `sprite.js` script in the list of sources in Chrome.
* I don't have any output at compile or run time, it just does not render....
* I removed my `<base>` tag

Here is my code :
```typescript
import { Component, Input, OnInit, ElementRef} from '@angular/core';
var Glyphs = {};
var req = require.context("./icons", false, /\.svg$/);
req.keys().forEach(function(file: string) {
  var id = req(file);
  var name = /^\.\/(.*)\.svg$/.exec(file)[1];
  if (name) {
    Glyphs[name] = id;
  }
});

@Component({
  selector: 'lnk-icon',
  template: "",
  directives: [],
  providers: [],
  pipes: []
})
export class IconComponent implements OnInit {

  @Input("glyph")
  private glyph: string;

  constructor(private element: ElementRef) {
  }

  ngOnInit() {
    var svgns = "http://www.w3.org/2000/svg";
    var xlinkns = "http://www.w3.org/1999/xlink";
    var svg = document.createElementNS(svgns, "svg");
    var use = document.createElementNS(svgns, "use");
    use.setAttributeNS(xlinkns,"href",Glyphs[this.glyph]);
    svg.appendChild(use);
    this.element.nativeElement.appendChild(svg);
  }

}

```
and my webpack config:
```javascript
//stuff
  module: {
     loaders:[{
      test: /\.svg$/,
      loader: "svg-sprite"
    }]
  },
//more stuff
```
Note that I first tried using Angular's template syntax but didn't work neither...

**Comment by kisenka** [comment]
@n00dl3 `setAttributeNS(xlinkns,"href",""+Glyphs[this.glyph]+")")` remove redundant bracket from end of the line.

**Comment by n00dl3** [comment]
oh yeah, thanks.
But that does not come from here, it's a mistake from my copy/paste and older tests...

**Comment by kisenka** [comment]
@n00dl3 could you please provide full test case? Webpack config, node js dependencies (just copy them from package.json), component code and a few arbitrary SVG files? It will be more faster to investigate your problem then. You can place testcase on [gist.github.com](http://gist.github.com) or create separate repo under your account.

**Comment by n00dl3** [comment]
https://gist.github.com/n00dl3/b364815982b2faefc0d348937fe192de

**Comment by n00dl3** [comment]
Could you please elaborate a bit more about what is supposed to happen when svg files are required ?
I don't really understand what is the purpose of the `/lib/web/sprite.js` file :
* when should it be loaded ?
* is it loaded automatically by webpack or should I write my own ?

A surprising thing that I noted is that if I navigate to the "id" of my icon, chrome tells me that:
>This page contains the following errors:
>
>error on line 2 at column 1: Document is empty
>Below is a rendering of the page up to the first error.

but if I look in the network tab, the server is actually sending something:
```javascript

var sprite = require("/path/to/my/project/dev/node_modules/svg-sprite-loader/lib/web/global-sprite");
var image = "<symbol viewBox=\"0 0 192 192\" id=\"chevron-right-circle\" > <title>icons-cs5</title> <path d=\"M96,36.13A59.87,59.87,0,1,1,36.13,96,59.94,59.94,0,0,1,96,36.13m0-16A75.87,75.87,0,1,0,171.87,96,75.87,75.87,0,0,0,96,20.13Z\"/> <polyline points=\"85.58 121.84 111.42 96 85.58 70.18\" style=\"fill: none;stroke: #000;stroke-linecap: round;stroke-linejoin: round;stroke-width: 16px\"/> </symbol>";
module.exports = sprite.add(image, "chevron-right-circle");
```

**Comment by n00dl3** [comment]
[I created a repo for testing](https://github.com/n00dl3/test_svg_sprite), it will be easier for you to try:
just run 
```
npm install
npm start
```
and you are good (server is listening on localhost:8080)

**Comment by kisenka** [comment]
@n00dl3 when svg files are required happens actually this:
> When you require an image, loader transforms it to SVG symbol and add it to the array in special [sprite](lib/web/sprite.js) class. When browser event `DOMContentLoaded` fires sprite will be rendered and injected as first child of `document.body`. Require statement e.g. `require('svg-sprite!./image.svg')` returns a symbol id, so you can reference it later in `<svg><use xlink:href="#id"/></svg>`.

`/lib/web/sprite.js` it's a client runtime which holds all symbols and render whole sprite at DOMContentLoaded event.

Loader works in following steps:
1. Process SVG image, convert it to symbol and [return as a string](https://github.com/kisenka/svg-sprite-loader/blob/master/index.js#L47).
2. Generate client runtime code, which add sprite.js as dependency, so it's becomes a part of a bundle and will be invoked on the _runtime_. Client runtime has symbol string on input and add it to the symbols [list of the sprite](https://github.com/kisenka/svg-sprite-loader/blob/master/lib/web/sprite.js#L180).

**Comment by kisenka** [comment]
@n00dl3 great, give me some time.

**Comment by kisenka** [comment]
@n00dl3 just remove `svg` from this line https://github.com/n00dl3/test_svg_sprite/blob/master/config/webpack.common.js#L28 :)

**Comment by n00dl3** [comment]
F**k!!!!
Well thank you very much.
Now excuse me, I have to suicide myself... :rage4:

**Comment by kisenka** [comment]
No problem :)

BTW :scream:
![screen shot 2016-07-07 at 17 45 45](https://cloud.githubusercontent.com/assets/2714771/16657237/6a550ea0-446a-11e6-8e1f-ce55b0b46b19.png)

**Comment by n00dl3** [comment]
"phantomjs-prebuilt": "^2.1.7"<-culprit

**Comment by princed** [comment]
@kisenka BTW, could we detect such cases somehow?

**Comment by kisenka** [comment]
@princed I think yes - http://webpack.github.io/docs/loaders.html#loaders

**Comment by kisenka** [comment]
@princed a pochemu vi sprrrashivaete?

**Comment by cartogram** [comment]
@n00dl3 Don't feel so bad, I just did the exact same thing! Lucky for me I found this thread

**Comment by aalenliang** [comment]
Great! I am with you!
