### ISSUE TITLE
IE issues with svg sprite technique

### ISSUE THREAD

**Issue by stream7** [kisenka/svg-sprite-loader#49]
Hello!
 
I came across this [IE issue/bug](https://github.com/facebook/react/issues/7355) and I'm wondering a) if you have find a workaround for this b) if this should be documented in the README.

Thoughts?

**Comment by kisenka** [comment]
@stream7 hi! Never heard about this before. Maybe replace whole `<svg>` instead of `<use>`?

**Comment by stream7** [comment]
@kisenka hey! How can you do that though? You don't have such control in React, after the VDOM reconciliation it will just update the `xlinkHref` attribute since that's the only thing that has changed.

The workaround I'm using now is to render both icons and use a css class to show only the "active" one.

**Comment by kisenka** [comment]
@stream7 I am not good in React, but can not you force component rerender? If not, maybe use SVG as background image in this case?

**Comment by stream7** [comment]
> but can not you force component rerender

I believe you can force a virtual DOM rerender but not a real one which won't help in this case.

Sure, you can use other techniques, I was just wondering if there is a workaround so we could stick to the sprite and the `Icon` component. 

Anyways, thanks for the response. I'll let you know if I find a workaround.
