### ISSUE TITLE
CSS/<style> Support

### ISSUE THREAD

**Issue by axelson** [kisenka/svg-sprite-loader#50]
Does svg-sprite-loader support `<style>` tags within the SVG's at all? Based on #27 I think the answer is no?

**Comment by princed** [comment]
In simple cases it may work. Are experiencing some specific issue?

**Comment by axelson** [comment]
Partially I was just unsure about how much CSS or <style> support there was in this library. But it looks like my svg didn't suffer the same fate as #27 although I am not sure why. But what appears won't work is re-using a gradient across multiple SVG. Is that possible?

**Comment by princed** [comment]
> re-using a gradient across multiple SVG
Could you elaborate, please?

**Comment by kisenka** [comment]
Shipped with 0.0.31
