### ISSUE TITLE
Update extract text plugin version [WebPack2]

### ISSUE THREAD

**Issue by no-more** [kisenka/svg-sprite-loader#54]
Hi,

In extract-svg-plugin.js, the syntaxe of extract-text-webpack-plugin is deprecated :
`this.extractPlugin = new ExtractPlugin(this.id, this.filename, this.options);`

should be something like : 
`this.extractPlugin = new ExtractPlugin({ filename: this.filename, id: this.id});`

There might be other changes as it's not enough to make this work again.

Thanks a lot.

**Comment by Memoyr** [comment]
Hi, is this issue will be solved ? Or is there a workaround I could do while waiting for it ?
thanks

**Comment by kisenka** [comment]
Sorry guys, not enough time. PR is very welcome!

**Comment by no-more** [comment]
Hi,

Sorry but I didn't manage to make this work till now

**Comment by kisenka** [comment]
Shipped with 0.0.30. Also now you can omit `extract=true` option, loader will try to detect extract mode automatically.

**Comment by farwayer** [comment]
@kisenka Thanks for fixing. Now extracting working well. But one problem still exists. `ExtractSVGPlugin` outputs `[object Object]` as id.

**Comment by kisenka** [comment]
@farwayer could you tell me more about your setup? Example of SVG file will be useful too.

**Comment by farwayer** [comment]
@kisenka I made sample repo with test:
```
git clone https://github.com/farwayer/svg-sprite-loader-bug
cd svg-sprite-loader-bug
npm install
npm start
```
