### ISSUE TITLE
[suggestion] Adding a `esModule` option for esModule interop

### ISSUE THREAD

**Issue by HerringtonDarkholme** [kisenka/svg-sprite-loader#55]
Thanks for writing this loader! It helps me a lot.

I'm migrating my JavaScript project to TypeScript. Then svg-sprite-loader has some issue with it's `default export` behavior.

https://github.com/Microsoft/TypeScript/issues/2719 has stated that `import defaultimport from '...'` will transpiled to `var defaultImport = require('....').default`

Now svg-loader is transpiled to `module.export = XXX`.  If a `esModule` option is added, so user can control whether to transpile to `module.export.default = xxx`.

Now babel has transpiled code to `esModule` compatible code by default.
I think this is a desirable  option for minority language user, and it embraces future [node-esp](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#55-commonjs-consuming-es). 

If you don't mind, I can send a pull request.

Similar issue https://github.com/vuejs/vue-loader/pull/349

**Comment by princed** [comment]
A PR is surely welcome!

**Comment by HerringtonDarkholme** [comment]
Updated for doc in #56

**Comment by princed** [comment]
Thanks!
Published as 0.0.28

**Comment by HerringtonDarkholme** [comment]
Sweet! Thank you for responsiveness!
