### ISSUE TITLE
How to plug with angular material 2

### ISSUE THREAD

**Issue by no-more** [kisenka/svg-sprite-loader#58]
Hi,

I'm trying to use this plugin with angular material 2 icons but I don't know how to plug it.
According to the material2 icon documentation (https://github.com/angular/material2/tree/master/src/lib/icon) it looks like I need to refer to a physical svg sprite file but the file generation does not work any more on webpack2. Is there any other way to do it without using a physical svg sprite file ? 

Thanks.

**Comment by princed** [comment]
I don't think so. The only other possibility is to [provide in-memory filesystem](https://github.com/christianalfoni/webpack-bin/issues/106) to webpack, but I don't think either it could help in this case.

Closing issue, but feel free to ask more questions.
