### ISSUE TITLE
svg with clip-path doesn't display

### ISSUE THREAD

**Issue by badtant** [kisenka/svg-sprite-loader#63]
I have an svg which includes a clip-path. When using it with this loader is doesn't display.

```
<svg>
  <defs>
    <clipPath id="mask">
      <circle cx="166.201" cy="166.201" r="166.201"/>
    </clipPath>
  </defs>
  <g clip-path="url(#mask)">
    ...
  </g>
</svg>
```

When debugging this I found that if I remove visibility: hidden from the injected svg with all the symbols it displays correctly. Is visibility: hidden needed?

**Comment by princed** [comment]
You may find a solution in #59

**Comment by badtant** [comment]
Hmm, ok. But shouldn't this be fixed generally? It's not that uncommon with clip-paths...

**Comment by princed** [comment]
@kisenka What do you think?

**Comment by kisenka** [comment]
@princed do you mean change `display: none` to `visibility: hidden` globally?

**Comment by princed** [comment]
Or some other solution.

**Comment by kisenka** [comment]
@badtant how it works with `display: none`?

**Comment by badtant** [comment]
With `visibility: hidden`
Nothing shows

With `display: none`
Svg shows but the clip-path doesn't work

Isn't it enough width:
```
width: 0;
height: 0;
position: absolute;
```
?

**Comment by kisenka** [comment]
@badtant maybe, I don't know actually :) I can add this in 0.1.0 and we'll see.

**Comment by badtant** [comment]
This is snippet I use for screen reader only content and have never experienced problems with it.
```
  position: absolute;
  left: -10000px;
  width: 1px;
  height: 1px;
  overflow: hidden;
```

I tried it on the svg and it works so maybe safer to use that!

**Comment by kisenka** [comment]
@badtant please check 0.1.1 version
