### ISSUE TITLE
Usage with create-react-app

### ISSUE THREAD

**Issue by Grsmto** [kisenka/svg-sprite-loader#64]
Hi,
I'm trying to make the loader work within create-react-app (https://github.com/facebookincubator/create-react-app) 
but I'm having an issue and I can't figure out how to solve it:
```
client:75 ./src/css/app.scss
Module build failed: ReferenceError: document is not defined
    at new Sprite (!/blabla/node_modules/css-loader/index.js!/blabla/node_modules/postcss-loader/index.js!/blabla/node_modules/sass-loader/index.js!/blabla/src/css/app.scss:844:22)
    at Object.<anonymous> (!/blabla/node_modules/css-loader/index.js!/blabla/node_modules/postcss-loader/index.js!/blabla/node_modules/sass-loader/index.js!/blabla/src/css/app.scss:694:21)
```
This is how I added svg-sprite-loader to the webpack config: https://gist.github.com/Grsmto/7ee702886c5747f58689a228fc8517bc

Anyone you have any idea of how to debug this?

Thanks!

**Comment by princed** [comment]
@Grsmto Have you found the solution?

**Comment by Grsmto** [comment]
Yes. Actually my issue wasn't coming from svg-sprite-loader or create-react-app but the path to my SVG images.
Somehow when I switched to svg-sprite-loader the path of the images was different and the original path was making the build fail.
I had to go for example from:
`background: url("../svg/illustrations/motion.svg");`
to 
`background: url("/svg/illustrations/motion.svg")`

**Comment by princed** [comment]
Thank you for clarification. BTW, is that project public?

**Comment by Grsmto** [comment]
No. It's not live yet as well.
But our React app setup is: https://github.com/Neverbland/generator-neverbuild
I was trying to add svg-sprite-loader to it :)

I was about to open an issue to maybe skip `<img>` tags that don't support refs to sprites, dunno if you're aware of that, should I?
Thanks.
