### ISSUE TITLE
ExtractSVGPlugin outputs [object Object] for all symbol IDs

### ISSUE THREAD

**Issue by rosscourt** [kisenka/svg-sprite-loader#66]
As @farwayer posted here:
https://github.com/kisenka/svg-sprite-loader/issues/54#issuecomment-253815810

And the demo:
https://github.com/kisenka/svg-sprite-loader/issues/54#issuecomment-253931813

I wanted to open a dedicated issue for this so that they is somewhere to track it that isn't just the end of a already closed issue (#54).

@kisenka, is this what you were trying to work out in this repo? https://github.com/kisenka/multiple-extract-text-webpack-plugins

**Comment by kisenka** [comment]
@rosscourt > is this what you were trying to work out in this repo? 
yes.

If you want to extract symbols in separate file via extract-text-webpack-plugin and want import statement to return a symbol id you anyway should patch extract-text-webpack-plugin loader :(

**Comment by kirill-kruchkov** [comment]
Hello! I tried to use Extract SVG too. Here's a workaround I came up with: you can run two separate/parallel builds, first one with loader to make your client bundle and insert correct ids into your <use>'s, and second with extract to create bundle svg file. 
_Seems OK for me for now, 'cause I'm experimenting with pre-rendering html files for certain routes of my app using two separate builds._

**Comment by kisenka** [comment]
@kirill-kruchkov  

That's weird! :) svg-sprite-loader@2.0 with proper extracting mode is on the way, please read about it here #91 and take part in discussion/voting.

**Comment by kirill-kruchkov** [comment]
@kisenka well, it's ok for experimentation. Never goes to production :)

**Comment by kisenka** [comment]
Closing this because proper sprite extracting was implemented in [new 2.0 version](https://github.com/kisenka/svg-sprite-loader/releases/tag/v2.0.1). Please update.
