### ISSUE TITLE
IE Edge displays SVG on the homepage, but not others

### ISSUE THREAD

**Issue by arloduff** [kisenka/svg-sprite-loader#68]
I'm building an Angular2 app, and have my project set up to build with Webpack using this plugin.

Inside my **app/assets/svg** folder, I have my **.svg** files.

Inside my Webpack config:

    entry: {
      'polyfills': './app/polyfills.ts',
      'vendor': './app/vendor.ts',
      'svg': './app/svg.js',
      'app': './app/main.ts'
    },
    ...
    module: {
      loaders: [
      {
        test: /\.svg$/,
        loader: 'svg-sprite'
      },
       ...
      ]
    }

And inside **app/svg.js**:

    var Glyphs = window.Glyphs = {};
    var req = require.context(helpers.root("./assets/svg"), false, /\.svg$/);
    req.keys().forEach(function(file) {
      var id = req(file);
      var name = /^\.\/(.*)\.svg$/.exec(file)[1];
      if (name) {
        Glyphs[name] = id;
      }
    });

And then I'm inserting my SVGs into my Angular2 templates like this:

    <svg>
      <use [attr.xlink:href]="'#my-svg'"></use>
    </svg>

This displays correctly on all browsers except IE 11, and Edge versions 13 and 14 (tested using Browserstack). On IE, the SVG icons display correctly on the homepage, but when I navigate to other pages, they don't display at all. Looking in the DOM Inspector, I can see that the element is setting the `xlink:href` value to `#my-svg` correctly, and I can also see that the plugin has correctly inserted the svg code inside the top of the `body` tag, in the same way as it is inserted in other browsers. Yet, it only displays correctly on the homepage (the `/` page in my app) and not on pages that have longer routes like `/home/foo`.

By placing `console.log`s inside **svg.js** I can see that the file is also being executed every time each page is loading, so I thought that maybe the problem was that  the path `./assets/` was working for the homepage `/` but not able to be found by pages like `/home/foo`. But when I try changing the path to something that would work for those pages, the Webpack build complains that it can't find that path, and I can see that the SVG data has been correctly inserted into the DOM with the correct ID anyway, so the `<use>` element should be able to reference it.

**Comment by princed** [comment]
Do you have a `<base>` tag in your page?

**Comment by arloduff** [comment]
Yes, we're dynamically setting it with HTMLWebpackPlugin like so:

    <base href="<%= htmlWebpackPlugin.options.baseUrl %>"

I've verified that it comes out in the DOM as `<base href="/">` which is what we want it to be for development.

**Comment by princed** [comment]
That's why it happens.
Two  possible solutions:
1. Get rid of `<base>` completely since it's not required in Angular 2
2. Update absolute URLs to symbols and send a custom event to update them inside spite, as we do in https://github.com/kisenka/svg-sprite-loader/blob/master/lib/web/angular-base-workaround.js

**Comment by arloduff** [comment]
Thanks!

Unfortunately, removing the `base` tag breaks our app, so I'll have to go with option 2.

Can you clarify what you mean on 2a. about "update absolute URLs to symbols in `<use>`"?

I've added the following to my **app.js**:

    export class AppComponent {
      constructor (private router: Router) {
        router.events.subscribe((val) => {
          this.notifySvgSprite(val.url);
        })
      }
    
      notifySvgSprite (url: string) {
        let evt: CustomEvent = document.createEvent('CustomEvent');
        evt.initCustomEvent('spriteLoaderLocationUpdated', false, false, {
          newUrl: url
        });
        window.dispatchEvent(evt);
      }
    }

I can verify that it's getting as far as https://github.com/kisenka/svg-sprite-loader/blob/ab0cec901df1bdd2d98cba8a46a2c1e3ed014f3e/lib/web/sprite.js#L152 in the debugger, but is not entering the `if` branch, since `href` (`#my-svg`) does not contain `currentPrefix` (`/home/foo`). Are you saying to add the page routes to where the SVGs are loaded in the `use`?

So instead of what I'm currently doing:

    <svg>
      <use [attr.xlink:href]="'#my-svg'"></use>
    </svg>

Something like

    <svg>
      <use [attr.xlink:href="'/home/foo/#my-svg'"></use>
    </svg>

That works when I do it, but then, of course, each reusable component needs to insert the path to the file which is using it.

**Comment by arloduff** [comment]
adurr. I can just create an Angular2 component that has router to display SVG icons.

THanks for the help!
