### ISSUE TITLE
Support workarounds for <base> in style attribute:

### ISSUE THREAD

**Issue by princed** [kisenka/svg-sprite-loader#7]
E.g. we should parse cases like `<path style="fill:url(#id);" d="..."></path>`.

**Comment by kisenka** [comment]
Fixed via [svg-baker-runtime](https://github.com/kisenka/svg-baker/blob/18b2340c0da957204bd5ba4338cc01939048c8b4/packages/svg-baker-runtime/test/browser-utils.test.js#L77) in `svg-sprite-loader@2.0.0-alpha.1`, please read the #91.
