### ISSUE TITLE
[Question] Getting Clip Path to work with custom sprite

### ISSUE THREAD

**Issue by markgoetz** [kisenka/svg-sprite-loader#70]
Hi!  I'm trying to resolve the issue of SVGs not appearing if they use clipping paths, using the method suggested in #60.

Here is the relevant part of my webpack config:
```
			{
				test: /\.svg$/,
				loader: 'svg-sprite?' + JSON.stringify({
					spriteModule: path.resolve(__dir, 'src', 'sprite')
				});
			}
```

And here is the sprite.js that the config references:
```
const Sprite = require('svg-sprite-loader/lib/web/sprite');

Sprite.styles.pop();
Sprite.styles.push('display:none');

module.exports = Sprite;
```

When I do this, I get an error that sprite.add is not a function.

Any thoughts on why this is not working, or when the display: none; fix referenced in #63 might be implemented?

**Comment by kisenka** [comment]
@markgoetz do you mean [this](https://github.com/kisenka/svg-sprite-loader/issues/63#issuecomment-254225478) solution?

**Comment by markgoetz** [comment]
@kisenka Yes, that one exactly.

**Comment by kisenka** [comment]
@markgoetz please check `v0.1.1`

**Comment by markgoetz** [comment]
That seems to work, thanks!

Also, I got an error message when I installed it.  It doesn't seem to affect the process, though.
```
mgoetz-osx:hgv-landing-page mgoetz$ npm install svg-sprite-loader@0.1.1 --save-dev 
welcome-page@ /Users/mgoetz/Documents/Jellyvision/Repositories/hgv-landing-page
└── svg-sprite-loader@0.1.1  invalid
```
