### ISSUE TITLE
Cannot read property '1' of null

### ISSUE THREAD

**Issue by iamrane** [kisenka/svg-sprite-loader#71]
No matter how I'm trying to import it I ends up with
```
TypeError: Cannot read property '1' of null
    at Tapable.<anonymous>....
```

webpack.config.js (in loader)
```
{
    test: /\.svg$/,
    loader: 'svg-sprite'
}
```

Icon.js
I've tried
```
import myIcon from 'assets/svg/my-icon.svg';
```
and
```
const files = require.context(`assets/svg`, false, /\.svg$/);
files.keys().forEach(files);
```

all gives me 
```
TypeError: Cannot read property '1' of null
    at Tapable.<anonymous>....
```

I've also tried
```
const files = require.context(`svg-sprite!assets/svg`, false, /\.svg$/);
files.keys().forEach(files);
```

that gives me something something must be a object or something like that

I guess that's because Im using the config and defining a loader for svgs
I have no more svg loaders in my webpack config.

**Comment by kisenka** [comment]
@iamrane could you please make a repo with test case?

**Comment by iamrane** [comment]
I created a repo but no test case. Its just to start it and you will se warnings and no icons turning up.
https://github.com/iamrane/svg-test

**Comment by iamrane** [comment]
I used create-react-app so it should be bare minimum

**Comment by princed** [comment]
Your test project doesn't contain svg-sprite-loader setup. 
Looks like you have to eject react-create-app first and then setup loader.

**Comment by iamrane** [comment]
Might be wrong here. But since im using the svg-sprite flag in the requiresi shouldnt need the config.

**Comment by kisenka** [comment]
@iamrane this is content which svg-sprite-loader accepts
![image](https://cloud.githubusercontent.com/assets/2714771/25541786/b73d4d3c-2c58-11e7-9118-ff52b1add404.png)

Looks like svg image already processed by file-loader. Adding leading `!!` to a request will disable all loaders specified in the configuration: `const svgIcons = require.context('!!svg-sprite!./icons', false, /\.svg$/)`. But you should not use such inline requires, it is not recommended.
