### ISSUE TITLE
0.1.1 version，error occur in HUAWEI browser and UC browser

### ISSUE THREAD

**Issue by lqzerogg** [kisenka/svg-sprite-loader#72]
the new version package work fine in almost all browsers, except for HUAWEI browser and UC browser. But if I make a regression to 0.0.19, it work well. Hope you guys fix it quickly.

The error message is something like this:

not support. DOM Exception 9
Sprite.wrapSVGSprite.appendSymbolSprite.add(anonymous function)webpackJsonpapp.bundle.js:788__webpack_require__manifest.bundle.js:690fnmanifest.bundle.js:111(anonymous function)(anonymous function)webpackJsonpapp.bundle.js:1319__webpack_require__manifest.bundle.js:690fn

**Comment by princed** [comment]
Does it mean that 0.0.20 doesn't work in those as well?

**Comment by lqzerogg** [comment]
No, it does. It seems that it have not work properly since  0.0.23

**Comment by princed** [comment]
Looks like 0.0.23 doesn't really differ from 0.0.22. Does it work with 0.0.22?
Please help us find first broken version.

**Comment by kisenka** [comment]
@princed poshol nahuy otsuda

**Comment by lqzerogg** [comment]
0.0.22 seems working well. Now I'm using 0.0.22.

**Comment by lqzerogg** [comment]
And 0.0.23 definitely does not work in the browsers I mentioned.

**Comment by princed** [comment]
What about previous ones?

**Comment by princed** [comment]
Published as 0.1.2, test it, please.

**Comment by lqzerogg** [comment]
It works now.

**Comment by princed** [comment]
Great, thank you for the report.
