### ISSUE TITLE
Extract isn't working

### ISSUE THREAD

**Issue by MindRave** [kisenka/svg-sprite-loader#73]
First of all, hello, Happy new 2017 and thank you for this great plugin!

I got the basics to work, the SVG takes files from a folder and generates a prepended sprite in the html that I get to reference later. 👍 

However, I cannot get extraction to work properly (to be able to use it in a .css file, for example). Running it like in the config below, getting the following error: `Error: ENAMETOOLONG: name too long` and the output of the svg.

![capture d ecran 2017-01-02 a 13 31 31](https://cloud.githubusercontent.com/assets/4063406/21589232/05cff306-d0f0-11e6-95fb-943c0d77e6a9.png)

Necessary parts of Webpack config:
https://gist.github.com/MindRave/bf5706c552b270968898b9828a3f7a73

I am sure I'm missing something here, any pointers would be very welcome! Thank you!

**Comment by kisenka** [comment]
@MindRave you can't refer to sprite symbol in CSS file (yet). Please see #66 and https://github.com/kisenka/multiple-extract-text-webpack-plugins.

**Comment by mnpenner** [comment]
[external-svg-sprite-loader](https://github.com/Karify/external-svg-sprite-loader) supposedly supports CSS. It doesn't seem to support webpack-dev-server though.

**Comment by kisenka** [comment]
@mnpenner you're right, external-svg-sprite-loader allows to refer sprite symbol from CSS. In svg-sprite loader is planned feature, but sadly I have no time for implementing this in near future (and support other issues of this loader).

**Comment by silicakes** [comment]
+1 for that feature.
I really miss it.
@kisenka - If you have some time, point me to the right parts in the code and I'll try to make a fork with a working implementation.

**Comment by kisenka** [comment]
@silicakes work in progress, I need 2-3 week to release new major version with CSS support.

**Comment by silicakes** [comment]
@kisenka Awesome! is there a branch I can follow?

**Comment by kisenka** [comment]
Not yet, I hope it will appears at the weekend :)

**Comment by silicakes** [comment]
Great!:)

**Comment by kisenka** [comment]
@MindRave
@mnpenner
@silicakes

Hey guys! svg-sprite-loader@2.0 with proper extracting mode is on the way, please read about it here #91 and take part in discussion/voting.

**Comment by kisenka** [comment]
Proper extracting was implemented in 2.0. Please check [migration guide](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md) and [extracting readme section](https://github.com/kisenka/svg-sprite-loader#extract-configuration).
