### ISSUE TITLE
Render wrong color of svg

### ISSUE THREAD

**Issue by SLyHuy** [kisenka/svg-sprite-loader#74]
I try several svg icons, but there's error when render svg. These svg icons render with wrong color.
Please check these attach images.
Thank you.

Thailand flag after render:
![screen shot 2017-01-13 at 18 08 22](https://cloud.githubusercontent.com/assets/1643397/21928074/58617c74-d9bb-11e6-8bd4-42634121af9a.png)
Original file opened on Chrome:
![screen shot 2017-01-13 at 18 12 02](https://cloud.githubusercontent.com/assets/1643397/21928167/d28c5d3e-d9bb-11e6-9128-9604926a1202.png)

![screen shot 2017-01-13 at 18 07 52](https://cloud.githubusercontent.com/assets/1643397/21928075/586502c2-d9bb-11e6-9d27-3048388abd6e.png)
<img width="567" alt="screen shot 2017-01-13 at 18 07 34" src="https://cloud.githubusercontent.com/assets/1643397/21928076/58666cd4-d9bb-11e6-85df-e32516cb2b3b.png">

SVG file here:
[svg.zip](https://github.com/kisenka/svg-sprite-loader/files/704129/svg.zip)

**Comment by rajdee** [comment]
I have same issue with the svg sprites which using fill colors for the paths. But I think what problem isn't similar **svgstore** because this plugin doesn't use svgo

**Comment by kisenka** [comment]
@SLyHuy could you please create a repo/gist with reproducible error? It renders properly for me (loaders version 0.3.0):

![image](https://cloud.githubusercontent.com/assets/2714771/23859481/cb6a8ecc-0814-11e7-90d0-a93961f9d5bb.png)

**Comment by SLyHuy** [comment]
I tried to use Sketch to open and export new svg icons and it works fine. Maybe format of svg is old and have issue. We can close ticket. Thank you.
