### ISSUE TITLE
Treat svg files differently according to intended usage

### ISSUE THREAD

**Issue by alexpi** [kisenka/svg-sprite-loader#76]
Hello,
I am a new Webpack user, so my question could be pretty basic. I want to use .svgs for sprites, css backgrounds, separate images etc. These require different loaders for spriting, optimizations etc., but since they operate on the same file type(svg), I get clashes. Using url-loader and svg-sprite-loader by using the following code for example, gives me Typerrors.

```
exports.processImages = function (paths) {
  return {
    module: {
      rules: [{
        test: /\.(jpg|png|svg)$/,
        include: paths,
        loader: 'url-loader',
        options: {
          limit: 25000,
          name: './images/[name].[ext]',
        }
      }]
    }
  }
};

exports.svgSprites = function (paths) {
  return {
    module: {
      rules: [{
        test: /\.svg$/,
        include: paths,
        loader: 'svg-sprite-loader',
        options: {
          name: 'icon-[name]',
          prefixize: true,
        }
      }]
    }
  }
};
```

Any ideas for separating spriting from other operations ?

**Comment by princed** [comment]
As of webpack 2 it's possible to [match loader by issuer](https://webpack.js.org/configuration/module/#rule-conditions), so you can use different loaders based on what files you're importing from.
Closing issue, but feel free to ask more.
