### ISSUE TITLE
Subdirectories naming

### ISSUE THREAD

**Issue by ZorGleH** [kisenka/svg-sprite-loader#82]
Hi,

I'm using svg-sprite-loader with subdirectories.

I would like to extract sprites names from the path in the following way:
`a/b/c/foo/bar.svg` => `#foo-bar`

I've tried with the default `name` configuration:
```
loader: 'svg-sprite?' + JSON.stringify({
  name: '[path]-[name]'
})
```
But the result is `#a/b/c/foo/-bar`, which contains the whole path and unwanted `/`s.

As well as the regExp option:
```
loader: 'svg-sprite?' + JSON.stringify({
  name: '[1]',
  regExp: './a/b/c/(.*)\\.svg'
})
```
But the result is `#foo/bar` which still contains unwanted `/`s.

Is there a way to achieve what I want? What would you suggest?

Thanks.

**Comment by kisenka** [comment]
@ZorGleH [loader-utils/interpolateName](https://github.com/webpack/loader-utils#interpolatename) is used as id generator for symbols, so you can use `[folder]-[name]`.

**Comment by ZorGleH** [comment]
Great! Exactly what I needed. Thanks.
