### ISSUE TITLE
extract svg

### ISSUE THREAD

**Issue by fhqdgv** [kisenka/svg-sprite-loader#83]
thank you fro you plugin
if more icon
1.html size big
2.no file and no cache
will support extract? 
https://github.com/kisenka/multiple-extract-text-webpack-plugins

**Comment by kisenka** [comment]
Yes, extracting will be supported soon. Please follow [https://github.com/kisenka/svg-sprite-loader/milestone/1 this] milestone.

**Comment by mistic** [comment]
Hey @kisenka I'm very interested in the extract feature so I can load it through a xhr request. In my opinion it should be something implemented like this: https://github.com/mrsum/webpack-svgstore-plugin

If you want I can give you some help :)

**Comment by kisenka** [comment]
Hey @fhqdgv. Thanks for suggestion, new version is in active development. I hope to release it in middle of April.

**Comment by mistic** [comment]
@kisenka Also it will be very important add the support for [folder]-[name] in the sprite name config, so we can have sprites with same name under different sub folders :)

**Comment by kisenka** [comment]
@fhqdgv
@mistic 

Hey guys! svg-sprite-loader@2.0 with proper extracting mode is on the way, please read about it here #91 and take part in discussion/voting. Also placeholders like `[folder]-[name]` supported.

**Comment by kisenka** [comment]
Extracting was implemented in 2.0.1. Please check [migration guide](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md) and [extracting readme section](https://github.com/kisenka/svg-sprite-loader#extract-configuration).
