### ISSUE TITLE
Solving Illustrator stroke-width

### ISSUE THREAD

**Issue by ZorGleH** [kisenka/svg-sprite-loader#84]
Hi,

I use `svg-sprite-loader` with Illustrator-generated icons, but the default `stroke-with` ("1") is not exported by Illustrator. That breaks my icons. What would you suggest? Is there an option to solve this with `svg-sprite-loader`? Should I make my own loader?

Thanks.

**Comment by kisenka** [comment]
This is not svg-sprite-loader related, but if you need to add some attribute in each tag - use posthtml with [loader for webpack](https://github.com/posthtml/posthtml-loader):
```js
function addStroke() {
  return (tree) => {
    tree.walk(node => {
      if (typeof node === 'string') {
        return node;
      }

      if (!node.attrs) {
        node.attrs = {};
      }

      node.attrs['stroke-width'] = '1';
      return node;
    });
  }
}

module: {
  rules: [
    {
      test: /\.svg$/,
      use: [
        'svg-sprite-loader',
        {
          loader: 'posthtml-loader',
          options: {
            plugins: () => [
              addStroke()
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by ZorGleH** [comment]
Thanks for your quick reply. I'll try it and maybe also with svgo plugin, since I already use it for optimizing.
