### ISSUE TITLE
Svg is not rendering in https site

### ISSUE THREAD

**Issue by Rigorbb** [kisenka/svg-sprite-loader#86]
I render some svg icons in two some sites with difference in protocol. In the site with http - svg is working correct. But in the site with https - svg is not displaying. How resolve this problem?

**Comment by kisenka** [comment]
@Rigorbb which browser is used? Is these sites public?

**Comment by Rigorbb** [comment]
I tried use chrome and firefox. The sites are not public.

**Comment by kisenka** [comment]
Is there any error messages in browser console? I can't provide any advice without code examples. Could you create repo/gist with reproducible error?

**Comment by Rigorbb** [comment]
I resolve this error! This was my mistake, thank you!
