### ISSUE TITLE
option to specify sprite location

### ISSUE THREAD

**Issue by AndyOGo** [kisenka/svg-sprite-loader#88]
Currently the SVG markup is injected directly as first child of `document.body`.
It would be nice to be able to inject it inside a custom DOM node specified by an CSS selector.

**Comment by kisenka** [comment]
@AndyOGo you will need to override default sprite module, please check [spriteModule](https://github.com/kisenka/svg-sprite-loader#spritemodule-autoconfigured) option and corresponding example.
