### ISSUE TITLE
Error with UglifyJS2 and webpack 2

### ISSUE THREAD

**Issue by psachs21** [kisenka/svg-sprite-loader#90]
I've recently upgraded a project from webpack 1 to 2 and I'm encountering an error when trying to minimize output from svg-sprite-loader. 

`ERROR in app.bundle.js from UglifyJs
Unexpected token: operator (>) [app.bundle.js:140332,20]`

It works fine as long as i don't add the UglifyJSplugin. Has anyone run into something similar?

**Comment by psachs21** [comment]
I know it's cause by svg-sprite-loader because if i remove the import of an svg file, everything works as expected.

**Comment by kisenka** [comment]
@psachs21 please create repo or gist with reproducible error behaviour

**Comment by psachs21** [comment]
@kisenka will do

**Comment by psachs21** [comment]
Nevermind. I found the root of the issue and it was in my own config. Thanks anways!

**Comment by princed** [comment]
@psachs21 What was the issue? We're experiencing the same stuff with our codebase.
