### ISSUE TITLE
2.0 alpha

### ISSUE THREAD

**Issue by kisenka** [kisenka/svg-sprite-loader#91]
Hi all! I am preparing to release big update, it's already accessible as `svg-sprite-loader@2.0.0-alpha.4`. 

Please read carefully about upcoming breaking changes, new features and bugfixes.

### Node.js >= 6 required

¯\_(ツ)_/¯

If you think that Node.js < 6 should be supported, please vote up in [this issue](https://github.com/kisenka/svg-sprite-loader/issues/92).

### Targeting Webpack 2

¯\_(ツ)_/¯

If you think that Webpack 1 should be supported, please vote up in [this issue](https://github.com/kisenka/svg-sprite-loader/issues/93).

### Loader should always be configured with plugin, otherwise error is thrown.

Reason: architectural changes.
Migration: just add a plugin in your webpack config
```js
// webpack.config.js
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');

...

{
  plugins: [
    new SpriteLoaderPlugin()
  ]
}
```

### `name` config option renamed to `symbolId`

Reason: more obviously.

### `regExp` config option was removed

Reason: `symbolId` should cover most of naming cases.

### `prefixize` config option was removed

Reason: all symbol elements isolated by default.

### `angularBaseWorkaround` config option was removed

Reason: Angular introduced ability to remove the base tag requirement, see correspondent [issue comment](https://github.com/angular/angular.js/issues/8934#issuecomment-56568466). If you still need it check [angular-svg-base-fix](https://github.com/everdimension/angular-svg-base-fix).

### Runtime has changed

Instead of symbol id runtime module now returns an object (class instance actually) which contains `id`, `viewBox` and `content` fields. See [SpriteSymbol class](https://github.com/kisenka/svg-baker/blob/edb3814a5ec2d11ef940955739d86d4af7a2474d/packages/svg-baker-runtime/src/symbol.js) and [runtime generator](https://github.com/kisenka/svg-sprite-loader/blob/2.0/lib/runtime-generator.js#L36).

Reason: make runtime more flexible, also it was requested in #32.
Migration: 
```js
// old
import symbol from './image.svg';
const rendered = `
<svg>
  <use xlink:href="${symbol}" />
</svg>`;


// new
import symbol from './image.svg';

// now .viewBox is available
const rendered = `
<svg viewBox="${symbol.viewBox}">
  <use xlink:href="#${symbol.id}" />
</svg>`;
```

If you think that loader should provide compatibility in this case, please vote up in [this issue](https://github.com/kisenka/svg-sprite-loader/issues/94).

### Auto configuring

Some magic now [happens](https://github.com/kisenka/svg-sprite-loader/blob/2.0/lib/configurator.js#L20) by default, viz:

- Used runtime module depends on webpack 'target' config option: [browser sprite module](https://github.com/kisenka/svg-sprite-loader/blob/2.0/runtime/browser-sprite.js) will be used for 'web' target, and [isomorphic sprite module](https://github.com/kisenka/svg-sprite-loader/blob/2.0/runtime/sprite.js) for all other targets.
- Loader turns in extract mode automatically if SVG image was imported from css/scss/html etc (see [EXTRACTABLE_MODULE_ISSUER_PATTERN config param](https://github.com/kisenka/svg-sprite-loader/blob/2.0/lib/config.js#L7)).
- Generated export format depends on webpack version, `module.exports = ...` for webpack 1, `export default ...` for webpack 2.

### Sprite generator

- Sprite/symbol generator was moved in separate project ([svg-baker](https://github.com/kisenka/svg-baker)) and fully reworked. It's incredible customizable now. Customization via plugin coming soon.

### Client runtime

- Sprite/symbol javascript runtime was moved in separate project ([svg-baker-runtime](https://github.com/kisenka/svg-baker/tree/master/packages/svg-baker-runtime)) and fully reworked.
- Added ability to specify custom runtime generator via `runtimeGenerator` option (check default [runtime generator](https://github.com/kisenka/svg-sprite-loader/blob/2.0/lib/runtime-generator.js) for example).
- Runtime symbol is an object now (class instance actually). It contains `id`, `viewBox` and `content` fields. See [SpriteSymbol class](https://github.com/kisenka/svg-baker/blob/edb3814a5ec2d11ef940955739d86d4af7a2474d/packages/svg-baker-runtime/src/symbol.js).
  - Fixes #32.
- Base URL fix in `style` attributes (via [svg-baker-runtime](https://github.com/kisenka/svg-baker/blob/18b2340c0da957204bd5ba4338cc01939048c8b4/packages/svg-baker-runtime/test/browser-utils.test.js#L77)).
  - Fixes #7.

### Server side rendering

- Server side rendering done right! See [example](https://github.com/kisenka/svg-sprite-loader/tree/2.0/examples/server-side-rendering).
- Fixes #19.

### Extract sprite/sprites as separate file/files

- Extract sprite as separate file done right! See [example](https://github.com/kisenka/svg-sprite-loader/tree/2.0/examples/extract-sprite).
- Ability to extract multiple separate sprites by webpack loader config (example will be soon).
- Ability to extract sprite for each chunk, like extract-text-webpack-plugin (example will be soon). Experimental feature, should be used with caution.
- Fixes #66, #73, #83.

## TODO

- More tests and examples.

**Comment by eugene1g** [comment]
Great, trying to test it out now. Everything seems to compile well, but the sprite is not injecting into the body as with v1. Do I need to make an explicit call to trigger this now?

**Comment by kisenka** [comment]
@eugene1g sprite should injects automatically. Which webpack version is used?

**Comment by eugene1g** [comment]
Webpack2.
```js
 {
      test: /\.svg$/,
      include: [faModulesSrcDir + "/fa-icon"],
      use: [
        {
          loader: "svg-sprite-loader",
          options: {
            symbolId: "[name]_[hash:base64:8]",
            spriteModule: "svg-sprite-loader/runtime/browser-sprite.build"
          }
        },

        "svgo-loader"
      ]
    }
```
If I leave out `spriteModule`, then nothing gets injected. If I manually specify it, then it get injected but `.stringify()` is called before any symbols get populated...

**Comment by eugene1g** [comment]
Ok two separate notes -
 
1. The default/parent spriteModule `svg-sprite-loader/runtime/sprite.build` does not have DOM mounting logic, so it makes sense that it doesn't get injected. Hence forcing it to use browser-sprite fixes that problem.

2. I include all JS scripts at the end of the page, so when browser-sprite gets loaded it immediately mounts because `document.body` exists but before my `require("icon.svg")` code gets executed (because webpack does not guarantee the order of execution of every module). Therefore, the sprite gets mounted with no symbols in it, as none are populated at runtime yet. If I force the mount to happen on `DOMContentLoaded`, then all symbols are populated as expected.

**Comment by kisenka** [comment]
@eugene1g I need your setup, could you please create a gist/repo with minimal setup which can reproduce described behaviour.

**Comment by kisenka** [comment]
> If I force the mount to happen on DOMContentLoaded, then all symbols are populated as expected
You're right. Seems like logic `if (document.body) { sprite.mount(document.body, true); }` should be removed to avoid such cases.

**Comment by eugene1g** [comment]
Ok I made a simple demo, but there the injection works as described - so something must be weird within my main environment. Only the `document.body` point was illustrated - have to dig in a bit more. I can't do it now so will have to triage during the week :/

**Comment by kisenka** [comment]
Okay, `svg-sprite-loader@2.0.0-alpha.2` is published, now browser sprite only renders when `DOMContentLoaded` [happens](https://github.com/kisenka/svg-sprite-loader/commit/a3da41921559178c40eaffa5f3f533c5d087640b).

**Comment by eugene1g** [comment]
Thanks! Fixes my use-case.

Perhaps there is merit in optimistic execution - especially if somebody is loading your script async, or on-demand, or lazily later on. In those cases `DOMContentLoaded` won't ever fire, and it's better to execute asap. Perhaps it's worth replacing that listener with [domready](https://github.com/ded/domready) - it will execute the mount for both use-cases, and the lib is small and well-tested across browsers.

**Comment by kisenka** [comment]
`svg-sprite-loader@2.0.0-alpha.3` with [domready](https://github.com/ded/domready) is published :)

**Comment by kisenka** [comment]
Also [browser-sprite](https://github.com/kisenka/svg-sprite-loader/tree/2.0/examples/browser-sprite) example added.

**Comment by rocking42** [comment]
Hey @kisenka, I've just submitted a PR https://github.com/kisenka/svg-sprite-loader/pull/96

It's just related to where Sprite is imported in plugin.js and resolving the pathname as unix doesn't mind this but when we used a Linux system it caused an issue.

Love the work and let me know if there's anything I need to fix with my PR

**Comment by kisenka** [comment]
@rocking42 merged

**Comment by alexandernanberg** [comment]
I have a use-case which seems to be broken with the alpha builds. I've updated my webpack config to match the browser-sprite example.

```
const files = require.context('./glyphs', false, /.svg$/)
files.keys().forEach(files)
``` 

But when I run webpack I get this error.

![image](https://cloud.githubusercontent.com/assets/8997319/25431458/ed4e6458-2a80-11e7-88b0-00e43a295d24.png)

All the source code can be found [here](https://github.com/alexandernanberg/minimal-react-boilerplate) (haven't pushed the alpha changes)

Should I use a different approach or is it a bug in the alpha versions?

Thanks!

**Comment by kisenka** [comment]
@alexandernanberg there is an error in your [webpack.config.js](https://github.com/alexandernanberg/minimal-react-boilerplate/blob/master/webpack.config.js#L29), you should replace `module: { loaders: [ ... ] }` to `module: { rules: [ ... ] }`

**Comment by alexandernanberg** [comment]
@kisenka Ahh... Weird that I haven't been affected by that until now. Thanks anyway! 😄

**Comment by eugene1g** [comment]
webpack 2 is surprisingly backwards compatible and as part of that translates all `loaders` to `rules` behind the scenes - that's why your config file (from webpack1 days!) was still working without issues.

**Comment by oliverturner** [comment]
Does anyone else have this error?
```
(node:38229) Warning: a promise was created in a handler at {path to}/node_modules/svg-sprite-loader/lib/plugin.js:95:23 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast ({path to}/node_modules/bluebird/js/release/promise.js:196:13)
```
Using `svg-sprite-loader@2.0.0-alpha.4` on Node v7.9.0

**Comment by kisenka** [comment]
@oliverturner this is not an error, but I'll fix it.

**Comment by kisenka** [comment]
###  🎉  2.0 is out, please read [migration guide & overview](https://github.com/kisenka/svg-sprite-loader/blob/master/2.0.md).
