### ISSUE TITLE
2.0 feature voting & discussion: Webpack 1 support

### ISSUE THREAD

**Issue by kisenka** [kisenka/svg-sprite-loader#93]
Actually I don't test new version on webpack 1, so maybe it works.

**Please react + or - on this text, don't post comments with reactions only.**

**Comment by axelson** [comment]
I'm still using Webpack 1.X and I believe that there are considerable people still on it as well. Would love to see 1.X continue to be supported.

**Comment by kisenka** [comment]
Ok, I decided to support webpack 1.

**Comment by axelson** [comment]
🎊  Thanks!
