### ISSUE TITLE
spriteFilename has no effect if configured with multiple loaders rule

### ISSUE THREAD

**Issue by obartra** [kisenka/svg-sprite-loader#97]
Hi there,

I was wondering if there were any plans to add support for `[contenthash]` or `[chunkhash]` as part of the `spriteFilename` parameter.

My use case is to make sure I'm serving the latest version when extracting the sprite into a separate file.

**Comment by obartra** [comment]
spriteFilename parameter is disregarded altogether (even when set to a constant) when I switch from a single loader to the array (`use`) syntax.

**Comment by kisenka** [comment]
@obartra this is 2 issues: 
> I was wondering if there were any plans to add support for [contenthash] or [chunkhash] as part of the spriteFilename parameter.

The short answer is no, because it requires huge architectural changes in plugin. I've create [separate issue](https://github.com/kisenka/svg-sprite-loader/issues/98).

> spriteFilename parameter is disregarded altogether (even when set to a constant) when I switch from a single loader to the array (use) syntax.

This is a bug, fixed in 2.0.2, please check.

**Comment by obartra** [comment]
Thanks for the quick turnaround on the fix

**Comment by obartra** [comment]
Hey I've just tried it with `loaders: [array]` and it works but if I use `use: [array]` it fails with the following error:

```bash
/node_modules/svg-sprite-loader/lib/utils.js:228
    options = multiRule.map(normalizeRule).find(r => r.loader === loaderPath).options;
```

It's easy to work around though (just changing `use` to `loaders`)
