### ISSUE TITLE
`loaders` is valid on webpack 2

### ISSUE THREAD

**Issue by obartra** [kisenka/svg-sprite-loader#99]
`loaders` is deprecated in favor of `rules` in webpack 2 but `loaders` is still valid

https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules

If not supporting it is intentional it may be worth adding a more explicit error message (right now it crashes). I believe this is the affected code:

https://github.com/kisenka/svg-sprite-loader/blob/master/lib/utils.js#L186

**Comment by kisenka** [comment]
@obartra fixed in 2.0.3, please update :)

**Comment by obartra** [comment]
you work fast!
